### ISSUE TITLE
Cannot submit reports when multiple layers share a related table

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#101]
When a service contains two occurrences of data from the same feature class, and that feature class participates in a relationship with a table, reports can only be submitted to the first occurance of that layer in the service.

*Repro steps:*
In ArcMap: 
1) create a feature class with one text field (geometry type not important)
2) create a table with a text field and a long integer field
3) Right-click the gdb -> new -> relationship class
4) Give the gdb relationship a name
5) choose the feature class as the origin feature class adn the table as the destination table
6) Choose 'Composite relationship'
7) Choose default values until asked to set up the primary/foreign key relationship. Choose OBJECTID for primary key and the long integer field as the foreign key
8) Click Finish
9) Add the feature class to the map TWICE
10) Add the related table to the map. The TOC should look like this: 
![6-12-2015 12-33-45 pm](https://cloud.githubusercontent.com/assets/2752195/8138401/4f4f34b8-10ff-11e5-9884-90d206c80217.png)
11) Create feature templates for each of the layers (right click layer in TOC > Edit Features > Organize Feature Templates > create a template)
12) publish the mxd as a feature service hosted in an AGOL organization with Create, Update, and Query capabilities

In AGOL:
1) Create a group and share that group using Reporter
2) Add the newly published service to a new map with editing enabled
3) Save the map and share it with the group created above.
4) Open the Reporter app and submit a report to the first layer in the map - it will succeed
5) Submit a report to the second layer in the map - it will fail

- If you swap the order of the layers in the web map, the same layer will fail. 
- If you swap the order of the layers in the mxd before publishing, the first layer listed will succeed 
and the second will fail.
- If you remove the relationship and table, both reports will succeed

Example application: http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceReporter/index.html?appid=103d560cf1e24e49b465a32a57248b37#
I will send credentials and a map package by email.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
When trying to save feature to the second layer, the API is reporting an error message that 'GlobalID' field cannot be null. Please see screenshot below. It seems like 'GlobalID' is a non-nullable field that is for some reason, not visible in the REST endpoint of the second layer.

![image](https://cloud.githubusercontent.com/assets/2959186/8158575/f7e60132-137b-11e5-8710-7d2d8b421e8a.png)

![image](https://cloud.githubusercontent.com/assets/2959186/8158589/17e95b32-137c-11e5-880c-db59bf316290.png)

**Comment by allisonmuise** [comment]
I have confirmed that this behavior also exists on production AGOL and am waiting for feedback from the Online team on a possible resolution.

**Comment by allisonmuise** [comment]
This is a core issue that can be tracked here: https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/4020
