### ISSUE TITLE
Incorrect details when popup is set to show contents of a single field

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#102]
When the popup in a web map is set to display only the contents of a single field, Reporter shows the full list of fields in the item details.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

It seems to be the default behavior of popups. When popup is set to display only a single field and the field value is empty, the popup will show all attributes of the feature. You can observe this in ArcGIS Map Viewer too.

**Comment by allisonmuise** [comment]
I have confirmed that this is also an issue on production and am waiting on feedback from the Online team.

**Comment by allisonmuise** [comment]
This is a core issue that can be tracked here: https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/2133
