### ISSUE TITLE
Improve handling of long layer names, popup titles

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#103]
Currently app displays '...' when text is too long to display. Would be nice to have some way of displaying these strings on both desktops and touch devices. Could tapping the ellipsis open a window that contains the full text? @CTLocalGovTeam : Do you have any other suggestions to handle this scenario?

**Comment by allisonmuise** [comment]
I like the implemented behavior for the layer names. Can the same behavior be implemented for the popup titles in the list view and at the top of the details pane?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We will implement the same behavior of displaying a popover at the top of issue details pane.

However, we are unable to display the same popover in issue list, as every issue in the list has a primary click action (to display details view). We tried to do a tap-hold, but it conflicts with the click-drag-to-scroll action and the issue list cannot be scrolled at all. 

The full popup title is always displayed in the details view just below the pane title. However, users will always have to tap an issue in the list to view its full title in the details view.

**Comment by allisonmuise** [comment]
ok, that makes sense.

**Comment by allisonmuise** [comment]
verified
