### ISSUE TITLE
Increase touch buffer around info button

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#106]
info button on map list is very difficult to open on iPhone. Buffer should be expanded.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Increasing touch buffer may have undesirable effect that text may appear with an ellipsis when there is still some space available.
We could increase the size of the info icon from its current 16x16 px to either 18 or 20px.
Please let us know your preference.
![image](https://cloud.githubusercontent.com/assets/2959186/8674822/f3015bbe-2a5d-11e5-9431-0631d3b47841.png)

**Comment by allisonmuise** [comment]
I agree with allowing as much space as possible, but opening the map info panel on an iPhone is so difficult that I thought the info button wasn't working. I don't have this issue on Android phones.

What are the other options?

Can the touch buffer be increased to 18x18 without increasing the size of the graphic? I am guessing that this touch buffer is clear space, so the padding between text and info button could be decreased?

Could the touch area of the title be decreased slightly? This way it's harder to trigger opening the map when tapping the right side of the panel.

Could the size of the info button be increased on smartphone only? (really don't want to do this because title space is already smaller on phones)

**Comment by allisonmuise** [comment]
Let's increase the size on smartphones only. I still can't get the info button to open the map details on a smartphone.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Ok. We will increase the size to 20px on smartphones only.

![image](https://cloud.githubusercontent.com/assets/2959186/9219112/2c558562-40f6-11e5-8963-3f13ac8c0d2a.png)

**Comment by allisonmuise** [comment]
verified
