### ISSUE TITLE
Add 'home' to map navigation 

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#111]
Add the home extents button to the navigation tools on the main map only (not the geoform)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Just wanted to confirm the order of map navigation controls. Is this ok ?

![image](https://cloud.githubusercontent.com/assets/2959186/8722247/1e760384-2be0-11e5-9fe0-22d599cc0623.png)

**Comment by allisonmuise** [comment]
Can Home go between + and -? If so, that would be preferable.

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann @LindsayThomas @allisonmuise 
When geolocation is not available, map loads default webmap extent. In this case, clicking 'home' will take user back to default webmap extent.
However, when geolocation is available, on app load, it will auto-zoom to the buffer area of user's current location. On clicking 'home' icon in this case also, should we zoom to webmap's extent? 
Please confirm.

**Comment by allisonmuise** [comment]
Yes, this is correct. Home should always return to the web map extent.

**Comment by allisonmuise** [comment]
verified
