### ISSUE TITLE
Consider storing the social media alias

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#115]
Currently, only the GUID of the social media account is stored. Consider providing an optional configuration parameter for the user alias associated with that account. 

Where the alias is available, it would be used as the default value for the field, otherwise it would be left blank. 

Whether this field is editable or not by reporters would be controlled by the popup settings. If an alias is available, and the field is not exposed int he form, the alias should still be written to the field.

@ScottOppmann :What do you think of this?

**Comment by aparveen** [comment]
We don't support Google plus and Facebook anymore. Closing this issue.
