### ISSUE TITLE
Spacing on splash page

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#117]
The spacing of the elements on the splash page is not very even, and the proportions vary between smartphones and desktop browsers. 

Please make the spacing the same between each of the following elements on both desktop and smartphone browsers:

- title & subtitle
- Guest sign in
- 'Or' bar
- Social media sign in
- help link

If no social media sign in options are enabled, the help link should move up to maintain spacing below the guest sign in

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here are the revised screen's for splash page.

![image](https://cloud.githubusercontent.com/assets/2959186/9303995/06eddae0-4501-11e5-972b-ada2c5741649.png)

Please let us know your feedback.

**Comment by allisonmuise** [comment]
The one with Sign in options looks good.

On the one without sign in options the 'Or' bar should be hidden.

**Comment by allisonmuise** [comment]
verified on iPhone and desktop
