### ISSUE TITLE
Toggle Guest mode and other sign in capabilities

### ISSUE THREAD

**Issue by DShokes** [Esri/crowdsource-reporter#120]
It would be great to be able to turn guest use on or off.  There are use cases where some sort of user identification is a requirement.

Another idea is to allow any oath 2.0 server to be used for user sign in. This would be set in the configuration interface.

A third idea would be to allow preset login info to be accessed from a table on a featureservice. Site leaders for a volunteer event could be given predefined usernames so that  each location was easier to monitor.

**Comment by allisonmuise** [comment]
@DShokes : 

1) I will submit this one for consideration in a future release. For now, you can force sign in by making the app non-public.

2) This is possible if you've enabled enterprise sign ins for your organization.

3) A better (simpler, more secure, easier to manage) way to do this would be to create accounts in your organization for these users. We have no plans to replicate user/password management workflows that already exist in ArcGIS Online/Portal within the structure of this application.

**Comment by DShokes** [comment]
Great, thanks for this info!
