### ISSUE TITLE
Provide option to disable Guest access

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#121]
For those use cases where every report must have a user tied to it. If possible, prevent disabling Guest access if all other sign in options are also disabled, otherwise there will be no way to move past the splash screen.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We have added a new item "Enable Guest Access" to the configuration panel. When this is turned off and none of the other sign-in options are enabled, then the splash screen is displayed without any option to proceed ahead.
Please let us know if this looks ok.

### When only guest access is disabled ###
![image](https://cloud.githubusercontent.com/assets/2959186/12350744/06849098-bb9f-11e5-8133-eb2ed9c30fca.png)

### When all sign-in options are disabled ###
![image](https://cloud.githubusercontent.com/assets/2959186/12351183/b8a16ab0-bba1-11e5-930f-291811c589f6.png)

**Comment by allisonmuise** [comment]
Yes, this is the expected behavior.

**Comment by allisonmuise** [comment]
verified
