### ISSUE TITLE
Removing splash screen when PortalLogin is turned off

### ISSUE THREAD

**Issue by erikkross** [Esri/crowdsource-reporter#122]
Is there a way to remove the splash screen from showing when the option enablePortalLogin is set to false? It would be much better if the application just loaded instead of the user having to click the guest link.

**Comment by allisonmuise** [comment]
There isn't currently a way to do that, but it's a good idea. We'll look into this for a future release.

**Comment by erikkross** [comment]
I figured out a way to do it by modifying the source code. Not the most elegant solution, but it works for my needs. In the /js/widgets/sign-in/sign-in.js file I added the following to the end of the startup() function: 

    //skip the splash screen
    this._guestButtonClicked();

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
When none of the login providers are enabled (google, facebook, twitter, portal) and when guest access is disabled, currently the app displays the splash screen without any options to login and proceed, please see issue #121 

We think we should retain the above behavior and disable the splash screen only when guest access is enabled and all other login providers are disabled.

Please let us know if this sounds ok.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Based on feedback I received last week, let's go with the following:

- Hide the splash screen only when ALL sign in options (Guest, AGOL, FB, G+ and Twitter) are disabled.

- If any of those options is enabled (including just Guest), the splash screen should display.

The reason for this is the Help/Terms of use link on the splash page. Many organizations require that all application users (including anonymous ones) be presented with terms of use before accessing the application, although they may not want to manage social sign ins.

**Comment by allisonmuise** [comment]
verified. This will be included in the next release of ArcGIS Online.
