### ISSUE TITLE
Version of reporter in AGOL templates

### ISSUE THREAD

**Issue by DShokes** [Esri/crowdsource-reporter#124]
Where can we see which version of reporter is currently used for the AGOL app template and where will notifications be found when the template is updated? I'm weighing the benefits of hosting myself vs using available template.

**Comment by allisonmuise** [comment]
With the exception of a few hours around the time of AGOL updates, the Master branch is the version of the apps currently available on AGOL. If you're interested, what's currently in the develop branch is what we are working on for the next release. 

As for notification - There are typically emails and blog posts by the ArcGIS Online team when there are updates to AGOL. If you're interested in what specifically has changed for Reporter you can check the What's New section of this page: http://solutions.arcgis.com/local-government/help/crowdsource-reporter/ . That page usually updates within a week or two of release. 

I recommend using the hosted app unless you need to host the app on your own infrastructure for security reasons or if you have a strong need to customize the code. As part of AGOL, your app will automatically get bug fixes, enhancements, and new functionality every few months when AGOL updates.

As a side note: You've had lots of great feedback and I'd love to see how you're using this app. We're always looking for great use cases and user stories to help us direct future dev work. If you want to share, you can reach me at amuise@esri.com.
