### ISSUE TITLE
In RtL languages, help title overlaps with help dialog close button

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#126]
![8-27-2015 3-21-05 pm](https://cloud.githubusercontent.com/assets/2752195/9534701/67cf3ae0-4ccf-11e5-92f1-739590f933f4.png)

**Comment by allisonmuise** [comment]
This is still an issue

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We had missed accounting for one parameter that identifies if app is running in RTL mode to load RTL CSS. This is a minor fix and will be included in next code drop.

**Comment by allisonmuise** [comment]
verified
