### ISSUE TITLE
Placeholder text is not displayed for search bar in IE9 browser

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-reporter#127]
@allisonmuise 
This is related to the issue that is fixed in manager app https://github.com/Esri/crowdsource-manager/issues/76 

All modern browsers display the placeholder(hint) text when the textbox is empty and even if focus(cursor) is inside the empty textbox. 
![image](https://cloud.githubusercontent.com/assets/2959186/9605105/56c99d68-50d9-11e5-9033-825bd6079a19.png)

To provide support for older browsers(IE9), we have to programmatically set the hint text as the value of the textbox when its empty. This works only if the textbox does not have focus. If the textbox does not have focus and is empty, then the hint text is correctly displayed. The moment you click inside the textbox in IE9, the textbox needs to be emptied to accept user input and it cannot display the hint text (see image below).

![image](https://cloud.githubusercontent.com/assets/2959186/9605288/764781f4-50da-11e5-90d4-e7220831af4b.png)

The reporter app displays a search bar in two places, one while submitting a report (geoform) and other on map, below the zoom buttons. The search bar in geoform does not have focus set on load, hence it will display the hint text in IE9, until user clicks inside the textbox. 
However, the search box on map, when expanded, automatically gets focus and hence the hint text is never displayed in IE9. 

We can fix this by not setting focus automatically, when search box is expanded, so it displays the hint text. But users will now have to do an additional click to search. One to expand and the other to click inside the textbox and then start typing the desired search term. 

Please let us know if we should go ahead and **not** set the focus automatically when the search box is expanded.

**Comment by allisonmuise** [comment]
Thanks for the detailed explanation! Based on this information, please continue setting the focus automatically.
