### ISSUE TITLE
In RtL languages, geoform search box layout is off

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#128]
Firefox with content language set to Hebrew:
![9-2-2015 2-22-38 pm](https://cloud.githubusercontent.com/assets/2752195/9645043/4a4e2612-517e-11e5-81ff-6cffbe44ede3.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are including this in the upcoming delivery.

**Comment by allisonmuise** [comment]
this is still an issue

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We had missed accounting for one parameter that identifies if app is running in RTL mode to load RTL CSS. This is a minor fix and will be included in next code drop.

**Comment by allisonmuise** [comment]
verified
