### ISSUE TITLE
Timed interval to bring in features submitted by other users

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-reporter#132]
@allisonmuise 

We are thinking of the following approach for implementing this feature. Please let us know your thoughts.

* When auto-refresh is triggered on the time interval, it should only get newly added features within the last buffer extent that was used to add features on map (user may have clicked "View More" to expand the buffer a couple of times). 
* The newly added features should be sorted by distance and added to the issue list.
  * This could be a time consuming process based on no. of features in the layer and on map.
  * The app will have to query all OIDs and compare them with the ones added on map and find the new ones.
  * Also edits to attributes of existing features cannot be updated. This will be very time consuming, as each attribute field will have to be checked for each feature on the map, since its a separate graphics layer.
  * Compute the distance of the new features to user's current location and add them to the list of issues in their correct order by distance.
* We cannot trigger the auto-refresh automatically as user may already be interacting with the app and may disrupt his workflow by redrawing the issue list.
* We think the best place to auto-refresh is in two places, 
  * when time interval has elapsed and user navigates to issue list from any other view. At this time, the auto-refresh is triggered and issue list is redrawn with new features.
  * when time interval has elapsed and user is already on the issue list view and idle.
* Should we expose the time interval as a configurable item? Considering the time intensive nature of this operation, a minimum of 3 mins interval is recommended.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam :
Sorry for the delayed response on this. 
For now, let's not do the auto/timed interval refresh. Instead, the list & map should only refresh when:
-  a map is chosen from the map list, including when the current map is re-selected, or
- a layer is chosen from the layer list, including when the current layer is re-selected, or
- when accessing the My Issues list

**Comment by allisonmuise** [comment]
cc: @ScottOppmann @NikkiGolding @MikeMillerGIS

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Currently when you click on a map in list, if it contains only one layer, it does not reload the layer and displays the list of issues. 
However, if you click on a layer (map with multiple layers), then it always reloads. Hence in such case of maps with multiple layers, clicking on the layer again will go back to initial state of 1 mile buffer.

The My Issues list is always updated whenever user reports an issue from the app. Do you mean the My Issues list should be updated if two users submit issues simultaneously using the same credentials?

**Comment by allisonmuise** [comment]
> Currently when you click on a map in list, if it contains only one layer, it does not reload the layer and displays the list of issues.

Can a reload be added here? I understand that this will return the buffer to it's original range and that's ok.

> However, if you click on a layer (map with multiple layers), then it always reloads.

ok, good


> Do you mean the My Issues list should be updated if two users submit issues simultaneously using the same credentials?

no, this isn't necessary if that list is being updated when users submit reports

**Comment by allisonmuise** [comment]
verified
