### ISSUE TITLE
Update .container references

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#134]
The following change has been made in JS API 3.15; please update Reporter accordingly:
![9-21-2015 1-16-57 pm](https://cloud.githubusercontent.com/assets/2752195/10003833/6575d78e-6063-11e5-9d67-39f2ab3b0e15.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
JSAPI v3.15 isn't out yet.
Can you please provide us a link to the dev version?

**Comment by MikeTschudi** [comment]
Thanks for checking. We wanted to be sure that the app's use of bootstrap's container class was not affected by the removal of Esri's container class.
