### ISSUE TITLE
Need to sign in twice to access app

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#143]
When accessing the app for the first time using a method other than 'Guest', I have to sign in twice. For example:
1. clear cache
2. Load app
3. click ArcGIS sign in button (or FB, G+, Twitter)
4. enter credentials/ authorize app
5. app returns to splash screen and I have to click the ArcGIS button again in order for the app to proceed.

If I repeat steps 2-4, the app loads after providing my credentials/authorizing app.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are unable to reproduce this. Can you please share a link to the app?

**Comment by allisonmuise** [comment]
This is reproducible with multiple reporter apps hosted locally and in devext, and with all tested browsers and devices (IE11, Chrome, FF, Tab 2, Tab S, Galaxy S4, iPhone 5, iPhone 6, iPad3, iPad 2). 

The cache (including passwords) must be cleared before beginning the test. I will demonstrate this behavior on tomorrow's call.

**Comment by allisonmuise** [comment]
this is non-repro for the social media, and as-designed for AGOL. The app reloads when returning from the identity manager, therefore the splash screen is re-displayed.
