### ISSUE TITLE
help window close button does not work consistently on iPhone

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#144]
tapping the X in the upper right corner of the help window doesn't consistently close the help window on iPhones.
iPhone 6 takes 5-10 attempts to close. *
iPhone 5 closed successfully in 15-35 attempts*

This is not an issue on android phones, android tablets, or iPads (window closes on first try most times. If first try not successful, 2nd try works)

Is it possible that the image is contained within a div that has smaller dimensions than the image, and the touch action is being triggered on the div? From talking to other developers here, I understand that most browsers should stretch the div to the contents, but perhaps that is not happening on the version of Safari that ships with iOS 7 (specifically, I am using iOS 7.1.2)?

*Please note that the only person who was able to consistently close this window in 1-2 touches was also the only tester who is a regular iPhone user.

**Comment by previnWong** [comment]
@CTLocalGovTeam  so it seems like the button div has no width or height.  But the Close Helper div does have width and height.  So it seems Chrome stretches the button div to encompass the close helper, but my guess is that safari does not.

![image](https://cloud.githubusercontent.com/assets/11183838/10439681/6acd8464-70f0-11e5-8c0f-984d8307f2dc.png)

![image](https://cloud.githubusercontent.com/assets/11183838/10439689/8004cedc-70f0-11e5-8535-240b0655c546.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @previnWong 
We have fixed this by changing the CSS so that the button div now gets at least 18x18 px height and width. However, we are testing it on iOS v8.3.

**Comment by allisonmuise** [comment]
verified - still takes a few tries, but easier than before.
