### ISSUE TITLE
show domain codes, not values

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#145]
If both the feature layer popup and the comment table popup contain fields with coded domains (1: yes, 0: no), the feature layer will show the value (0 or 1) and the comment will show the code (yes or no).

In both cases, the code should be displayed.

**Comment by allisonmuise** [comment]
![10-12-2015 2-49-09 pm](https://cloud.githubusercontent.com/assets/2752195/10439759/0f42511e-70f1-11e5-811d-c58ed31135a0.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are able to reproduce this and are investigating it.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We have fixed this on our side. This required a minor fix in the way the popup configuration was referring to the feature's properties.

**Comment by allisonmuise** [comment]
verified
