### ISSUE TITLE
Only AGOL-hosted layers accessible in Reporter

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#146]
Services that were published using ArcGIS for Server are not accessible through Reporter, even though they are editable, and added to maps with editing enabled on the layer.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are unable to reproduce this on our side.

Are you seeing this behavior on other browsers as well? We have usually seen this occurring in firefox, when the ArcGIS Server is secured with a self-signed or domain certificate and firefox simply drops such layers unless you add a security exception for the certificate.

**Comment by allisonmuise** [comment]
I am seeing this behavior with all browsers and devices tested so far - FireFox, Chrome, IE11, android phones and tablets, iPhones, and iPads.

The maps with server layers load and can be edited through the AGOL map viewer in those same browsers.

**Comment by allisonmuise** [comment]
This appears to have been an issue with the specific server hosting the layers I was testing with originally. I cannot repro this issue with another server installation.
