### ISSUE TITLE
Show non-editable layers in web map as contextual information

### ISSUE THREAD

**Issue by dcesri** [Esri/crowdsource-reporter#147]
Hi, 

Thanks for this great app!  I'm working with a customer to crowdsource feedback on the quality of certain outdoor paths here in the UK.   Ideally we need people to be able to view the path within this application without being able to edit or add new features to that layer.  Their feedback will be collected on a separate feature layer.  Could this option be considered as an enhancement?  

Please let me know if you need any further information.  

Many thanks, 

Dan Cronin
Esri UK

**Comment by allisonmuise** [comment]
@dcesri :
This has been a popular request and it's definitely under consideration for a future release ( #84 ) . Use cases such as this one are helpful in designing this work.

To keep all the feedback on this enhancement in one location, I'm going to close this issue as a duplicate and reference it from the existing issue on this topic.

Thanks!

**Comment by allisonmuise** [comment]
Re-opening as #84 addresses both display and editing of multiple layers. We're going to look at display of multiple layers only for 4.2.

**Comment by allisonmuise** [comment]
Possible option for implementing this:

Add a boolean in the config panel that is False by default to allow display of non-editable layers. This way users can opt in to this behavior, protecting any previously-hidden layers that the may have included in their Reporter maps. When this booleen is True, all (visible) non-editable layers are displayed along with each editable layer.

**Comment by dcesri** [comment]
Great news, thanks!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

I don't see this capability. I created a map with the following layers:
1. Hosted feature layer with create, edit, delete permissions and popup enabled with editable fields
2. Dynamic Map Service (uneditable)
3. Hosted feature layer with create, edit, delete permissions and popup enabled, but all fields marked display only
4. Hosted feature layer with create, edit, delete permissions, but disabled on the layer in the map TOC.
5. Hosted feature layer with all editing capabilities disabled on the service.
6. Hosted tiled layer

Only the first layer is showing up in the application. I would expect all the other listed layers to show up in the same view as the editable layer.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise   
>1 Hosted feature layer with create, edit, delete permissions and popup enabled with editable fields

This is presented in map list as it is editable and works as expected.

>2 Dynamic Map Service (uneditable)

This is not implemented. Will implement this.

> 3 Hosted feature layer with create, edit, delete permissions and popup enabled, but all fields marked display only  

We didn't consider this case. We will implement this.

>4 Hosted feature layer with create, edit, delete permissions, but disabled on the layer in the map TOC.

We didn't consider this case. It does not show up in map list currently. Will implement this.
Also, if a webmap contains all layers turned off, the webmap will not show up in list. If it contains all non-editable layers, it wont show up in list.

>5 Hosted feature layer with all editing capabilities disabled on the service.

This is implemented. Can you please share an app so we can investigate this.

> 6 Hosted tiled layer

This is not implemented. Will implement this.

Currently, the app is considering only feature layers that are non-editable to be displayed as is. We can modify this easily to support any kind of non-editable layers to be displayed as is.

**Comment by allisonmuise** [comment]
Thanks!

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We will implement this ticket as per the scenario mentioned in crowd source manager issue [88](https://github.com/Esri/crowdsource-manager/issues/88)

-Ashish

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : The uneditable layers seems to consistently show up underneath the editable layers. They should show up in the same order they are placed int eh TOC of the web map.
