### ISSUE TITLE
BUG-000092488 The Crowdsource Reporter web app does not allow to submit a new report if the layer is a server service without an existing feature. 

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#156]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/1012

Open Web App http://ess.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=29ed1393e7fe4f1c9995c0623ffb0611
Click "Proceed as Guest"
There are four maps:
"Hosted Empty Web Map" - Layers hosted in AGOL with no features
"Hosted with Points Web Map" - Layers hosted in AGOL with a single feature in each layer
"Server Empty Web Map" - Layers hosted on ArcGIS Server with no features
"Server with Points Web Map" - Layers hosted on ArcGIS Server with a single feature in each layer

The schema for the layers was downloaded from:
http://www.arcgis.com/home/item.html?id=83ffd94efd1d45688b994abd60736fbe

Click on the first map "Hosted Empty Web Map"
Click on the first layer "CitizenProblemReportsHosted - Animal_Problems"
Notice that the "Submit a report" option is available

Click the "Go to main list" button

Click on the second map "Hosted with Points Web Map"
Click on the first layer "Hosted_w_Points - TestParent.SDE.Animal_Problems_1"
Notice that the "Submit a report" option is available

Click the "Go to main list" button

Click on the third map "Server Empty Web Map"
Click on the first layer "CitizenProblemReportsServer - TestParent.SDE.Utility_Problems"
Notice that the reports window doesn't open and the "Submit a Report" option is not available

Click the "Go to main list" button

Click on the Fourth map "Server with Points Web Map"
Click on the first layer "Server_w_Points - TestParent.SDE.Animal_Problems_1"
Notice that the "Submit a report" option is available

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

On our side we are able to see ony two webmaps.
![image](https://cloud.githubusercontent.com/assets/2959186/11813993/7407dc9e-a36a-11e5-88e6-f00bc355bc58.png)

We also tried to reproduce this issue with services from our side and see that it works as expected. Please see this link http://203.199.47.146/csreporter/issue156/

The first layer in the webmap does not have any features and we are able to submit reports.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I believe you are seeign only the AGOL maps because the layers in the others were published to an internal server (not mine so I can't verify). I was unable to get an example stood up on an external server today so I'll share my screen in the meeting tomorrow. I am able to reproduce this with multiple layers in multiple orgs. I cannot access the app referenced in your comment.

**Comment by allisonmuise** [comment]
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=c7b9281cabaa4bc2bb16f8dd92fc3779

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The above link was working earlier, however now we get an error "Configured group is invalid or no items have been shared with this group yet." Maybe the contents are private, can you please check and let us know?

Also, we went through the layer schema (mentioned in first comment) and observed that all the layers present in feature server doesn't have create or update capabilities.

**Comment by allisonmuise** [comment]
I've updated the sharing on the items. They should be accessible again.
With regards to the service capabilities - Is there a way that we can let people know when this is the source of an issue?

**Comment by allisonmuise** [comment]
verified
devtopia issue updated
