### ISSUE TITLE
Add method for sharing app

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#157]
specifically - a specific view into the app - the current layer, report, etc

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is our approach to implement the share functionality.

On click of share icon, share dialog will be opened with text box for showing the application URL. The URL will contain parameters such as "webmap", "layerid" and "oid" based on following conditions : 
- If the user is on web map screen, the URL will contain only web map id. 
- If the user is on the issue list screen, the URL will contain web map and layer id.
- If the user is on the issue details screen, the URL will contain web map, layer and selected features object id.

Here is the screenshot of share dialog:
![image](https://user-images.githubusercontent.com/5525972/44718358-6ee81d00-aadd-11e8-9715-72faea66b7c6.png)


The URL shown in the screenshot in just a sample. We are planning to show the bitly URL in the text box.

**Comment by allisonmuise** [comment]
this looks good @ashishchoure . I will get back to you on using bitly and the share icon after talking to the AGOL team about what they use.

**Comment by allisonmuise** [comment]
@ashishchoure I am sending you an email conversation that contains links to preferred alternates to bitly and the share graphic.

**Comment by ashishchoure** [comment]
@allisonmuise 

As per the email conversation, here is the screenshot for the share icon in application header (highlighted in orange color).
![image](https://user-images.githubusercontent.com/5525972/45086376-a0d23280-b120-11e8-952e-f63e395e1cf0.png)

Let us know your thoughts.

**Comment by allisonmuise** [comment]
@ashishchoure looks good!

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@allisonmuise : added testcase
