### ISSUE TITLE
Date picker mismatch between type-in field value and calendar selection

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-reporter#158]
Change the date in the date picker and submit a report.  The blank form that appears for a new report shows the current date in its type-in part and the previously-selected date in its calendar.

![image](https://cloud.githubusercontent.com/assets/2125181/12096788/b40ee51e-b2cc-11e5-98e0-85318b3999a6.png)

The new report uses the calendar date.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Although we provided a fix this in V2.8, we have discovered a scenario where user is unable to cancel out of geoform. Clicking cancel doesn't do anything. This happens only when the layer has both, a date  field with range domain and a number field with range domain applied with default values set for both. The code change for this fix is minor.

Please let us know if you'd like us to submit a pull request with this fix or if you'd like us to include this in next delivery for the 4.2 milestone.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Yes, please submit a pull request with this fix and I will include it in 4.1.
Thanks!

**Comment by allisonmuise** [comment]
verified
