### ISSUE TITLE
Allow configuration of form headers

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#161]
Expose the form headers ('Location', 'Attachments', etc) in the app configuration panel.

(requested by Scott Moore via Nikki 1/19/2016)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : would this change be low LOE? Could this be added easily to the 4.2 changes?

**Comment by allisonmuise** [comment]
@NikkiGolding : Spoke with Dr Anand about this today. This is not as simple as pulling these strings into the configuration file, because doing that would change all headers in non-english apps to the default english strings.

The CT team is going to evaluate the LOE required to expose these strings in the configuration panel while still displaying the NLS strings when the default values are used.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is the approach that we followed to implement,

Add new parameters in configuration for headers (Details, Location, Attachments)

* If existing application does not contain new parameters in configuration, then form headers will always be shown from NLS 

* All new apps will check if it contains new parameters 
  * if they match the default value, then form headers will be shown from NLS
  * if they dont match, which means user has provided their own, then always show values as configured.

**Comment by allisonmuise** [comment]
cc @NikkiGolding

**Comment by allisonmuise** [comment]
verified that these strings can now be edited in the configuration panel. The default strings are handled in the nls files, custom strings are not. Returning the strings in the config panel to the default values re-allows accessign the values through the NLS files.
