### ISSUE TITLE
Calender UI not localzied

### ISSUE THREAD

**Issue by shohei-51** [Esri/crowdsource-reporter#163]
When running the Crowdsource Reporter in Japanese environmnet, most of UIs such as submit report button get localized to Japanese except the calender UI. GeoForm uses the localized calender UI in Japanese environment. Please consider enable localization of the calender UI.

![calendar_not_localized](https://cloud.githubusercontent.com/assets/11626200/12939213/763e00ca-d000-11e5-8e66-11a9afb95d10.png)

**Comment by allisonmuise** [comment]
@shohei-51 : Thanks for reporting this, we'll look at a fix for a future release.

@CTLocalGovTeam : Is this a small fix that could be added to the 4.2 release?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam

**Comment by allisonmuise** [comment]
verified
@shohei-51 : This will be fixed in the next release of ArcGIS Online.
