### ISSUE TITLE
Add support for maps with multi-layer basemaps

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#166]
Multi-layer basemaps are going to be new at 4.1. Reporter currently doesn't support them, so this functionality will need to be added.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : When the map uses a multi-layer basemap the geoform fails to load. The main map loads without issue.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We tested this funcitonality with webmaps contaning multi layer basemaps but we were unable to reproduce the issue. Can you please share a webmap?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
I can now only reproduce this with one layer that was published while devext was experiencing other issues. Last week I was seeing this behavior with all layers. I'm going to close this issue for now, but will reopen it if testing turns up a more reliable repro case.
