### ISSUE TITLE
Enhancement - Make list of existing issues hidden until view existing is clicked

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-reporter#171]
Feedback was that the list of existing issues was confusing as it appear to be items types you could log.  Suggestion was to replace the list with two buttons, Submit and View existing.  On the click of view existing, the existing items list would be shown.

**Comment by allisonmuise** [comment]
Could these two functions be better distinguished in the existing app by allowing the configuration of the 'Submit a report' button?

We are trying to reduce the number of clicks needed to submit a report so I don't really want to add another step in the submission process. It was also a deliberate decision to force people to see what's already been reported near their location before they choose to submit something new.

**Comment by ChrisBuscaglia** [comment]
My interpretation of this requirement was to make the submit more prominent and not on the bottom of the screen.

**Comment by allisonmuise** [comment]
@MikeMillerGIS & @ChrisBuscaglia : The placement of the button at the bottom and the display of exsting issues were deliberate choices in the app design and we haven't received enough feedback at this point to consider redesigning this UI. 

The text and color of the submission button are going to be made configurable over the next two releases (text this release, color next) which will allow users to increase the contrast between the button and their color scheme.
