### ISSUE TITLE
Enhancement - Clustering of existing issue

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-reporter#172]
Feedback was that there could be a lot of request, 4-6K open issues.  Cluster is required to group together to make a legible map

**Comment by allisonmuise** [comment]
We are trying not to modify the layer symbology via the app. Is there a smartmapping option for clustering? If there is, the app should honor it.

**Comment by ChrisBuscaglia** [comment]
You can use a heat map based on the issues and then adjust the 'Area of Influence' options.  This could also help someone identify high volumes of issues.

**Comment by allisonmuise** [comment]
something to consider - #152

**Comment by allisonmuise** [comment]
closing this as the enhancement is not really for this app. Support for heatmap symbology is already covered elsewhere.

**Comment by ScottOppmann** [comment]
@allisonmuise - I think what @MikeMillerGIS @ChrisBuscaglia were really talking about is point clustering much like the Local Perspective application does.  Would be very valuable for larger organizations that have many submitted observations.  Not sure when/if the webmap will support such, but if it does, we should include.  Perhaps the best course of action is to keep this issue open and in the backlog pending feedback from others.

**Comment by MikeMillerGIS** [comment]
Scott is correct.

**Comment by allisonmuise** [comment]
@ScottOppmann @MikeMillerGIS : I understand what you are looking for and agree it would be a great enhancement - to AGOL. Let's discuss further on Thursday.

**Comment by allisonmuise** [comment]
closing - AGOL team is working on clustering. Apps will support it once implemented.
