### ISSUE TITLE
Enhancement - Implement page on result list

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-reporter#173]
Since the existing features list can grow, to speed up loading and improve the user experience, implement paging to only show X number of records at a time

**Comment by allisonmuise** [comment]
This exists already. If you share your location with the app, only the features within a configurable distance and within the server limits will load. To adjust this, you can either lower the number of features that can be loaded at once by the service, or decrease the search distance.

**Comment by MikeMillerGIS** [comment]
great, closing
