### ISSUE TITLE
Enhancement - Hide issues when user is anonymous

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-reporter#175]
Feedback was only certain issues can be reported when the use is anonymous, once the user logs in, additional items they can report are visible.  This all needs to be in the same app.

**Comment by allisonmuise** [comment]
The only way to support this under the current licensing model is to make some layers only visible to members of the organization and to open the org up to creation of accounts through social media. Expanding this through this application is not something we'll look at.
