### ISSUE TITLE
'Back' button points the wrong way for RtL languages

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#177]
'<' is 'back' for LtR and 'forward' for LtR
'>' is 'forward' for LtR and 'back' for RtL

Need to update arrows in app for RtL languages.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

In addition to updating just the arrows we think it make sense to re-position the following components:

1) Layer title in webmap list
![image](https://cloud.githubusercontent.com/assets/2959186/17167952/614a5a52-53fd-11e6-9f72-ec2314be7ef1.png)

2) Issue list header 
![image](https://cloud.githubusercontent.com/assets/2959186/17168031/c6f01360-53fd-11e6-9151-db3a1156ddd5.png)

Please let us know our thoughts.

**Comment by allisonmuise** [comment]
yes, please make those changes as well.

**Comment by allisonmuise** [comment]
verified
