### ISSUE TITLE
Adjust splash screen spacing

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#178]
Guest option should display centered between the help and app title when there is no subtitle, no other sign in options, and the help window is enabled.
![2016-03-30 3-22-22 pm](https://cloud.githubusercontent.com/assets/2752195/14159590/70649c16-f68b-11e5-85cf-9694f1c6e291.png)

**Comment by allisonmuise** [comment]
Spacing is off even when there is a subtitle:
![2016-03-30 3-47-02 pm](https://cloud.githubusercontent.com/assets/2752195/14160051/bb195ffa-f68e-11e5-92c1-bc2b51864c1f.png)

**Comment by allisonmuise** [comment]
Could we also leave the title and guest sign in options at the same location on the screen as when there are social media sign in options enabled? The title looks better sitting above the midpoint on the screen and it keeps the Guest option i the middle.

**Comment by allisonmuise** [comment]
OTOH, the spacing looks squished when anonymous access is disabled, with or without Help:
![2016-03-30 3-51-02 pm](https://cloud.githubusercontent.com/assets/2752195/14160138/4b2699be-f68f-11e5-8ed1-5778f346c804.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Please look at the new screens of sign-in (splash screen) in various scenarios.

1.
![image](https://cloud.githubusercontent.com/assets/2959186/14176722/0827efe6-f770-11e5-89fc-e601a754325e.png)

2.
![image](https://cloud.githubusercontent.com/assets/2959186/14176824/b3f7a9b0-f770-11e5-96b5-4f2bc48a1813.png)

3.
![image](https://cloud.githubusercontent.com/assets/2959186/14176872/efca9c22-f770-11e5-8256-f88ffea146d4.png)

4.
![image](https://cloud.githubusercontent.com/assets/2959186/14176947/52b6ffce-f771-11e5-9a71-ac730462d3b1.png)

Please let us know if this looks good.

**Comment by allisonmuise** [comment]
Much better! Thanks!

**Comment by allisonmuise** [comment]
verified
