### ISSUE TITLE
Submit a report button color doesn't align with theme color

### ISSUE THREAD

**Issue by jessnoo** [Esri/crowdsource-reporter#179]
The bright green doesn't always fit in with the selected theme color. Can it be tied to the theme color or an option exposed to choose an alternate color?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can do this either way, theme color or configurable color. Both options are low LOE and low risk. Please let us know your preference?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Can you please let us know your preference, theme color or configurable color?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : configurable color, please

**Comment by allisonmuise** [comment]
verified on devext @jessnoo
