### ISSUE TITLE
BUG-000095120 The Crowdsource Reporter web application does not show labeled features in the main map frame.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#180]
Devtopia 1157

Steps to Reproduce:

    Open the Crowdsource Label Map and notice that the features in the layer are labeled.
    Open the Crowdsource Label App application, built from a group that the Crowdsource Label Map was shared with. Notice that the features in the main map frame are not labeled.
    Click on "Submit a report" to bring up a smaller map that can be used to create a new location. Notice that the smaller map shows the labels of the features.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam:

Labels are only displaying for features in the geoform map They should display on the main map as well. Could you take a look and see if this is something quick'n'easy that can be done for this release? If not, I'll push to the following milesstone.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The reporter app uses a graphic layer instead of directly adding the feature layer due to implementation of geo-filtering. Graphic layers do not support labeling. 
The geoform map does not use graphic layer, hence it is able to display the labels.
We don't see a quick and easy way to display labels on the main map. We'd have to handle them separately including label placement, conflict detection etc.

**Comment by allisonmuise** [comment]
OK, is it possible to hide the labels in the geoform map, then, so that it's a consistent experience?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

The un-editable layers will support labeling in the main map as well as geoform map. They are not altered in any way.

We assume that we still want to hide labels of 'editable' layer in the geoform map, correct?

**Comment by allisonmuise** [comment]
yes, please

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
The following app contains one map with 3 layers:
 - ChartsAndDatesEditable: The only editable layer
 - ChartsAndDates: This is the same underlying layer as ChartsAndDatesEditable, but with editing disabled in the TOC, and labels turned on
- HealthAndSafetyReports: Separate layer with editing disabled in the TOC and labels turned on.

Labels are only showing for the HealthAndSafetyReports (cow icon) layer. 
http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceReporter/index.html?appid=60da44805bb84440a4009c45694d2fec

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are not able to access the above link.

![image](https://cloud.githubusercontent.com/assets/2959186/14606206/c2052456-0599-11e6-815a-bcad74aa24e8.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are still not able to access this map. Can you please update the permissions.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Sorry for the delay, I have been out of the office.

Here is a new app: http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceReporter/index.html?appid=3f58be292b224af78cbc14c22f6a5306

You should be able to access it as a guest. Now I am seeing labels for both non-editable layers in the main map, and no labels in the geoform map.

**Comment by allisonmuise** [comment]
actually - the nun-editable layers aren't displayign at all in the geoform map, which is a duplicate of #189 so closing this issue
