### ISSUE TITLE
App displays geolocation button even if browser doesn't support geolocation

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-reporter#181]
lines 50 to 56 in bootstrapper.js check if the browser supports geolocation and sets `config.geolocation` with the result. This switch is not checked either in main.js before it calls `this.appUtils.createGeoLocationButton` or in that function's definition in utils.js, so the geolocation button is always created.

**Comment by CTLocalGovTeam** [comment]
@MikeTschudi 

`config.geolocation` property is not used to control the visibility of geolocation button. It used to control the geographical filtering functionality of application.

Please let us know if this answer’s your question.

**Comment by MikeTschudi** [comment]
Thanks for the correction!  And it handles the Chrome 50 secure-origin issue for the filtering.
