### ISSUE TITLE
Reporter does not honor default values defined in a subtype

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#183]
Initial summary, more details coming:
If the default value is set at the field level, meaning right-click on the layer in ArcMap > fields tab > set a default value, then the default value does appear in the Crowdsource Reporter application and is working as expected. However, if the default value is set within the Subtype, the default value is not added when a new point is created.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to reproduce the issue. Can you please share webmap on which we can reproduce the issue?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
More details as promised: This is actually not a subtype issue, it is another case of users being confused about when it's ok to use a unique value renderer and when it's not. Can we talk about options for better handling of default values when a layer has multiple feature templates during our status call this week?

**Comment by CTLocalGovTeam** [comment]
Yes. We can discuss approach for better handling of default values on status call.

**Comment by allisonmuise** [comment]
closing - can't improve handling of default values with current json structure. Can't tell which field the templates are based on
