### ISSUE TITLE
Shadows for home and zoom out buttons go over adjacent icons

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-reporter#186]
Each shadow is offset by 1 pixel to the right and down, but has a blur extending outwards from the shadow for 10 pixels, which easily extends up into the next icon above for the home and zoom out buttons.

![image](https://cloud.githubusercontent.com/assets/2125181/14680268/9022e30e-06d1-11e6-87d8-2e6ebbee36b7.png)

**Comment by allisonmuise** [comment]
verified
