### ISSUE TITLE
Out-of-the-box geolocation fails due to missing basemap layers

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-reporter#187]
The ‘develop’ branch of map-and-app-gallery-template fails when one tries geolocation in Firefox because the handler for the returned location is not able to find a layer named “defaultBasemap” or “defaultBasemap0”.  (Tested in Firefox 45, the latest version.)

**Comment by allisonmuise** [comment]
@MikeTschudi Is this in the right repo?

**Comment by MikeTschudi** [comment]
No, and I can't reproduce it, either.  Thanks for the catch.
