### ISSUE TITLE
clear selection when returning to issue list

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#192]
Repro steps:
Select report from list to view details. Note that feature is highlighted in map
Click the < arrow to return to the list of reports. Note that feature is still highlighted in map

Selection highlighting should clear on return to the report list.

**Comment by allisonmuise** [comment]
related to #182 ?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This functionality is as per design.

When user returns to issue list, we highlight the selected feature(issue) in the issue list with theme color vertical bar. This way user can easily see the selected issue in the list.

This feature is particularly useful when user is going through issues one by one.

If we clear map selection on returning to issue list, we have to remove the functionality of highlighting the row in issue list.

Please let us know if we should retain or remove this feature.

![image](https://cloud.githubusercontent.com/assets/2959186/16410252/3e18f126-3d3f-11e6-8aaa-fe8f5786436b.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This makes sense. Let's leave it for now unless @ScottOppmann feels otherwise.

Can we at least clear the selection when returning to the map list?

**Comment by ScottOppmann** [comment]
I am fine with the logic @CTLocalGovTeam suggests.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We will clear the selection when returning to map list.

**Comment by allisonmuise** [comment]
verified
