### ISSUE TITLE
Separate 'help' text available on splash screen from 'help' available in-app

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#193]
would allow for more legal-style disclaimer text on splash screen and more functional help in-app.
(Marshfield, USFS)

**Comment by allisonmuise** [comment]
Important consideration here is backwards compatibility.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is our understanding regarding the functionality :  
* We need to show different content on help dialog and splash screen dialog configured in the config file. On load, splash screen will be shown and help dialog functionality will remain unchanged.

* This splash screen will be displayed using the same window used to display the help dialog. The splash screen will be displayed after user go past the login screen (either as guest/authenticated user).

Here is our approach to implement the functionality : 
* Currently, we have two configurable parameters "**helpDialogTitle**" and "**helpDialogContent**" to fetch the content for help. Similarly, we will add two more parameters "**splashDialogTitle**" and "**splashDialogContent**" to fetch the splash screen content.

* To support backward compatibility, we are thinking of  keeping the "**splashDialogTitle**" and "**splashDialogContent**" values to blank by default. This will ensure that the previously configured application will not show splash screen on long as the "**splashDialogTitle**" or "**splashDialogContent**" value is blank.

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : To clarify - The 'splash screen' referenced above is the page with the sign in options, not the splash page referenced in #221 . Previously we referred to the screen with the sign in options as a splash page but to avoid confusion with the new splash screen, I will refer to the page with the sign in options as the sign in page. 

My apologies for not recognizing this confusing terminology when reviewing these issues.

The help panels we'd like to separate are:
1. the one that can be accessed from the sign in page by clicking the link below the sign in options
2. the one that can be accessed when clicking the question mark found in the upper right corner of the application once past the sign in page.

#221 will cause the help page accessible from the question mark to display immediately after passing the sign in page.

For the configuration panel: 
There are already parameters for enabling the help, setting the title/tooltip of the panel, and setting the content displayed in the panel. To these, let's add:

- another checkbox parameter that says something like 'Display different content on sign in page'. By default this should be unchecked.

- another title and content parameters as you describe above (perhaps avoid 'splash' to prevent similar confusion for users). 

When the checkbox is checked, use the values of these new dialog and title parameters in the panel that is accessible from the splash page. When the box is unchecked, use the same content in both. This should avoid backwards compatibility issues.

Does this help clarify what is wanted? We can schedule a conversation if that would help, too.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Thanks for the detailed description. We are pretty much clear on what is expected.

**Comment by allisonmuise** [comment]
verified
