### ISSUE TITLE
Enhancement - Advanced Editing Capabilities

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/crowdsource-reporter#195]
Add the ability to leverage feature service edit capabilities so users can edit existing features if desired.   Users should be able to:
- [ ] Update attributes
- [ ] Delete features

Review whether feature service capabilities provides enough granularity or if additional application configuration would be necessary.

FYI - @lindsayking

**Comment by lindsayking** [comment]
According to @allisonmuise , these capabilities will need to be disabled by default for backwards compatibility so they will need to be configurable.

**Comment by allisonmuise** [comment]
@lindsayking : I believe we will also need changes to service capabilities to support this. Configurations will simply be to use or ignore those capabilities if they exist

**Comment by allisonmuise** [comment]
@ScottOppmann Thinking on this further:

We could, perhaps, get around some service limitations by managing this at the app level and doing this for authenticated users (Social media or AGOL). We could add 'edit' and 'delete' buttons to reports with a stored user id that matches the current user. Reports submitted anonymously would not be editalbe/deletable. Each of these capabilities would need to be configurable.

I'm not sure where we would put these buttons, and we would need to take into considerations some security issues such as how easy is it to fake the ID of the current user in order to modify reports submitted by others?

**Comment by allisonmuise** [comment]
@ScottOppmann @lindsayking @NikkiGolding : Can this wait for the update to the 4.x API, or should this go for the November release?

**Comment by NikkiGolding** [comment]
@allisonmuise We'd like this in November. What is driving the need to push the date?

**Comment by allisonmuise** [comment]
@NikkiGolding no driving need, just trying to be conscious of only doing work twice when it's necessary. 

We are going to have to move the app to the 4.x API next year which will mean re-writing the app from the ground up. Any changes we make now will have to be done twice - once to make the change now, and then again to include the change in the re-write.

For that reason I'm trying to push new functionality that requires major dev work but is a 'nice-to-have' rather than a 'need' to that major overhaul so that we only need to do it once.

If you need this for November I'll leave it in for 4.4.

**Comment by NikkiGolding** [comment]
@allisonmuise  Please leave for 4.4

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Just to confirm our understanding,   

1. Only logged in users will be able to edit reports and comments
2. Attachments are not editable
3. User can edit/delete only the reports and comments that they have reported
4. Users cannot edit/delete reports and comments submitted by the other users
4. Anonymous reports and comments cannot be edited/deleted
5. If user reports an issue using google login, then it can only be edited/deleted using the same google login
6. Feature Services must have these capabilities; 
    * *Create, Query, Update, Editing* - Only Edit button enabled
    * *Create, Query, Update, Editing, Delete* - Edit and Delete enabled
    * *Create, Query, Editing* - Edit and Delete disabled
7. Add configuration options
    * Enable editing - defaults to false
    * Enable delete - defaults to false

**Comment by ScottOppmann** [comment]
@allisonmuise - please make sure we review the @lindsayking and @NikkiGolding to ensure their requirements are met and they are comfortable with @CTLocalGovTeam assumptions.  Tx

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
With regards to #2 as listed above - Is is possible to allow users to remove/add attachments?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can remove/add attachments for features as well as comments.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Please have a look at these mockups and let us know if these are ok.

Feature Editing:

![image](https://cloud.githubusercontent.com/assets/2959186/18003530/c1fe0d42-6bab-11e6-9934-8f9eb0eaa5bb.png)

----

Comment Editing:

![image](https://cloud.githubusercontent.com/assets/2959186/18003545/ddff3408-6bab-11e6-9cc0-d897e6182d12.png)

**Comment by allisonmuise** [comment]
@ScottOppmann @lindsayking @NikkiGolding

**Comment by lindsayking** [comment]
@allisonmuise   These look good to me.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Clicking 'Update' is just scrolling me back to the top of the form. No success message, no error message....nothing.If the update can't be committed for some reason, I would expect some sort of message consistent with what we have for the main geoform. If the update is successful, the app should exit Update mode and return to the details view of the report.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam On click of the trash can, please prompt users to confirm that the report will be deleted. Only delete the report on confirmation.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : If this will involve string changes, please note that string freeze is Nov 8th @ close of business in Redlands. The fix doesn't need to be in and tested, but I must have any strings by then.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We can either display two separate messages for delete confirmation:
```javascript
 geoform : 
    {
      deleteReportMessage : "Do you want to delete report?", \\shown when user tries to delete a report
      deleteCommentMessage : "Do you want to delete comment?" \\shown when user tries to delete a comment
    }
```

Or display one message for both actions, in that case, the nls string to be added will be:
```javascript
 geoform : 
    {
      deleteMessage : "Are you sure you want to delete?", \\shown when user tries to delete a report or comment
    }
```

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Let's go with the second option.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

>@CTLocalGovTeam 
>Clicking 'Update' is just scrolling me back to the top of the form. No success message, no error message....nothing. (EDITED TO ADD: I am seeing this with the main geoform occasionally, too)

>If the update can't be committed for some reason, I would expect some sort of message consistent with what we have for the main geoform. If the update is successful, the app should exit Update mode and return to the details view of the report.

The feature/comment editing functionality is designed as described above. You can see the editing functionality in the demo link [here](http://203.199.47.146/csreporter/demo/?group=9b89e36717f241769e9db67873bf1339)

Steps : 
1. Login with valid credentials
2. Select "**Media, Comment and Pop-up Test**" webmap
3. Select "**CSR_Geo_Filtering_Test_Layer - TestPoints**" layer
4. Submit new feature
5. Now try editing or deleting feature and comment **(Comment table has filter on field "SHORT_INT = 3")**

Please have a look at it and let us know your feedback. Also, we would request you to share the application link and data if you are seeing some issues at your end.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Editing comments and reports now seems to be committing changes appropriately.

When opening the editing form for comments, though, previously selected domain values don't seem to 'stick'. Domain values always need to be set again before saving the edits.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Can you reproduce this issue with domain values?

**Comment by allisonmuise** [comment]
verified

**Comment by allisonmuise** [comment]
@apena12 This text will display whenever editor tracking is enabled on the layer.
