### ISSUE TITLE
Enhancement - Limit Geographic Extent of Feature Edits

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/crowdsource-reporter#197]
Limit the geographic extent where new features can be created.  Could use:
- [ ] Configurable item in application to set
- [ ] Initial or full extent of map

**Comment by allisonmuise** [comment]
@ScottOppmann 
Suggestion:
Configurable option to define (a) layer name(s) in the maps that represent the boundary for reports. This layer name would have to work like the common field names for voting, etc. Reports submitted outside this area would be met with a configurable message.

This would be quite a change in the app, I think. Do we want to do this for 4.4, or should we hold off until the new API is ready?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Assuming initial extent is the default extent of the webmap, this cannot be used because app zooms to user's current location and will be different for each user. Webmaps do not have a full extent property. 
The Reporter App is a gallery app, so we would be configuring a group of webmaps. If we try to restrict based on full extent of a layer, then user will have to select the webmap first and then the layer from that webmap. The selected layer will apply the restriction to all other webmaps/layers in the app. The layer must also be present in each webmap for this to take effect. Also, the layer name will have to be the same across all webmaps as their internal ids in each webmap will be different.

Please let us know your thoughts.

**Comment by ScottOppmann** [comment]
@allisonmuise @CTLocalGovTeam - Could we use the geographic extent of the ArcGIS Organization the application lives within?

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann @allisonmuise 
The Organization does have a default extent property and it can be used to limit feature creation outside this extent. 
An alternative option is to provide a single textbox in the configuration, where user enters the layer name manually, like the ones we provide for common field names for Voting, Userid etc. The layername will then be used app-wide to limit feature creation outside the full extent of that layer. We think that's what Allison originally intended when she was describing her suggestion. Is this correct? This is doable.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : your understanding of my description is correct. 

@ScottOppmann : what do you think of this idea?

**Comment by ScottOppmann** [comment]
Interesting idea, users could then have essentially an extent feature in each webmap.  If they disabled editing on the layer, it would not show up in Reporter app, correct?  If not, then I do think this is the most flexible approach.  Allows users to identify a specific extent for each report type.

**Comment by allisonmuise** [comment]
@ScottOppmann 

Uneditable features can display or not based on the app configuration. Regardless, setting the symbology to nothing would make the layer not be visible in the app, even if other reference (uneditable) layers were being displayed.

**Comment by ScottOppmann** [comment]
Ok, but that could get confusing.  Use parks as an example.  A map may have parks in it (to support find by location), trails (for context when feedback offered), and the extent allowed for edits.  If the user clicks on the map, which layers would be shown?

**Comment by allisonmuise** [comment]
@ScottOppmann you can only interact with the editable layers. The others are there only as reference.

**Comment by ScottOppmann** [comment]
Understood, but would the non-editable layers show up in the layer list when you click on a map in the TOC?

**Comment by allisonmuise** [comment]
No, only editable layers show in the list, even when the non-editable layers display in the map.

**Comment by ScottOppmann** [comment]
Ok, then your idea (using a non-editable extent layer) would work nicely.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
When do we display a message to the user if he tries to report outside his allowable area?
a) when user adds a location in main map or geoform map, or
b) when user submits the report

**Comment by allisonmuise** [comment]
please display a configurable message when the user completes their drawing in either map if no part of the drawing intersects the allowable area.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @ScottOppmann 
We think the configured extent layer should always be non-editable. If its editable, then it will probably restrict adding any new features within its own full extent! So, should we honor geo-restriction only by non-editable layers?

**Comment by allisonmuise** [comment]
Yes. Un-editable being any of the following:

- Server Map Services, tiled layers, and other service types that are inherently un-editable
- Feature layers/services without Add capabilities
- Feature layers/services without an editable field defined in the popup
- Feature layers/services with editing disabled on the layer in the map Contents

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I can submit features everywhere, without running into restrictions. I'm wondering if there's a misunderstanding over what's expected.

Could you clarify how I should define the Geographical extent layer? Layer name, REST endpoint, etc?

I am expecting that I can trigger the out-of-bounds message by dropping a new report outside the features in the specified layer. Inside the polygon(s) = good, outside the polygon(s) = bad. Is this how it is implemented? 

Are there any checks in place to make sure that the specified layer contains polygon geometry? I can't submit features inside lines or points so would be nice to have some check there, although this isn't critical for this release.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This functionality will work with all layer types. You need to configure the "Layer name" in configuration and layer should be non-editable.

Here is the configuration parameter:
`    "geographicalExtentLayer": "Highways_Extent_Layer"`

Can you please share the application link. This will help us to identify the issue.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : OK - I have the app telling me that the reports are outside the reporting area, but it's telling me that regardless of where I try to create a report. I will send a URL via email.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are able to reproduce the issue with the URL send via email.

The application was not allowing you to add new report because of difference in spatial reference of geographical extent layer and drawn feature while comparing if features lies in layers extent.

To resolve this we will be using following approach:
We will get the full extent of the layer, and project the extent in map's spatial reference and will use this for  comparison. This will make sure the layer's extent and drawn feature are always in same spatial reference.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I can still create reports outside the features in the specified layer. Let's discuss on the call tonight.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

In the current implementation the application is considering the layers full-extent as the boundary in which the user can report the issue. 

As per our discussion in the today's call we will be updating this enhancement with following approach:

1. Only polygon layers are applicable to limit the geographic extent for reporting.
2. Once user draws the feature on map, the app will query the configured geoLimitLayer to check if at least one polygon of the configured layer is intersecting with the drawn feature(Drawn feature could be point/line/polygon) else it will display an appropriate message and removes the drawn feature.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, this sounds good.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

While implementing the new approach to limit geographical extent, only polygon feature layers coming from following sources will be supported :
1. Feature Services url added to webmap 
2. ArcGIS map service layer url added to webmap with layer id
3. Tile map service layer url added to webmap with layer id (query-enabled)

When a mapservice is added to webmap without a layer-id, all its sub-layers are added to the webmap. The sub-layer names are uneditable in the webmap. Mapservices added in this way cannot be used for geo-restriction. The same applies to tiled map services. To be considered for geo-restriction, they must be added as a feature layer.

Please let us know if this sounds ok.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Why the requirement to be added to the map via URL? We must support feature collections and hosted feature layers as well.

Support for tiled services is not necessary.

Support for map services added one layer at a time, but not when added as a group is acceptable.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

To implement the new approach we need to query the extent layer, but Feature layers  created from ['Feature Collection'](https://developers.arcgis.com/javascript/3/jsapi/featurelayer.html#featurelayer2) doesn't  support query. So we will not able to support Feature Collection layers as extent layer.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : OK

**Comment by allisonmuise** [comment]
verified
