### ISSUE TITLE
Location information should be stored even when field is not displayed

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#198]
This is in regards to enhancement #162. Currently this works well if you make the location field in the pop-up editable. However this is not the best experience because as you go down the form you come to the location field which gives the impression you need to populate it. Then when you get to the bottom your search for an address or click in the map and it may change what you typed above.

Instead I would like to make the location field not visible in the form (not editable in the popup), but still have it write the location information to the field when the feature is created.

FYI @ScottOppmann

**Comment by allisonmuise** [comment]
@chris-fox : 
The location is only being written when the field is editable? When the field is not editable, no value is being written?
I'm confirming because this was working in a previous code drop.

**Comment by chris-fox** [comment]
@allisonmuise Yes, that is what I am finding. All I changed in the webmap was if the location field was editable.

**Comment by allisonmuise** [comment]
ok

**Comment by allisonmuise** [comment]
closign this issue. #162 has been reopened.
