### ISSUE TITLE
Date/Time format is incorrect in the geoform when using MM/DD/YYYY or DD/MM/YYYY formats when showing time

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#199]
Repro steps:

- Configure the popup for a date field using the format MM/DD/YYYY or 12/21/1997
- Check the option to show time (Not repro without this option)
- Create a new report and the date is shown as DD/MM/YYYY or 21/12/1997 (time displayed correctly) in the geoform

The date displays correctly in the item details.
I reproduced this using the dev branch today as well.

**Comment by allisonmuise** [comment]
@chris-fox was this using the development version of Reporter, or the production version? If it was the development version, can you repro on production?

**Comment by chris-fox** [comment]
I repro'd it on both.

**Comment by allisonmuise** [comment]
verified
