### ISSUE TITLE
Empty box is added below the search button in Firefox

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-reporter#200]
@allisonmuise 

In Firefox, when we click on already selected layer an empty box is added below the search button in map navigation panel.

Steps to reproduce:
•	Launch the application and proceed as guest with geolocation enable
•	Select a layer from web map containing multiple layers
•	Navigate to geo form
•	Come back to web map list
•	Again click on the selected layer

![image](https://cloud.githubusercontent.com/assets/2959186/15392267/9bd068c4-1de3-11e6-8fb2-7a0fd447859a.png)

**Comment by skrishn** [comment]
@allisonmuise:  Yes, same issue. I noticed in Chrome, FF and IE11

**Comment by allisonmuise** [comment]
verified
