### ISSUE TITLE
Feature is not drawn on the location where mouse is clicked when location is entered

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#202]
1. Open a reporter application with line/polygon features
2. Click on a layer - click submit report
3. Fill out the geoform
4. In the Location box: Enter an address or Lat/Long or USNG or MGRS (depends on the configuration setting)
5. Choose a suggestion from suggestion drop-down (do not clear the address by clicking x button)
6. Draw a feature in geo form map - notice the feature is not being drawn where the mouse is clicked. If you can't see the feature scroll down the page to see it

Note: The issue is not reproducible if you clear the address or if you pan the geo-form map.

**Comment by allisonmuise** [comment]
@skrishn can you verify that this is fixed on devext?

**Comment by skrishn** [comment]
@allisonmuise verified
