### ISSUE TITLE
base cach from arcgis online web map

### ISSUE THREAD

**Issue by zhujingx** [Esri/crowdsource-reporter#203]
I have web map with the bash cached map service  at ArcGIS online. When I use this web map in the sample ,it asked me the user name and password for the map service. I put the credencials in the ArcGIS online already, why this sample still ask me  again. It would be great if  If you could get rid off this step.

Thanks
Zhujing

**Comment by allisonmuise** [comment]
@zhujingx: The application will require you to enter credentials if:
1) The editable layer is not shared with Everyone *or* the layer does not have stored credentials
2) The map is not is not shared with Everyone
3) The application is not shared with Everyone
4) The hosting organization does not allow publicly sharing content or does not allow anonymous access to content

To access content that is not publicly accessible (bound by one of the restrictions listed above) you must use the ArcGIS sign-in option.

**Comment by zhujingx** [comment]
Alison,
Thank you for the quick response.
I understand it will ask me the credential for the arcgis online, but after that it asked the credential for the map service which I already put the map service into arcgis online as image layer and add the user info in arcgis online. That is strange.

Zhujing

**Comment by allisonmuise** [comment]
@zhuijingx:

Hmm...I haven't run into that before, and it definitely should work. Could you contact Esri Support Services with this? I'm actually out of the office this week, so they'll be able to help you more than I can from my phone! Once they've got all the details and a repro case they'll send it to me to fix.

Thanks
-Allison

**Comment by zhujingx** [comment]
I have case with ESRI support 01786960.

But the analyst can not figure it out. She suggest me to post the issue on github.

Zhujing

**Comment by zhujingx** [comment]
Sorry, this is the case number 01785639

**Comment by zhujingx** [comment]
Alsion,

I also saw this manger application, it share the same data as the reporter, but this one could edit the all the data on the map. The reporter only could add new point.
http://solutions.arcgis.com/local-government/help/crowdsource-manager/

Would this be controlled by the code of the application, or by the feature layer in arcgis online?

Thanks
Zhujng

**Comment by allisonmuise** [comment]
Crowdsource Manager is designed to be a review and triage application to help assess reports submitted through other apps such as Reporter. If you think of them as two parts of a single workflow - Reporter is for submitting reports (creating features) and Manager is for reviewing them (attribute updates on existing features). The underlying service may (and should) have both add and update capabilities, but the applications only expose what is necessary for their part of the workflow.

**Comment by zhujingx** [comment]
OK thanks. So the code in different application wrote differently,  what did you use in the code? Did you use the edit widget from Javascript API or individual Add or Edit in the code?
Thanks
Zhujing

**Comment by allisonmuise** [comment]
I am not a JS developper, but I spoke with one of our devs about this. The apps do not appear to be using the Edit widget. For Reporter - features are drawn into a graphics layer using esri/toolbars/draw, attributed from the form, and then committed to the feature layer.

**Comment by zhujingx** [comment]
Do you know what method used for editing the attribute info in the manager? I can not find edit widget in the code neither.

**Comment by allisonmuise** [comment]
@zhujingx : No, Manager doesn't use the Edit widget, either. Feature attributes can only be updated through Manager.

**Comment by allisonmuise** [comment]
@zhujingx : I'm going to close this issue. If you have a specific enhancement you'd like to request, please open a new issue.
