### ISSUE TITLE
Main map doesn't respect scale dependancies

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#204]
@CTLocalGovTeam :
The main map doesn't seem to respect scale dependencies (features that only draw at specific zoom levels), but the map in the geoform does. Is this something that can be fixed in a future release (not for 4.2), or is it a by-product of using a graphics layer?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Are you experiencing this with the editable layer or with all non editable layers. 
If its the editable layer, then yes its by product of using graphics layer. We can inherit the scale dependency to the graphic layer however need to analyze its impact. 
For e.g., If the layer is not visible do we still show the list of issues?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : A user reported this with the editable layers. Thanks, we'll look at options to address this for a future release. As you mention, we'll need to be thoughtful about the overall workflow of the app.

**Comment by allisonmuise** [comment]
duplicate #207
