### ISSUE TITLE
BUG-000097007 When adding a Map Image Layer in ArcGIS Online from a secured ArcGIS Server service with credentials saved and add it to a webmap, the layer does not load in the in the Crowdsource Reporter and Crowdsource Manager application.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#206]
<div><div>User is working with Crowdsource Reporter app downloadable from <a href="https://github.com/Esri/crowdsource-reporter" target="_blank">GitHub </a>but the issue is reproducible in ArcGIS Online web app version as well.
<ol><li>Create a <b>Map Image Layer</b> in ArcGIS Online as follows:
	<ul><li>Go to <b>My Content </b>page in ArcGIS Online and select <b>Add Item </b>option.</li><li>Provide secure <a href="http://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure_ac2/MapServer" target="_blank">ArcGIS Server service URL</a> and store credentials (username = user1 and password = user1).</li><li>It will generate an item of type <b>Map Image Layer</b> in ArcGIS Online and will generate a new URL. Share this item to a group, lets say &quot;My Group&quot;.</li></ul>
	</li><li>Create a map with the item created in step 1 and add an <a href="http://sampleserver6.arcgisonline.com/arcgis/rest/services/SF311/FeatureServer/0" target="_blank">editable feature layer</a> to the map. Save the webmap and share it to the same group - &quot;My Group&quot;.</li><li>Go to <b>Groups </b>&gt; &quot;<i>My Group</i>&quot; &gt; <b>Share </b>&gt; <b>Create a Web App </b>&gt; Select <i>Crowdsource Manager </i>template. Similarly, create another application using <i>Crowdsource Reporter </i>template.</li><li>The webmap created in step 2 will be consumed in the Crowdsource Manager application and Crowdsource Reporter application. Notice the &quot;Map Image Layer&quot; will not display on the map.</li></ol>
<b>NOTE:</b>

<ul><li>The issue is not reproducible with Basic Viewer application and Finder application.</li><li>Tried testing the webmap in a simple JavaScript <a href="https://developers.arcgis.com/javascript/3/jssamples/ags_createwebmapid.html" target="_blank">sample</a> as well. It will ask to sign in to ArcGIS Online account as the webmap is shared to a group only. Providing the valid credentials, the webmap will display both layers including Map Image Layer. Hence, the issue is not reproducible with simple JavaScript application.</li></ul></div><div>
<span><b>Salesforce ID:</b> BUG-000097007</span><br/>
<span><b>Salesforce Submitter:</b> Garima Dhakal</span><br/>
<span><b>Salesforce Submit Date:</b> 6/08/2016 1:50 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 4.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
arcgis-portal-app-templates #1210

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to reproduce the issue. Can you please confirm if `showNonEditableLayers` flag is set to true in configuration?

**Comment by allisonmuise** [comment]
I can reproduce in this application: http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=a1fdf7c56ab94113adc49c75802f5e7a

The showNonEditableLayers flag is set to true. Note that the MIL features draw in the map in the submission form, but not in the main map. They also draw in Manager.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Thanks for sharing the application link. We will investigate this issue and keep you updated.

-Ashish

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We are able to reproduce the issue and we will provide a fix for this in upcoming code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam This is still not working for me. I will send a link via email.

**Comment by allisonmuise** [comment]
verified
