### ISSUE TITLE
BUG-000096844 The Crowdsource Reporter does not reflect the visibility range set from a web map.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#207]
<div><div><ol><li>Open a map viewer and add a feature layer. <a href="http://ess.maps.arcgis.com/home/item.html?id=3beff7e5ebe74246afb347efd04af655" target="_blank">http://ess.maps.arcgis.com/home/item.html?id=3beff7e5ebe74246afb347efd04af655</a> </li><li>Click more Options, and click the Set Visibility Range. Adjust the range.</li><li>Save the map.</li><li>Click Share and share it with group.</li><li>Go to group page and click SHARE.</li><li>Click <b>Create A Web App.</b></li><li><span>Select </span><b>Crowdsource Reporter</b><span>, and click </span><b>Create App. </b><a href="http://ess.maps.arcgis.com/home/item.html?id=83326c8d2d614248bbf1ee72f10ae409" target="_blank">http://ess.maps.arcgis.com/home/item.html?id=83326c8d2d614248bbf1ee72f10ae409​</a> </li><li>Click Save in the Configure Web App page.</li><li>Click View.</li><li>Zoom in on the map. The layer should be invisible as you zoom in, but it appears.</li><li>Click Submit Report. Notice that the visibility range is properly applied to the map in the right panel.</li></ol>
<br>*Attached is the document regarding the behaviour.</div><div>
<span><b>Salesforce ID:</b> BUG-000096844</span><br/>
<span><b>Salesforce Submitter:</b> Siti Rohana Tazura Ali</span><br/>
<span><b>Salesforce Submit Date:</b> 6/01/2016 9:56 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000096844</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> N/A</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
arcgis-portal-app-templates #1205

**Comment by allisonmuise** [comment]
@ScottOppmann @MikeMillerGIS @NikkiGolding @LindsayThomas 

The more I think about this issue, the more I feel that this would best be handled by documenting that scale dependencies are not honored for the editable layers. I don't see how honoring scale dependencies would add to the UX because the map extents are not used when determining which features to load.

1) Users set the loading zoom level of the map when they save the map, so having the app open to a global scale when features are only local is bad configuration. At least if the features load, users can click one of the items in the list and be zoomed to the feature. If scale dependencies are honored, the list will be empty and there's no way for users to know where the features are of if there are any.

2) When users share their location with the browser, the app only loads those features closest to them. The existence of those features doesn't (and shouldn't) depend on the zoom level of the map.

Thoughts?

3) When users don't share their location with the map, the app loads all features (up to the max allowed by the server) anyway. Again, the existence of these features doesn't/shouldn't depend on the zoom level of the map.

**Comment by allisonmuise** [comment]
@ScottOppmann Do we want to address this through doc or by changing the app?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @ScottOppmann 

The app already supports scale dependencies. The graphics layer honors the min and max scale. The issue list displayed in panel remains as is and is not affected by scale dependency.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Was this a change you made for 4.3? I see scale dependencies honored on devext, but they are not on production.

**Comment by allisonmuise** [comment]
verified
