### ISSUE TITLE
Configurable option for showing map first, instead of list

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#211]
In smartphone view, the list loads first and users can toggle to the map. Provide a configuration option so that the app can be set up to show the map first on phones.

**Comment by allisonmuise** [comment]
https://geonet.esri.com/message/536826

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : The 'list' button that displays in map view should return to the list of reports, not the list of maps. Otherwise, this functionality is looking good

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The behavior of 'list' button is as per design. In the current implementation, the 'list' button always navigates user to web-map list. If user clicks's on back button he will be navigated to list of reports. Even if we do this, both back and list buttons will take user to web-map list and there will be noway to go to list of reports.

**Comment by allisonmuise** [comment]
@CT hmmm...ok. we made need to rethink this. This behavior isn't logical when the map loads first. I'll look in to this and get back to you.

**Comment by allisonmuise** [comment]
I have opened a issue #273  for modifying the behavior of the 'List' button. I will close this one as the original issue has been resolved.
