### ISSUE TITLE
Limit ability to re-vote for a report

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#212]
Currently, when the Vote button is clicked the button changes colors but users can click the button again to re-vote.

Ideally, users would only be able to vote once, but I don't want to introduce the complexities of managing cookies so here is my proposal (follows changes we are making in Crowdsource Polling):

- When the Vote button is clicked, disable the button to prevent users from immediately re-voting. 
- Maintain a list of features that have been voted on for as long as possible without using cookies - until app close if possible.

@CTLocalGovTeam : I've put this in the 4.3 milestone, but if it's a significant development effort please let me know and I'll move it to the 4.4 milestone.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This change is low LoE and we can include this in upcoming code drop.

**Comment by allisonmuise** [comment]
verified
