### ISSUE TITLE
CSS issues in RtL

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#215]
The item details panel isn't drawing correctly in RtL languages such as arabic:
note the end of the tan area relative to the horizontal line and the placement of the Gallery button
![8-11-2016 9-41-46 am](https://cloud.githubusercontent.com/assets/2752195/17596794/e7669460-5fa7-11e6-95d8-f40f9339e73c.png)

**Comment by skrishn** [comment]
@allisonmuise verified
