### ISSUE TITLE
favicon i salways esri logo

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#217]
browser tab displays esri logo, even when a different favicon is specified in the app configuration.
@CTLocalGovTeam  can this be addressed for 4.3?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are analyzing the issue and we will keep you updated on this.

-Ashish

**Comment by skrishn** [comment]
@allisonmuise Verified
