### ISSUE TITLE
Only zoom to user location when user is inside study area

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#220]
When a restricted geographic area is defined ( #197 ) and a user shares their location with their device, only zoom to user location when they are inside that geographic area.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Can you please confirm our understanding of this feature is in line with the vision you have in mind.

![image](https://cloud.githubusercontent.com/assets/2959186/18001927/d827c648-6ba2-11e6-997f-5ea5f9274155.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam :yes, those look correct.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I have a reporter app configured to use a reference layer. my location is well outside the boundaries of all polygons in that layer. When I share my location with the application, the map opens to my location, not the default extents.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

As per our discussion in the today's call we will be updating this enhancement with following approach:

On app load if user allows to geo-locate , the app will query the configured geoLimitLayer to check if at least one polygon of the configured layer is intersecting with the user's current location. If yes user will be navigated to current location else app will be navigated to webmap's default extent.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Yes, this sounds good.

**Comment by allisonmuise** [comment]
verified!
