### ISSUE TITLE
Make order of form components configurable

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#222]
Currently form is in Details>Attachments>Location order. Allow these to be re-organized as part of the application configuration process

**Comment by allisonmuise** [comment]
I'm open to suggestions on how this could work in the configuration panel.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

We can add configuration options to control the order of form components. 
We are planning to create three dropdowns with "Details", "Attachments" and "Location" as options(see screenshot).
 
![option](https://cloud.githubusercontent.com/assets/2959186/20835394/5fb2df02-b8c0-11e6-9120-c90f87185142.png)

There is a possibility that user can select the same option in more than one dropdown. In that case, the default order will be shown in the app.

We assume the “Location” option includes both the searchbox as well as the map, correct?

Please let us know if this is ok

**Comment by allisonmuise** [comment]
Let's go the other way with these boxes: instead of picking the title that goes with each location, let's have them pick the location that will go with each title. The labels would be Details, Attachments, Location, and the dropdown options would be Top, Middle, Bottom.

This way, users can't leave off one of the sections. The worst they can do is assign two titles to the same location, in which case, build the form with the sections assigned to the same location in the order Details, Attachments, Location.

For example:

Details - Bottom
Attachments - Bottom
Location - Middle

would result in elements in this order: Location, Details, Attachments

Or:
Details - Middle
Attachments - Top
Location - Top

would result in elements in this order: Attachments, Location, Details

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Fixed and will be available in next code drop.

**Comment by allisonmuise** [comment]
verified
