### ISSUE TITLE
Hide map on form in Desktop mode

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#224]
When working with the app in desktop or tablet-landscape mode, two maps are visible when completing the form. Would make more sense to direct users to draw on the large map rather than providing the smaller form map.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We have implemented this and it will be available in tomorrow's code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam My apologies - I wasn't very clear.

Can we leave the 'Location' text, the instructions to draw the location on the map, and the search box as part of the form? I just meant to remove to map itself from the form.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We need to analyze the feasibility of this change. However, to implement this we need to add following strings.
1. Desktop, point layer: 'Click the map to draw the location.'
2. Desktop, line or polygon layer: 'Click the map to draw the location. Double click to complete the drawing.'

Please let us know if you would like us to add this strings before string freeze. We can include this string changes upcoming code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, please add these strings for the next drop, then update the code later.

**Comment by allisonmuise** [comment]
verified
