### ISSUE TITLE
Provide drawing hint on desktop devices

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#225]
Provide 'click to draw' tooltip instructions and 'double-click to complete drawing' instructions. Could be either as tooltip, or perhaps part of form?

**Comment by allisonmuise** [comment]
I mentioned the cursor tip in the call this morning, but on revisiting the issue I think that text in the form would be better as it would work on mobile devices as well. 

Could this text be context-dependant? I'm thinking the following scenarios

1) Desktop, point layer: 'Click the map to draw the location.'
2) Desktop, line or polygon layer: 'Click the map to draw the location. Double click to complete the drawing.'
3) Phone/Tablet, point layer: 'Tap the map to draw the location.'
4) Phone/Tablet, line or polygon layer: 'Tap the map to draw the location. Double tap to complete the drawing.'

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can easily add context dependent text in the form. Here are some of the options to add hint text in the form. 

![image](https://cloud.githubusercontent.com/assets/2959186/20974979/f7435a8e-bcc3-11e6-9060-84154af3db01.png)

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Let's go with option 2

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

We have implemented this and it will be available in tomorrow's code drop.

**Comment by allisonmuise** [comment]
verified
