### ISSUE TITLE
add basemap widget

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#226]
when collecting feedback in remote areas, a combination of aerial imagery and topo maps may be required to find the correct location. Currently the app only supports one basemap.

**Comment by allisonmuise** [comment]
The UI for this might shift slightly over the course of development, but the functionality will remain the same, so please start there, and we can tweak the UI after I return.

Desktop mode:
I suggest starting with the button graphic from Basic Viewer. This button could sit in line with the navigation widgets on the left side of the screen. Clicking the widget would expand a panel (like the search does) containing the basemap options. This panel should be styled to fit in with Reporter. Do not use the same styling from Basic Viewer.

Smartphone mode:
Let's try adding the item 'Basemaps' to the burger menu list in between Sign In and Help. Clicking this should open a popover window (like the help) with the basemap options

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is the screenshot of base map gallery widget in desktop and mobile mode.

![image](https://user-images.githubusercontent.com/2959186/30740698-a5ddf36e-9faf-11e7-8134-7d1d271c3cfd.png)

Please confirm if this looks good.

**Comment by gigaranger** [comment]
Hello Allison,

I like it and will it be configurable for the basemap groups to allow own basemaps in the widget?

Thanks,

Kenny

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I like the UI. The window fits well with the rest of the app. 

Will the access point for the gallery be the same on desktop and mobile, or is it under the burger? 
Can the basemap group be configurable at the app level?
After choosing a basemap, does the window close automatically, or does the X need to be clicked after selection?
Is the currently selected basemap indicated in any way?

cc @ScottOppmann

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Please see our response inline.

Will the access point for the gallery be the same on desktop and mobile, or is it under the burger?
>> We are planning to keep the access points same for mobile and desktop. This way user will always see basemap button irrespective of mobile/desktop mode.

Can the basemap group be configurable at the app level?
>> Yes. We will add a new configuration parameter for selecting basemap group. By default this will be empty. When no group is configured, app will fetch org's basemap group. 

After choosing a basemap, does the window close automatically, or does the X need to be clicked after selection?
>> Once a basemap is selected the window will be closed automatically.
 
Is the currently selected basemap indicated in any way?
>> The basemap gallery widget takes care of it and shows a border for selected basemap.
![image](https://user-images.githubusercontent.com/2959186/30808388-8ab24f0e-a21b-11e7-9ea6-3f8dfb52c999.png)

Please let us know your thoughts.

Also, we are planning to give a quick demo once we are done with the implementation. This will make sure all of us are on same page.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Perfect! Sounds good!

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

As discussed on the status call, we are not able to add group selector for allowing user to configure the basemap group. Till the time we take a final call on configuration panel, we are planning to honor the org's settings.

If `useVectorBasemaps` key is set to true then we will use `vectorBasemapGalleryGroupQuery`  group in basemap gallery widget. Otherwise we will honor the `basemapGalleryGroupQuery` parameter.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, I haven't forgotten about this :). I'm discussing options with the AGOL team and will send you more info as soon as I have it.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could we make this configurable, and off by default?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can add a new option  `showBaseMapGallery` in the config file (default value will be false) and show it in configuration panel.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Thank you!! I realize I never wrote this into the issue description, so I appreciate you adding this parameter.

**Comment by allisonmuise** [comment]
verified

**Comment by gigaranger** [comment]
Hello Allison,

I am excited to see this get resolved for the basemaps to be available in the crowdsource reporter.

Is this configuration option available now for a app that is hosted in ArcGIS Online?

If so where do I make the change in the application?


Thanks,

Kenny Kleewein

GIS SPECIALIST
MATANUSKA-SUSITNA BOROUGH
INFORMATION TECHNOLOGY
350 E DAHLIA AVE
PALMER AK  99645-6411
907-861-8536

**Comment by allisonmuise** [comment]
@gigaranger This change with be available following the December release of ArcGIS Online.

**Comment by skrishn** [comment]
@allisonmuise : test case added. Label removed
