### ISSUE TITLE
Display form hints as grey, italicized text above the parameters

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#227]
Form hints are currently displayed below the parameter and looks slightly dissociated. The would be more helpful if they were above the parameter.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here are two options to show the hint text above and below. Please let us know which option you would like us to implement.

![image](https://cloud.githubusercontent.com/assets/2959186/17975559/cf61acd6-6b07-11e6-8440-4d18a3b15b27.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Option 1, please

**Comment by allisonmuise** [comment]
verified
