### ISSUE TITLE
add legend widget

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#229]
Display of reference layers has added many features to the UI. Would be helpful to have a legend to help interpret complex maps.

**Comment by allisonmuise** [comment]
https://geonet.esri.com/ideas/12968-option-to-add-legend-to-crowdsource-apps

**Comment by allisonmuise** [comment]
The UI for this might shift slightly over the course of development, but the functionality will remain the same, so please start there, and we can tweak the UI after I return.

Desktop mode:
I suggest starting with the button graphic from Basic Viewer. This button could sit in line with the navigation widgets on the left side of the screen. Clicking the widget would expand a panel (like the search does) containing the legend content. This panel should be styled to fit in with Reporter. Do not use the same styling from Basic Viewer.

Smartphone mode:
Let's try adding the item 'Legend' to the burger menu list in between Sign In and Help. Clicking this should open a modal with the legend info.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

Here is the screenshot of legend widget in desktop and mobile mode.

![image](https://user-images.githubusercontent.com/2959186/30740753-e6be181e-9faf-11e7-8784-5e3d819b0dfa.png)

Please confirm if this looks good.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I like it!

Will the access point for the legend be the same on desktop and mobile, or is it under the burger?

cc @ScottOppmann

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are planning to keep the access points same for mobile and desktop. This way user will always see Legend button irrespective of mobile/desktop mode.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Sounds good! Thanks!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could we make this configurable, and off by default?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can add a new key `showLegend` in the config file (default value will be false) and show it in configuration panel.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Thank you!! I realize I never wrote this into the issue description, so I appreciate you adding this parameter.

**Comment by allisonmuise** [comment]
verified
