### ISSUE TITLE
Tablet view needs to be more intutive

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/crowdsource-reporter#23]
In tablet view, it is hard to determine what to do when the app is opened.  It is hard to tell that I have to click a map name and once I open the map to know what to do with the layers.  The edit button to so far away, it is hard to see and hard to correlate with the active layer.  Not sure what best fix is, but maybe something like letting the user input custom text to the map and layer display.  Also, look at how the user can generate a new feature from the layer item in the accordion panel.

ex: 
To create a ${MapName}, click here
View ${LayerNAme} issues

**Comment by allisonmuise** [comment]
@MikeMillerGIS I'm closing this because I'm in the process of setting up a queue of work for CT that will (hopefully!) address this issue.
