### ISSUE TITLE
In RTL popup doesn display correctly when configured popup field is empty

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#231]
Open a reporter app in  RTL language like Arabic
Add a new feature and leave the field configured to show in Popup title empty and notice it doesn't get displayed correctly. The issue is noticed with existing features where the field value is empty

See the attached screenshot:  Popup is configured with 'name' field and the popup title displays differently with and without the field value

![image](https://cloud.githubusercontent.com/assets/3836616/17950718/d0ea8aba-6a11-11e6-9ebf-ddf1de146ae9.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Puctuation seems to be pushed to the left, even when it is provided by the users to the right. In the above example, the popup title is configured as Point: {name}, therefore the colon should always appear to the right of he word Point. This works when {name} has a value, but when it is null the colon gets incorrectly pushed to the left of Point.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise  @skrishn 

The browser handles rendering of text according to the locale. Application doesn't have control on it. Please see the image which shows although the title is set to "Charting:" browser is rendering it ":Charting"

![image](https://cloud.githubusercontent.com/assets/2959186/17975956/29529736-6b09-11e6-97f7-2a618b4bd86c.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Thanks for the explanation!
