### ISSUE TITLE
BUG-000098881

### ISSUE THREAD

**Issue by Carolinercraig** [Esri/crowdsource-reporter#232]
BUG-000098881 -- Crowdsource Reporter does not honor filters placed in the web map when the logged-in user views ‘My Reports’

**Comment by allisonmuise** [comment]
@Carolinercraig was this submitted through support?

**Comment by Carolinercraig** [comment]
Yes, it has. Support told me to log it here as well, with the Bug# given.  We do need this issue resolved as we discovered the issue using the FB integration.

**Comment by allisonmuise** [comment]
@Carolinercraig Thanks. I will close this issue then as it will be a duplicate of what is exposted from the support system after triage. You can track the status of the issue through the customer care portal.
