### ISSUE TITLE
issues with default values in date fields

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#236]
Current behavior with date fields:
Field not required, no default value = Today's date
Field not required, default value  = default value
Field required, no default value = Dec 31, 1899
Field required, default value  = default value

-> When field is required and no default date specified, use today's date not Dec 31 1899

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Can you please share the data where you are seeing the date as Dec 31, 1899 in case of Required field and no default value.

**Comment by allisonmuise** [comment]
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=261c0304dea9410697cd7a03933361e6

date field 2 has a default value and date field 1 does not. Both fields require values.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

[Feature service](http://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/rest/services/TestDates/FeatureServer/0) used in above application has default values for both date fields(DATE1 and DATE2). 

![image](https://cloud.githubusercontent.com/assets/2959186/18462579/08d4d9c8-79a1-11e6-8ba4-a2b48e72dc45.png)

The layer template has default values for DATE1 and DATE2 and this is the reason you are not seeing today's date for date field 1.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I'll investigate this further. I'm not publishing the layer with a default value specified. This might be something that is happening automatically.

Is it an option to treat Dec 31, 1899 as a null value?

**Comment by allisonmuise** [comment]
user error - value gets written tot he template in arcmap and must be removed.
