### ISSUE TITLE
508 compliance

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#240]
https://www.w3.org/TR/WCAG20/
https://www.w3.org/WAI/
http://webaim.org/
http://a11yproject.com/
https://a11ywins.tumblr.com/

**Comment by ashishchoure** [comment]
@allisonmuise 

As per the our discussion in the meeting, here are the points we need to discuss with Tao.

**1. Do we need to add keypress events on all the DOM’s which will be in focus and has some functionality on key press ?**

- Once the screen reader is active, the `click `and `keypress `events work one and the sane. In this case there is no need to write `keypress `event on each DOM elements.
- But what if user does not turn on  a screen reader and start using the keyboard for using the application? (Is this a valid use case?) In this case the keyboard ENTER, SPACE etc keys will not work.
- If the above case is valid, then we will have to add `keypress `events on DOM elements.

**2. In mobile devices all the elements irrespective of tab index are focused.**
- We are seeing different behavior in desktop and mobile devices, In mobile device all the elements are focused. Even if we have `tabidnex="-1"` still the elements are being focused.
- To confirm this behavior, we went through some 511 compliance websites and we saw the same behavior(Desktop and mobile behavior is different and almost all the elements are getting focus). 
- Is this expected or we are missing out on something ?

Please let us know your thoughts on above points. This will really help us in moving forward.

**Comment by allisonmuise** [comment]
@ashishchoure I just spoke with Tao. We are going to meet next Wednesday so he can show me how to run some tests on the code. I will write up the results of those tests for you in this issue so you can see the types of things that need to be fixed in order to meet our standards of accessibility.

In the meantime, he took a quick look at the app and has these three suggestions:

1. Remove tab indexes for non-interactive elements such as the app title on the splash screen, app title in the main view of the app, etc. These are unnecessary and could be causing some of the issues with the screen readers.

2. To prevent users from tabbing outside dialog boxes, you need to trap focus inside the dialog. There are examples on the calcite page that show how to do this in calcite web, but there should be an equivalent for bootstrap.

3. Yes, keypress events are required so that users can navigate the application using only the keyboard. Users who do not need the screenreader may be unable to use a mouse.

**Comment by ashishchoure** [comment]
@allisonmuise 

Thanks for the feedback. We will work on it and keep you updated.

**Comment by ashishchoure** [comment]
@allisonmuise 

1. As suggested, we have removed tab indexes from non interactive elements such as,
- App title in splash screen
- App title in app header
- Layer/feature title in Issue wall, Issue details, Geo form, My issues etc

However, we have few more non interactive elements such as,
- Section titles in Geo form, Comment form
- Modal header title
- Section titles (gallery section, comment section) in issue details panel etc.

We can easily remove the tab indexes from all of this, but user will lose the reference to the particular section. (EG : If we remove tab index of Gallery section title, the focus will directly set to first image in attachment gallery and there will be no reference to the user of what is being traversed)
Let us know how would you like us to proceed on this.

 2. We are still working on modal dialog issue

3. We have added `keypress` events to focusable elements which has some functionality attach to it.

**Comment by ashishchoure** [comment]
@allisonmuise 

While working on issue where the focus goes behind the Modal Dialog, we found the same behavior with the sample given in the bootstrap website. 

![508_comp_1](https://user-images.githubusercontent.com/5525972/47770987-858e3880-dd07-11e8-996d-64b573493653.gif)

Looks like something wrong is going on with bootstrap modal.

**Comment by allisonmuise** [comment]
Feedback from Tao based on the followign testing workflow:
1. run axe-coconut
2. Test tab order
3. Test with screen reader

Map:
- [ ] use role="application" for map div
- [ ] Map credits get role = "button"
- [ ] Use aria-expanded properties to reflect when credits are expanded/collapsed
- [ ] Tab order - after focus on map, go to the nav buttons, not the Esri icon

Category/Map list:
- [ ] Map name should be "button"
- [ ] Map thumbnail alt text should be "" (empty string)
- [ ] Info button - why does it have aria-hidden = True?

Feature list:
- [ ] CSS issue with selected row - use focus-offset to set the position of the selection slightly to the inside of the feature/row border so that it is centered on the row and easier to see
- [ ] Submit button has tab index assigned to parent and aria-label assigned to child. Tab index and aria-label should always be assigned at same level
- [ ] Add aria-selected label to currently selected feature in list. (This is visually indicated so it should be indicated to non-sighted users, too)

Details view:
- [ ] Remove tab index from popup contents and the comment header. Only interactive elements (buttons, links, etc) need tab index

Form view:
- [ ] Tab focus on thank you message is good!

General/Header:
- [ ] Define header and main landmarks
- [ ] Sign in button has tab index assigned to parent and aria-label assigned to child. Tab index and aria-label should always be assigned at same level

**Comment by allisonmuise** [comment]
@ashishchoure see notes above. Let me know if any of these is not reasonable. As mentioned on the call, I know there are some contrast errors, too. I'm not worried about those for this release.

**Comment by ashishchoure** [comment]
@allisonmuise

Thanks for the feedback. We will go through all the points and let you know what all things we can accommodate in this milestone.

**Comment by allisonmuise** [comment]
@ashishchoure Thank you for the update! That's fantastic that you were able to do nearly everything on the list. I agree that, given the effort required, the landmarks can wait a release.

Re: the headings on the comment and reporting forms. I believe that the screenreader will read the headings, even if they do not have tab indexes. Could you confirm if this is true or not? If the screenreader reads them in their place as the user traverses the form that is all that is needed for context. Including them in the tab order is just adding additional clicks for a user trying to navigate the UI.

**Comment by ashishchoure** [comment]
@allisonmuise 

While testing the application we have observed that only the focused content's are being read by screen reader. We have gone through some websites and found the same behavior. 
It will be helpful if Tao has such examples where the contents are being announced by screen reader without focus.

**Comment by allisonmuise** [comment]
@ashishchoure I spoke with Tao about this and there are other key combinations that are used for navigating the non-interactive elements of the page (Windows Narrator uses Caps Lock + arrow keys) And when navigating the app this way the text that doesn't have a tab order is read by the screen reader.

**Comment by allisonmuise** [comment]
@ashishchoure I'm going to close this as the main deliverable has been accepted. I will open individual issues for items I find during testing.
