### ISSUE TITLE
Honor filters on tables

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#241]
@CTLocalGovTeam 

Currently, the comments thread does not honor any filters that have been applied to the related table. What is the LOE to add this query when pulling in this content?

-A

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Honoring the filters is low LOE. We can easily include this change in upcoming code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Thanks!!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I see this change in Manager, but not in Reporter.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to reproduce the issue with the latest code.

The related table has a filter 'SHORT_INT = 3' and the application is honoring this value.
Here is the example :

![reporter_comments](https://cloud.githubusercontent.com/assets/2959186/20052526/5c5cc0e0-a4fa-11e6-9513-060f45d2f1cb.gif)

Can you please share the application link. This will help us to identify the issue.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I can't reproduce this after merging the latest code, either.
