### ISSUE TITLE
Apply org theming

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#242]
Please manage work on this issue separate from work on other issues for 4.4. 

Org-level theming options will be accessible in this JSON format:
{
header:{
background: "#337ab7",
text: "#fff"
},
body: {
background: "#FFF",
text: "#333"
},
button:{
background: "#D95F45",
text: "#333"
},
logo:{
small: "https://org.maps.arcgis.org/logo-small.png"
}
}

These options will be read in to the app and applied by the same mechanism that values from defaults.js are read in until alternate values are supplied in the configuration panel. This means that there may be a disconnect between what is shown in the config panel and the app's appearance. This is ok.

Schemas for the application of these options follow:

**Comment by allisonmuise** [comment]
![10-25-2016 2-34-06 pm](https://cloud.githubusercontent.com/assets/2752195/19705270/70452456-9ac0-11e6-85a2-213c7f483509.png)

![10-25-2016 2-34-24 pm](https://cloud.githubusercontent.com/assets/2752195/19705271/73654404-9ac0-11e6-967d-091e7d5acd98.png)

![10-25-2016 2-34-37 pm](https://cloud.githubusercontent.com/assets/2752195/19705275/79899ccc-9ac0-11e6-8639-0f6818ee37d2.png)

![10-25-2016 2-34-50 pm](https://cloud.githubusercontent.com/assets/2752195/19705278/7bea9890-9ac0-11e6-80ea-1a18d1a4d33b.png)

![10-25-2016 2-35-06 pm](https://cloud.githubusercontent.com/assets/2752195/19705280/7d78b192-9ac0-11e6-8b33-b426245baa3f.png)

![10-25-2016 2-35-18 pm](https://cloud.githubusercontent.com/assets/2752195/19705281/7f435ebe-9ac0-11e6-95fd-e56d558e01e4.png)

![10-25-2016 2-35-28 pm](https://cloud.githubusercontent.com/assets/2752195/19705283/81830f44-9ac0-11e6-9fee-2b58de1033ba.png)

![10-25-2016 2-35-38 pm](https://cloud.githubusercontent.com/assets/2752195/19705284/83015632-9ac0-11e6-8529-e1dcc15d8f41.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam CLARIFICATION:

The logo mentioned in the JSON will point to the application logo, NOT the favicon as indicated in the mockups. When a logo is specified at this level it will override the current logic for this logo. When no logo is specified, the app should use the current logic for finding a graphic for this space.

**Comment by allisonmuise** [comment]
Per AGOL team:

The config panel parameters will be connected to the org theming parameters by adding a sharedStyleProperty property to each of the affected parameters in the JSON. For example:

           {  
               "label":"Title logo:",
               "fieldName":"logo",
               "type":"string",
               "sharedStyleProperty":"logo.small",
               "tooltip":"Defaults to sample logo"
            },

**Comment by allisonmuise** [comment]
another change...the property name has been changed to SharedThemeProperty:
       {  
           "label":"Title logo:",
           "fieldName":"logo",
           "type":"string",
           "sharedThemeProperty":"logo.small",
           "tooltip":"Defaults to sample logo"
        },

Also - I sent Kedar credentials to access an organization that has the shared theme properties included in the org settings JSON.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I confirmed with Kelly that by default the org theme parameters will be NULL.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : The calculate colors should not be configurable, or defined anywhere as explicit values as they are not part of the defined shared theme. These values should always be calculated from the shared theme values. 

Please remove these parameters from default.js.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We added these keys for our internal testing. We will remove these keys in upcoming code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
All my previously-configured Reporter apps are picking up the shared theme colors. This is incorrect.

The shared theme colors should only override the default options with newly-configured apps. Once an app has been configured with a color scheme, the app should use those configured values.

The behavior in Crowdsource Manager is correct.

**Comment by allisonmuise** [comment]
The application logic should only read the values set in the configuration panel; there is no need for the app to handle any of the logic in deciding when org theme vs default vs configured values are used. The configuration panel will handle this logic.

**Comment by allisonmuise** [comment]
1) let's swap the colors used in the map selection panel so that the major color is the configured body color, and the calculated color is only used for the header bar, on hover, for the map details, and to indicate the selected map & layer.

2) Let's make the background of the feature list the configured body background instead of the calculated color. Use the calculated color on hover/selection.

3) let's make the background of that the geoform the configured body background instead of the calculated color

**Comment by allisonmuise** [comment]
Looks great!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : For backwards compatibility, the original 'theme' property must be used for the shared theme header.background property. The headerBackgroundColor should not be necessary.

Please make the necessary adjustments and submit a code drop ASAP.

Please copy Suba on this PR as I will be out of the office next week.

cc @skrishn

**Comment by skrishn** [comment]
@CTLocalGovTeam : I removed the headerBackgroundColor property from default.js and  configpanel.js along with its references in the config panel . I see the following behavior 

![image](https://cloud.githubusercontent.com/assets/3836616/22949223/5ae76e2c-f2b6-11e6-9229-9dcfdb3702d0.png)

Production app for reference

![image](https://cloud.githubusercontent.com/assets/3836616/22954542/d94272b6-f2cb-11e6-9e6a-0c87ca64cd45.png)

cc @allisonmuise

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @skrishn

Removing the headerBackgroundColor property from default.js and configpanel.js along with its references in the config panel will not work as it has some dependencies in the code. To remove the headerBackgroundColor property from default.js and configpanel.js we would need to do some code changes.

We will do the code changes and submit the pull request ASAP.

Please let us know your thoughts on this.

--Pratik Gohil

**Comment by skrishn** [comment]
@CTLocalGovTeam . Please go ahead and make the changes

Cc @allisonmuise

**Comment by allisonmuise** [comment]
verified!
