### ISSUE TITLE
New reports don't show under My Report

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#250]
1) sign in to Reporter app that tracks users
2) Submit a new report
3) go to My Reports

new report isn't listed

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I am still seeing the 'Feature cannot be displayed' message in Chrome and FireFox. Was the fix demonstrated in the status meeting included in the code drop?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The fix is for issue #247 is not included in the Wednesday's code drop. This will be included in upcoming code drop. However we have fixed issue #250. You should see the added issues in "My Reports".

**Comment by allisonmuise** [comment]
@CTLocalGovTeam ok - This issue was references in that code drop so I was confused. Seemed like a very quick turn-around :)

**Comment by allisonmuise** [comment]
verified
