### ISSUE TITLE
update twitter proxy URL

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#254]
Esri's twitter proxy has a new URL. Please update Reporter with the following changes:

 
    "twitterUrl": "/sharing/tools/tproxy/proxy/1.1/search/tweets.json",
    "twitterSigninUrl": "/sharing/tools/tproxy/signin",

    fullURL = this.config.sharinghost + this.config.twitterSigninUrl

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

After using the above mentioned [new](http://utility.arcgis.com/sharing/tools/tproxy/signin) twitter proxy signin url we are not able to see the twitter signin page instead we are seeing following json in window.
![image](https://cloud.githubusercontent.com/assets/2959186/20422256/3e7f6ba2-ad8f-11e6-80a3-de3950980c27.png)

Whereas when we use the [old](http://utility.arcgis.com/tproxy/signin) twitter proxy we see the following sign in page:
![image](https://cloud.githubusercontent.com/assets/2959186/20422299/8de687f2-ad8f-11e6-8aa0-0ef0aaf94b7c.png)

Could you please confirm if this proxy url will work as like previous one or their are some changes in the implementation which needs to be considered.

**Comment by allisonmuise** [comment]
@MikeTschudi : Is the same thing you were seeing with Polling? Is it being addressed at the Twitter Proxy side, or does @CTLocalGovTeam need to do something to address it?

**Comment by MikeTschudi** [comment]
It is the same.  At this time, the proxy can only be tested in the dev environment.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : If you send me a pull request with the update, I will install it into devext so that you can test this.

There will be a build to devext in approx 90 mins, and another around midnight PST.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : AGOL team is reverting these changes. Please return the code to the previous syntax.
