### ISSUE TITLE
Option to configure which geocoders are used in search

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#265]
https://geonet.esri.com/ideas/12970-customizing-geocoder-options-in-crowdsource-reporter

**Comment by allisonmuise** [comment]
The cbasic Viewer configuration panel includes a parameter for choosing the locator that is used for the app search widget. Please add this parameter to Reporter. It should control the geocode service used by the main search widget, and the search widget in the GeoForm.

**Comment by allisonmuise** [comment]
verified

**Comment by psoulages** [comment]
Please take me off this chain

**Comment by allisonmuise** [comment]
@psoulages To unsubscribe from a github repository you must sign in and choose 'Ignoring' from the menu at the top.
![image](https://user-images.githubusercontent.com/2752195/32246653-e3062b5c-be3c-11e7-8608-7c5884fc8952.png)
