### ISSUE TITLE
BUG-000101946 Labels using Arcade flicker on as layer loads

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#269]
1. Create a map in ArcGIS online that has an editable feature service. (e.g. http://ess.maps.arcgis.com/home/item.html?id=3d63b9d37fa2444b9b482d47c72d921b )
2. Open the option menu for the service > Create labels.
3. In the Text drop down select either a field or  Custom (Expression). If you select Custom, create an Arcade expression for the label.
4. Save the map (http://ess.maps.arcgis.com/home/item.html?id=c9c7f4bca7854b068dac0f0c1b86d14a)
5. Create a group (Groups > Create Group) and set the same level of sharing as the map. (http://ess.maps.arcgis.com/home/group.html?id=4ebef4b041a94dbc9c856812b66a61e9 )
6. In My Contents share the map to the group.
7. In My Contents go to Create > App > Using Template. Select the Crowdsource Reporter > Create Web App.
8. In the configure page, select the group you previously created and then save the app. (http://ess.maps.arcgis.com/home/item.html?id=3ec0dbcd065f4a82a89f61b8e1ac23fa )
9. Open the app and sign in. The label will be displayed for a second and then disappear.

Salesforce ID: BUG-000101946
Salesforce Submitter: Rebecca Richman
Salesforce Submit Date: 1/06/2017 10:46 AM
Salesforce Bug Type: Failure/Error
Salesforce Severity: Medium
Repro Data: (n/a)
Work Around: (n/a)
Product: ArcGIS Online
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: N/A
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please investigate and share the LOE to eliminate this flicker. Can this be done for 5.1?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This is same as #180.
The reporter app uses a graphic layer instead of directly adding the feature layer due to implementation of geo-filtering. Graphic layers do not support labeling.
The labels appear to flicker because on layer click in web-map list, feature layer is loaded on main map for a split second(to read its properties) and then it is immediately hidden and a new graphics layer is added in its place with the same properties.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I figured that hey might be related. How can we avoid that flicker?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can fix this issue with minor code change but we think this will need some extra time to test as it is related to how layers are handled in reporter application. So this will not be included in tomorrow's code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam ok

**Comment by allisonmuise** [comment]
verified
