### ISSUE TITLE
post-comment period workflow

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#271]
USFS, Geonet, etc:

How to support the workflow of a defined comment period, including leaving the app live and accessible for information purposes post-comment period

**Comment by allisonmuise** [comment]
The goal of this enhancement is to provide a access into Reporter after a defined commenting period has ended. Users should not be able to contribute new reports, comments, or votes through the app once the comment period has closed.

To accomplish this with minimal changes to the existing UI or configuration panel, I propoose the following:

1. Add a set of radio buttons to the configuration panel to allow users to toggle between the values 'Open' and 'Closed'. The parameter label should be 'The current reporting period is:'

2. Add a rich text parameter to the configuration panel for 'Message when reporting period is closed'

When the value of the first parameter is 'Open', the app should function as it currently does.

When the value of the first parameter is 'Closed', performing any of the following actions should result in a popover window (displayed like the help panel) with the content of the rich text parameter:
- Clicking the 'Submit a report' button at the bottom of the list of features
- Clicking the 'Vote' button
- Clicking the 'Comment' button

**Comment by allisonmuise** [comment]
toggling this radio button has no effect per #308

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : Verified.
