### ISSUE TITLE
store user credentials with comments

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#28]
repro steps:

App is configured to use field NAME for storing reporter name. Field NAME exists in feature class and related comments table.

1) sign into app using social media

2) Create a feature. Username is successfully written to NAME field for new feature

3) Comment on another feature. Username is NOT written to NAME field of comments table.

Please keep track of credentials in the comments table if the configured field exists in the table as well as the feature class.

**Comment by allisonmuise** [comment]
I'm putting this one in the backlog as well since we have decided not to make other changes to the commenting workflow for this release.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We will include this in the upcoming code drop.

**Comment by allisonmuise** [comment]
verified
