### ISSUE TITLE
Thank you message for comments

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#287]
Hoping to have a popup dialogue when a person submits a comment to an existing report, much like the dialogue that pops up when a person submits a report (default config var is “submitMessage”).  This would be especially helpful if/when we start filtering people’s comments to be turned off by default.

(DuPage Co)

**Comment by ashishchoure** [comment]
@allisonmuise 

We are showing the message  `"submitMessage": "Thank you! Your report has been submitted."` inside the geoform at the top.

However, after submitting the comment we close the comment form. So, we cannot follow the same approach of showing success message inside the form. Instead, we can easily show the alert message when comment is submitted successfully.

Here is the screenshot of geoform and comment form after submission : 
![image](https://user-images.githubusercontent.com/5525972/44644474-d4f77600-a9f1-11e8-9856-74829899a92a.png)

Let us know your thoughts and we can discuss this further if required.

**Comment by allisonmuise** [comment]
@ashishchoure I would like to keep the styling of the comments as close to the same as possible. Could the message be displayed at the top of the list of comments, instead? This would put the message in the same location as the comment form, even though the form is now closed.

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is the screenshot of message on top of the comments list: 
![image](https://user-images.githubusercontent.com/5525972/44659126-cb393700-aa20-11e8-9e67-9b7483ebfcf6.png)

However, when should we hide this message? After certain time ?

**Comment by allisonmuise** [comment]
@ashishchoure I'm not seeing a space for this message in the configuration panel. Am I missing it?

**Comment by ashishchoure** [comment]
@allisonmuise 

Apologies, as we missed to add the comments success message in configuration panel.

We have added this as a configurable option with default value same as in nls (`"Comments Submitted Successfully."`)and it will be delivered in the upcoming code drop.

**Comment by shoe913** [comment]
Verified

**Comment by skrishn** [comment]
@allisonmuise : added testcase
