### ISSUE TITLE
Map doesn't pan/zoom to search result location

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#289]
In the geoform, search for a location to submit a report. Notice that the map does not zoom/pan to this location, even though the point marker is placed there.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

After searching a location from the search control in geoform, the geoform map zoom/pan to the selected location.
As we are not showing geoform map in desktop mode. We are observing the issue only in desktop.
In mobile devices, the geoform map zoom/pan to the selected location as expected.

Please confirm if your observing this issue only in desktop?

So, to resolve this issue we will zoom/pan the main map to searched location of geoform search control.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Yes, please

**Comment by allisonmuise** [comment]
verified
