### ISSUE TITLE
BUG-000103577 An error returns in the Internet Explorer web browser when clicking to view the attached image in the Crowdsource Reporter.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#293]
<div><div><b>Open ArcGIS Online</b>
<ol><li>Sign into ArcGIS Online.</li><li>Select My Organization.</li><li>Select EDIT SETTINGS.</li><li>Choose the Security tab on left.</li><li>Check on Allow access to the organization through HTTPS only.</li><li>Select SAVE.</li></ol>
<b>Create a new feature layer </b>
<ol><li>Select My Content.</li><li>Select Create and Feature Layer.</li><li>Select AED and click CREATE.</li><li>Enter the title of layer and click DONE.</li><li>In the item details page of the created layer, copy it service URL.</li></ol>
<br><b>Create a new referring feature layer and web map </b>
<ol><li>Go back to My Content.</li><li>Click Add Item and From the web.</li><li>Select ArcGIS Server web service.</li><li>Paste the copied url.</li><li>Enter your ArcGIS Online user name and password.</li><li>Select Store credentials with service item.</li><li>Enter a title and add a tag and click ADD ITEM.</li><li>Add the layer to Map Viewer.</li><li>Click Edit and create a new feature. Attach an image file to it.</li><li>Save the map</li></ol>
<br><b>Create Crowdsource Reporter</b> 
<ol><li>Create a group.</li><li>Select the added layer and the map and share them to the group created in the previous step.</li><li>Go to the group page.</li><li>Click Share and CREATE A WEB APP.</li><li>Select the Crowdsource reporter template and click CREATE WEB APP.</li><li>Enter a title and add a tag, and click DONE.</li><li>Save and close the app</li></ol>
<br><b>Limit referrer URL </b>
<ol><li>In the app’s item details page, copy the URL.</li><li>Click My Content and click the added feature layer.</li><li>Click the Settings tab and click Limit Usage.In the Referrer URL or IP box, paste the copied app’s URL and click Add. Click OK.</li></ol>
<br><b>Test in IE </b>
<ol><li>Open the Crowdsource Reporter app in IE.</li><li>Open the app as a guest.</li><li>Click the feature in the right panel.</li><li>Click the attachment button.</li><li>Click the thumbnail image.</li><li>The error appears and the image is not shown.</li></ol>
<u><b>Notes:</b></u>
<ul><li>This issue is not reproducible in FireFox and Chrome.</li></ul>
<u><b>Data:</b></u>
<ul><li>Feature Layer: <a href="https://utility.arcgis.com/usrsvcs/servers/a97edb6866f4478abf6712630aea77ec/rest/services/CrowdsourceBug/FeatureServer" target="_blank">https://utility.arcgis.com/usrsvcs/servers/a97edb6866f4478abf6712630aea77ec/rest/services/CrowdsourceBug/FeatureServer</a></li><li>Web Map: <a href="http://trialafifah.maps.arcgis.com/home/webmap/viewer.html?webmap=17a58b8c6268463ab4397219e1d8726a" target="_blank">http://trialafifah.maps.arcgis.com/home/webmap/viewer.html?webmap=17a58b8c6268463ab4397219e1d8726a</a></li><li>Crowdsource Reporter URL: <a href="https://trialafifah.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=bd734cf0404b4b308f4ceba615b111c4" target="_blank">https://trialafifah.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=bd734cf0404b4b308f4ceba615b111c4</a></li><li>Please click &#39;View Note&#39; in this defect for account credential</li></ul></div><div>
<span><b>Salesforce ID:</b> BUG-000103577</span><br/>
<span><b>Salesforce Submitter:</b> Nur Afifah Azhar</span><br/>
<span><b>Salesforce Submit Date:</b> 3/13/2017 9:02 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> N/A</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I can still reproduce this issue, but it does require following the repro steps above exactly.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could you please summarize the information you've found so far on this issue?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are able to reproduce the issue. This is related to how the request's are handle.

When application request's the thumbnail of an attachment, the 'Referer' parameter is set to application URL.
![image](https://user-images.githubusercontent.com/2959186/29073475-5dd9284a-7c69-11e7-86a2-4f61e55e63a0.png)

However, when we click on image thumbnail to see the actual image, 'Referer' parameter is not present in the request. This is because we are doing window.open to see the image.

![image](https://user-images.githubusercontent.com/2959186/29073495-70e0080a-7c69-11e7-9179-4d24e988dda8.png)

'Referer' is nothing but the reference of browser page.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

As discussed, the only option to see the images in IE is to create a dialog which will open inside the application. This is high LOE and we need to change the entire approach to show images in a dialog box.

This will also need a lot of testing as CSR application is supported across different screen sizes.

**Comment by allisonmuise** [comment]
Thanks, @CTLocalGovTeam closing this issue as it is not something we can address within the framework of the app.
