### ISSUE TITLE
 DojoConfig: Update apps to set async:true to avoid console warning

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#296]
In apps that create a web map the following warning appears in the console unless dojoConfig async is set to true.

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

Set to true in config apps to remove this warning (and the associated problems it warns about) from the app.

**Comment by allisonmuise** [comment]
1649

**Comment by CTLocalGovTeam** [comment]
@allisonmuise  @skrishn 

The async parameter is already set to true in [dojo-configuration file](https://github.com/Esri/crowdsource-reporter/blob/develop/js/dojo-configuration.js#L26).

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Thanks for checking
