### ISSUE TITLE
Question: AGOL sharing vs the sign in page

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#298]
Given the following scenario, what can be done to improve the user experience. 

App, map, group, and layers are all shared with the Organization.
Sign in screen is disabled by turning off all sign in options
When the app is loaded in a clean browser, user is prompted for AGOL credentials. After providing credentials, app loads, but fails to load maps & layers. 
Content only loads after enabling and clicking the ArcGIS button.

The goal is to use Reporter without the sign in page without sharing all content publicly. How significant would the code changes be to enable this?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

We tried reproducing the above case. When map,layers and group are all shared with organization. On application load, we are getting message "`Configure group is invalid or no items has been shared with this group yet.`"

![image](https://user-images.githubusercontent.com/2959186/28775360-13412b26-760f-11e7-88a3-af2522f0a66b.png)

Could you please share the application link. This will help us to narrow down the issue.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We will discuss this issue in tomorrow's call.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Please also provide a summary here (after tomorrow's call is ok) so that those who are filling in while I am out of the office can have a complete picture of the issue.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We have analyze this issue and here are the details : 

- As per the current implementation of CSR, if all the signed in options are disabled the user is logged in to the application as a "Guest". 

- In the above scenario, although the user is logged in to a portal we are not honoring that and instead logging in as a "Guest" user. As all the contents are shared to org only and user is logged in as a "Guest", no contents are displayed in the application.

**Using following approach we can easily handle this scenario :**
1. When all the sign-in options are disabled, first we will check if user is already signed in to a portal.
   - We  can check signed in status with the help of [`IdentityManager.checkSignInStatus`](https://developers.arcgis.com/javascript/3/jsapi/identitymanager-amd.html#checksigninstatus) API method.

5. If user is signed in, we will proceed with portal login and user will see all the accessible contents.

6. If not then we will proceed as "Guest".

Please confirm if we can go ahead and implement this.

**Comment by allisonmuise** [comment]
verified
