### ISSUE TITLE
Cant submit new report when map JSON doesn't include popup configuration

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#299]
repro steps:

publish a feature layer using ArcGIS Pro 
(http://arcgis4localgov2.maps.arcgis.com/home/item.html?id=0b7f71728a5b461685bbc36b5b4b3b0e)

Add the layer to a map in AGOL, and save the map without editing the popup configuration 
(http://arcgis4localgov2.maps.arcgis.com/home/item.html?id=8c46e5904e644c7fb604e9f5fda65053)

Share the map with a group, and use the group to create a reporter app
(http://arcgis4localgov2.maps.arcgis.com/home/item.html?id=1c0e6e47f02246fa96f8ca39c256c914)

Try to submit a new report. The submission form doesn't draw.

Open the JSON for the map and notice that it doesn't contain the popup configuration
(http://arcgis4localgov2.maps.arcgis.com/sharing/content/items/8c46e5904e644c7fb604e9f5fda65053/data?f=pjson)

This should not prevent the app from functioning. It should fall back to the layer JSON, as it appears Manager is doing.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I've come across another issue that appears to be related to this one. please let me know if you'd like this as a separate github item.

In cases where the map JSON does not contain popup information for a layer, there seems to be some issues getting the field formatting from the popup config, even once it is included in the map JSON.

For example: 
Using a map that originally had no popup info in the JSON for the points layer: The JSON was added by turning off editing on one of the fields in the popup and re-saving the map. 

Once this was done, there was still no entry on the TEXT field for stringFieldOption and the field in the reporter form was showing up, by default, as multi-line, even though the default in the popup is single line. After toggling this setting to multi-line, saving the map, and toggling it back to signle line, and saving the map, I can now see the setting in the JSON, but the app is still showing me a multi-line text box. In the map viewer, I am getting the correct single-line behavior.

All of this content is currently on devext. I will send URLs to the service, map, and app via email.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are able to access the application link.

In the first attempt, app link was showing text area in the geo form. As per the implementation, if  `stringFieldOption `value is anything other than "textbox" then the field will be rendered as text area.

In the given case, the format option `currentField.stringFieldOption` for the text field was ‘undefined’, this was the reason geo form was showing text area. 

However, we tried editing the fields `stringFieldOptionpopup ` option to "singleLine" or "MultLine" and geo form is honoring this popup settings.

Please confirm if we are not missing anything and both of us are on same page. If not we can discuss it over a call tomorrow.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I believe we are on the same page, and I'm hoping it's a small fix....

Could the logic be adjusted so that, instead of showing textarea when the value is anything other than textbox, the form shows textbox when the value is anything other than textarea?

This way the app's geoform will mirror the popup logic, which is to show the single-line box, unless the popup is specifically configured to show the multi-line box.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This is a small fix. It will be available in the upcoming code drop.

**Comment by allisonmuise** [comment]
verified
