### ISSUE TITLE
reference layer popup showing even when popup disabled

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#300]

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are able to reproduce the issue. When reference layer's popup is disabled, we are seeing an empty panel.
![image](https://user-images.githubusercontent.com/2959186/28671270-b4f64a1e-72f9-11e7-8bcd-0acd7956844f.png)

To resolve this issue, on map click we can easily check if layers popup is enable/disable and then will do further processing.

So if selected features(reference layer feature) popup is disabled, nothing will happen on feature click.

Please let us know your thoughts on this approach.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, this sounds good. Thanks!

**Comment by allisonmuise** [comment]
verified
