### ISSUE TITLE
Issue with geographical extent layer

### ISSUE THREAD

**Issue by walzjc** [Esri/crowdsource-reporter#302]
I am having an issue with the geographical extent layer. 
![image](https://user-images.githubusercontent.com/17415343/28882265-5cff67b6-7770-11e7-8cfb-8cb5f260bc6c.png)
When I enter the point within the extent layer it still does not submit or create the record. 
![image](https://user-images.githubusercontent.com/17415343/28882408-c4b48d1e-7770-11e7-84cb-5b7673598412.png)
I have the extent layer placed within the basemap feature. Any ideas?
![image](https://user-images.githubusercontent.com/17415343/28882419-cc6d0626-7770-11e7-9b29-5ff639e9a632.png)

**Comment by allisonmuise** [comment]
@walzjc Does it work if the extent layer is not part of the basemap group?

**Comment by walzjc** [comment]
I tried it both ways and it still does not work. If the extent layer is not part of the basemap group it will not be displayed.

**Comment by allisonmuise** [comment]
@walzjc 

If you cannot successfully submit a report when the extent layer is not part of the basemap group, the submission issue is unrelated to the location of the extent layer. The suggestions here might help resolve the message you are seeing: https://geonet.esri.com/message/641346-cannot-submit-report-on-crowdsource-reporter

The issue with the layer drawing can be resolved by removing it from the basemap group, making the extent layer uneditable, and setting showNonEditableLayers to true. 

If this does not resolve the issue, I recommend contacting Esri Support Services or your local distributor as they have more resources for troubleshooting issues like this.

**Comment by walzjc** [comment]
The extent layer is now showing up when it is not included in the basemap group. I also got it to submit the reports.
However, I can still submit a report even if it is located outside of the extent layer. Any ideas?

**Comment by allisonmuise** [comment]
@walzjc please share a link to your application

**Comment by walzjc** [comment]
http://gis.co.sherburne.mn.us/ServiceRequest

**Comment by allisonmuise** [comment]
@walzjc 
Ah...I think I know why it's not working.

Try adding the county layer directly to the map using the url https://gis.co.sherburne.mn.us/arcgis/rest/services/ServiceRequest/CountyServiceZones/MapServer/0

How it's added right now, the actual layer you are referencing is buried one layer deep in the TOC. I'll add a note to mention this in the doc next release.

**Comment by walzjc** [comment]
Thanks! The application is now working correctly.
