### ISSUE TITLE
radio button parameters not working

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#308]
Toggling the values of the two radio button parameters (closing comment period & list vs map view on mobile devices) has no impact on the application's behavior.

This is reproducible on production for the map vs list view parameter, and on devext for both of them.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @skrishn 

We are not able to reproduce this issue in Dev Ext.  [Here ](http://localgovtestdev.mapsdevext.arcgis.com/home/webmap/configureApp.html?appid=bbd9f313b7ca4d7da05f224caa1e239c)is the link of application published on Dev Ext.

However, we have found a minor issue where "reporting period" parameter is not honored when user clicks on "Submit a Report" button in Map View(Mobile mode) and we have fixed this issue at our end.

**Comment by skrishn** [comment]
@allisonmuise @CTLocalGovTeam : I can still repro the issue - when map view is selected; the app doesn't honor it 

I also noticed that issue you mentioned. 

I think it could be related. Please test again and let me know when you have can the fix

**Comment by CTLocalGovTeam** [comment]
@allisonmuise  @skrishn 

We have resolved the above mentioned issue in today's delivery. Please have look at it.

However, we are still not able to reproduce the radio button issue at our end. [Here ](http://localgovtestdev.mapsdevext.arcgis.com/home/webmap/configureApp.html?appid=bbd9f313b7ca4d7da05f224caa1e239c) is the application link published on Dev Ext. The radio buttons are working as expected.

Could you please share the application link? This will help us to find out root cause of the issue.

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : I can still repro the [issue ](http://localgovdev.mapsdevext.arcgis.com/home/webmap/configureApp.html?appid=0fdf009caaab4484b10f2bfd8d062dd3)- 

- Reporting period to 'Close' is not honored. 
- Map view in mobile setting is not honored.

Please try to fix this asap.

**Comment by CTLocalGovTeam** [comment]
@skrishn @allisonmuise 

We are able to reproduce the issue of "Map/List" view with the given link.

This is a specific scenario where we doesn't show web map list when single web map has a single layer in a group. For this case the "Map/List" parameter was not honored. We have fix this issue and we are planning to deliver this tomorrow.

For the issue related to Reporting period, we are not able to see the latest code in the given app link. Can you please check if this is the app template is created with latest code?

![image](https://user-images.githubusercontent.com/2959186/29607138-e97fc3ae-880d-11e7-867f-8e83011e8a47.png)

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : I'm sorry there was a merge conflict. I verified and the 'Close' parameter is fixed but the map/list is not. Its good that you were able to drill down map/list issue. Thanks!

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : Verified. Thank you!!
