### ISSUE TITLE
App doesn't display features symbolized using an Arcade expression

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#310]
Note that features appear in list, but not in the map area of the app. 
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=098f251d4b094998961466c2f2ce84b9

The features are visible in the map viewer:
http://arcgis4localgov2.maps.arcgis.com/home/webmap/viewer.html?webmap=d7b0a053e0d64a0e83b209386f5a9563

(also reproducible on devext with latest code drop)

**Comment by allisonmuise** [comment]
If this is high LOE, can move to 5.4 as it isn't a regression for 5.3

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @skrishn 

We are looking into this issue and we will keep you updated.

**Comment by skrishn** [comment]
@CTLocalGovTeam /cc @allisonmuise  Whats the status of this issue - can you get us a fix for 5.3?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @skrishn 

Form our initial analysis this seems to be an high LOE ticket. As suggested it will be good if we address this in 5.4 release.

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : Thank you.

**Comment by allisonmuise** [comment]
verified
