### ISSUE TITLE
BUG-000106163 Using the Citizen Problem Reporter template in ArcGIS Online, if a custom geocoding service is used, and a point is clicked on the map, the address of the location does not get populated in the specified field.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#311]
<div><div>Configuration: ArcGIS Online, Citizen Problem Reporter Template
<ol><li>Sign into ArcGIS Online with the credentials found in the notes.</li><li>In My Organization -&gt; Edit Settings -&gt; Utility Services, notice that there are two geocoders - the Esri World Geocoder and City of Charlotte. The Esri World Geocoder should be at the top.</li><li>Open the Citizen Problem Reporter application here <a href="http://marysolutions.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=1a65ce5812734d0c9c5fbcbf6b3648b3" target="_blank">http://marysolutions.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=1a65ce5812734d0c9c5fbcbf6b3648b3</a> and sign in using your ArcGIS Online account. </li><li>Submit a Report, and then zoom in on a location. Click on a location on the map. Optionally, open Fiddler or Dev Tools to see that there is a ReverseGeocode request and an address is returned in the response. </li><li>Select the type of problem and then submit the report. </li><li>Open the Item Details page for the RoadProblemReports service (<a href="http://marysolutions.maps.arcgis.com/home/item.html?id=213b3d3008d84cd1b08289181a990927" target="_blank">http://marysolutions.maps.arcgis.com/home/item.html?id=213b3d3008d84cd1b08289181a990927</a>), and view the Data tab. Notice that the Location field is populated with the address for the point that was created in Step 4. </li><li>Back in My Organization -&gt; Edit Settings -&gt; Utility Services, move the City of Charlotte geocoder ahead of the Esri World Geocoder and save this setting. </li><li>Repeat step 3 and 4, using Fiddler or Dev Tools to see the ReverseGeocode request. Then repeat Step 5 to submit the report. </li><li>Back in the Item Details page for the RoadProblemsReports service, check the Data tab. Notice that the Location field for this second point is not populated with an address.</li></ol></div><div>
<span><b>Salesforce ID:</b> BUG-000106163</span><br/>
<span><b>Salesforce Submitter:</b> Mary Long</span><br/>
<span><b>Salesforce Submit Date:</b> 6/28/2017 9:53 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> N/A</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
1708

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to reproduce the issue. We tried couple of geocoder's and application was populating the location as expected.

Could you please share the geocoder url with which app is failing to populate the location field.

**Comment by allisonmuise** [comment]
I have asked the support analyst for the URL to the service mentioned in their repro steps.

**Comment by allisonmuise** [comment]
I can no longer reproduce this issue, either.

**Comment by allisonmuise** [comment]
actually - yes I can. I cannot share the URLs to the locators though, as they are all inside the firewall. I will demonstrate on tomorrow's status call.

**Comment by allisonmuise** [comment]
https://github.com/Esri/election-widgets/issues/285

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I am still able to reproduce this issue on the most recent code drop, which is now on devext.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This functionality is working fine at our end. Could you please share the application link and data.

Also, the location field should satisfy the following condition before it is consider as a valid field: 
- Field should be type string
- Field should be editable
- Field should not be a type id field
- Field should not be a domain field

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I will demo this on this morning's call. The location is being written successfully to the same field using the same workflow and the World Geocode Service.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam This is verified. The custom locator I was testing with didn't cover the area I was testing in.
