### ISSUE TITLE
Unable to draw lines and polygons in the app

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#312]
Issue is noticed with layers published from Pro

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @skrishn 

We have fixed this issue in the today's code drop. Could please test and let us know if you are still able to reproduce this issue ?

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise Verfied. Thanks!
