### ISSUE TITLE
Feature layer with only date field types

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#313]
After a report is submitted is with a feature layer with only date field types, subsequent reports with different field types will be populated 
Steps to reproduce:
Example app: refer to the email
1.	Open ‘Many Layer – Mixed Editable Layers’ and submit a report to Edit Layers – Short Integer Field. 
2.	Submit a report to Edit Layers – Date Field.
3.	Go back to EditLayers – Short Integer Field and submit another report. 
4.	It initially lets you populate the fields with the correct information. Once you hit submit it through a “Values could not be submitted” error and the optional field is populated with a date data type.

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : I can still reproduce the issue with the steps mentioned above. Please look into it and let me know.

**Comment by CTLocalGovTeam** [comment]
Please share the app link to reproduce.

**Comment by skrishn** [comment]
I am using the same link that was in the initial email.

**Comment by CTLocalGovTeam** [comment]
@skrishn 

The app which shared in the initial email does not reflect the latest code.
For e.g. geo-form.js changes we [committed](https://github.com/Esri/crowdsource-reporter/commit/443d21f5aa0bc2801b38b7dd646cbf821dceb998#diff-92b02d5e4a88bfd4af764b8265a2251aR92). 

![image](https://user-images.githubusercontent.com/2959186/29585545-2317c67a-87a5-11e7-97a1-a4a671984c78.png)

Could you please confirm if the code changes are updated in build.

**Comment by skrishn** [comment]
@CTLocalGovTeam Ok - i will check and get back

**Comment by skrishn** [comment]
@CTLocalGovTeam @allisonmuise : Verified. Thanks!
