### ISSUE TITLE
Add proxy support for locally-hosted installations

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-reporter#324]
Add ability to proxy content. Example use:  public group with org-only webmap(s).

To configure,

* Add the sharing and feature layer URL prefixes to the proxy.config file using the credentials of a registered app in ArcGIS Online (e.g., using clientID & clientSecret or username & password):
```
<serverUrl url="https://www.arcgis.com/sharing/rest"
           clientId="3498FC38947FJWFA"
           clientSecret="654ab56c7654e54df5ecc54573ea4a34"
           matchAll="true"/>
<serverUrl url="https://services.arcgis.com/b6gLrKHqgkQb393u"
           clientId="3498FC38947FJWFA"
           clientSecret="654ab56c7654e54df5ecc54573ea4a34"
           matchAll="true"/>
```
* Also add them to the defaults.js file, but without the protocol:
```
"proxyThesePrefixes": ["www.arcgis.com/sharing/rest", "services.arcgis.com/b6gLrKHqgkQb393u"],
```

Guest login can then be used to view the protected webmap.

Implementation merged into `develop` branch with commit 7929a0b1cc98f3167f4b11788c175603057724b0

**Comment by allisonmuise** [comment]
@MikeTschudi Thanks!

**Comment by allisonmuise** [comment]
verified
