### ISSUE TITLE
CSS issue when report has no title

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#326]
When the first report in the list has no title, the height of that report in the list becomes smaller once the report has been viewed.

1) open the app http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=f5fb7fe07e3542d1806d4eb4a4af6f97#
2) click the map Animal Control Problems
3) Notice that the first item in the report list has no value for the popup title fields
4) click the report with no title
5) click the < button to return to the list and notice that the list display has shifted slightly

![image](https://user-images.githubusercontent.com/2752195/32248119-dd69093a-be41-11e7-955f-8d46b4bab2b2.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We too have found this issue in our internal testing. It is in testing phase and we will deliver this in upcoming code drop.

**Comment by allisonmuise** [comment]
verified
