### ISSUE TITLE
Timing Issue #2

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#327]
I'm not sure if this is related to Mike's issue or not, but I run into it ~50% of the time I'm accessing an app on production or devext.

Open the app http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=f5fb7fe07e3542d1806d4eb4a4af6f97#

1. As soon as the map list becomes visible, click the Animal Control map once. 
2. Wait while the rest of the map list and map list loads. The app won't go to the report list for the selected map.
3. Click the same map again on the list. The app will try to go to the report list, but the report list panel will fail to draw fully and the app will freeze. By 'fail to draw fully' I mean that no reports will be listed and the Submit button won't draw (but the + sign will).

This is a question of timing. If I take my time and let the app and map load and draw fully between each click, I don't run into this issue. I can reproduce this fairly consistently when I am rushing. I don't see any errors in the console that might indicate where the issue is.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are working on this and we will keep you updated.

**Comment by allisonmuise** [comment]
looks good. im unable to reproduce the issue anymore
