### ISSUE TITLE
Query and Edit Related Table in Application

### ISSUE THREAD

**Issue by kphaneuf** [Esri/crowdsource-reporter#330]
I'd like to have a related table update when a report is created.  For example, a report at a bus stop for trash or graffiti, then an attribute in that related stop in the bus stop table is updated, thus updating the symbology for that bus stop.  I found this script but am unsure where to place it or how to reference the layers.  Any help is greatly appreciated.
https://developers.arcgis.com/javascript/3/jssamples/ed_relatededits.html

Thanks!
Krystal

**Comment by allisonmuise** [comment]
@kphaneuf - 

Some things to consider based on your brief description:

 - you will need to create a new related record, not just edit an existing one, as the new report will not have any existing related records. Based on this you may be able to populate the attributes using default values.

- I don't believe there is currently a way to symbolize features based on values in related tables, as this idea is still open: https://community.esri.com/ideas/10702

I am closing this issue as it is outside the scope of the development of this app, but I suggest posting your question to Geonet where others who have customized this app might be able to provide further help
