### ISSUE TITLE
popup title is redundant in details view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#341]
popup title displays in both the colored bar, and at the top of the details text. Can we leave the layer name in the colored bar from the report list view, and only display the popup title in the details?

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is the screenshot of the issue-details panel after replacing the popup tile with layer title.

![image](https://user-images.githubusercontent.com/5525972/44645418-2d7c4280-a9f5-11e8-8705-1a6ca3d978c2.png)

**Comment by allisonmuise** [comment]
@ashishchoure Yes, I like it!

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@allisonmuise Added test case
