### ISSUE TITLE
Changes to report location search

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#346]
A few questions came up with regards to the search on the geoform. Could you let me know the LOE? If they are small enough, and if you have time, I'd like to get these in for April.

1) The search suggestions box doesn't close, even after selecting an address. Can we make it close? It takes up a lot of space...
 
2) Could we populate this box with the reverse-geocoded address (if available) when a user zooms to their location, or when they draw the location on the map? The same value that is written to the Location field would be adequate - just some obvious indicator on the form that a location has been selected.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are analyzing this ticket and we will keep you updated.

Thanks

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is our response.

1. The search suggestions box doesn't close, even after selecting an address. Can we make it close? It takes up a lot of space...

     > We can easily close the suggestion box once user selects the location.

2. Could we populate this box with the reverse-geocoded address (if available) when a user zooms to their location, or when they draw the location on the map? The same value that is written to the Location field would be adequate - just some obvious indicator on the form that a location has been selected.
    
   > As per our understanding, if a valid location field is configured and valid address is obtained after drawing location on map. We just need to show the address in the search text box? Please confirm.

**Comment by allisonmuise** [comment]
1. Good, thanks:)
2. Yes, The only functional change would be to show the address that will be written to the field in the search box. This will indicate to users that the location of the report has been captured and they can continue filling out the rest of the submission form.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We will deliver this change in upcoming code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I see the first change - the search box now closes after a result is selected. I don't see the second change, tho.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

Could you please share the application link.
