### ISSUE TITLE
reference layer title can't be configured

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#347]
The title that displays in the bar for reference layers is the name of the layer in the service. This is text that users frequently have no control over, and can be quite unfriendly to read. 

![526bb3e5](https://user-images.githubusercontent.com/2752195/35749443-645a35be-0806-11e8-9708-7e4040e23601.PNG)

Instead of the layer name from the service, could the app display the name of the layer from the TOC?

If this is low LOE, could this change be included for the 6.1 release?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are analyzing this ticket and we will get back to you in early next week.

Thanks

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are thinking of two options : 
1. As suggested, use the layer title from TOC.
2. Show the popup title of a selected non-editable feature in header. This way it will be consistent with the details panel of editable feature. (please see the screenshot)

![image](https://user-images.githubusercontent.com/2959186/36090671-460c2d20-1007-11e8-9011-6481e31de437.png)

Please let us know your thoughts.

Thanks

**Comment by allisonmuise** [comment]
Let's go with option 1. While I usually go for consistency, in this case I prefer the layer name to avoid having the same text shown in the blue bar and the bolded header. 

A similar change may come at some point for the report layers, but it's more complex due to backwards compatibility. I'd rather just do the reference layers 'right' from the start, and worry about the harder question of the report layers later.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Thanks for the quick reply. 
We will make the necessary changes in upcoming code drop.

**Comment by allisonmuise** [comment]
verified
