### ISSUE TITLE
help configuration

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#352]
I can't configure different content on the sign in page and the ? windows anymore. I always ge tthe same content for both windows regardless of the status of the 'Display different content on sign in page‎' checkbox in the configuration panel.

**Comment by allisonmuise** [comment]
cc @skrishn can we add a test for this?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @skrishn 

We are not able to reproduce the issue at our end.

![csr_help_dialog](https://user-images.githubusercontent.com/2959186/40959030-074812ce-68b9-11e8-80ba-01bc24e283e0.gif)

Could you please provide the steps to reproduce.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam My apologies - I thought I was using the config installed in devext, but it was a custom config panel that was improperly set up.
