### ISSUE TITLE
configurable option to disable use of user location

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#353]
Add a configurable option which, when enabled, will make the application never prompt for the user location, and should not use the user's location if it was previously shared with the app.
By default this option should be disabled.

**Comment by allisonmuise** [comment]
to clarify - this should not disable users' ability to use their location when submitting a feature - only when initially loading features

**Comment by ashishchoure** [comment]
@allisonmuise 

This will not impact the functionality of selecting current location while feature submission.

**Comment by allisonmuise** [comment]
verified
