### ISSUE TITLE
support sorting comments asc or desc

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#356]
Add configurable parameters (Field selection & asc/desc options) to control the sort order of the related records.

**Comment by ashishchoure** [comment]
@allisonmuise 

We are planning to add two configuration parameters "commentSortField" and "commentSortOrder".
The field selection will be a text input and order selection will be a drop down. If a valid field is entered the comments will be sorted as per the configured order.

**Comment by allisonmuise** [comment]
@ashishchoure Sounds good!

**Comment by allisonmuise** [comment]
verified

**Comment by allisonmuise** [comment]
@ashishchoure what types of fields should be supported for sorting the related records? Text fields seem to work, but sorting on integer and OBJECTID don't seem to work. Just curious what the restrictions are.

**Comment by skrishn** [comment]
I cant get it to sort on an integer field. 

![image](https://user-images.githubusercontent.com/3836616/47882527-0cfea900-dde7-11e8-8d79-1136d47b3ef6.png)

Here is the link to the app: https://lgtest.mapsdevext.arcgis.com/apps/CrowdsourceReporter/index.html?appid=28b882f8fa1f4cc490982c4818d43bb4

**Comment by allisonmuise** [comment]
@skrishn The configuration looks like it is using the field alias. Could you try with the field name? Alias isn't expected to work.

**Comment by skrishn** [comment]
@allisonmuise : Ok. it works without Alias

**Comment by allisonmuise** [comment]
@ashishchoure Sorting looks good for the field types listed above, but it would be nice to be able to sort on OID fields.

**Comment by ashishchoure** [comment]
@allisonmuise

We will add OID field type in the above list.
This will allow user’s to sort the comments based on OID field.

**Comment by shoe913** [comment]
Verified

**Comment by skrishn** [comment]
@allisonmuise : Added testcase
