### ISSUE TITLE
Ability To Change Location of Submit Button

### ISSUE THREAD

**Issue by kphaneuf** [Esri/crowdsource-reporter#362]
We would like to be able to move the Submit button to the top of the sidebar container.  I can't figure out how to do this in the code.  It would be nice if it was an option in the configuration similar to the form sections.  If there is a way to change it in the code please let me know.
![image](https://user-images.githubusercontent.com/13141791/43931588-16c0e62c-9bf4-11e8-9558-36785c962eab.png)

**Comment by allisonmuise** [comment]
@kphaneuf Configuring the Submit button to appear at the top of the list is not currently supported, but it is something we are considering as part of making the application more accessible.

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is the screenshot of Issue list after making the position of "Submit a Report" button configurable (Top/Bottom).

![image](https://user-images.githubusercontent.com/5525972/44703738-64fef380-aab6-11e8-8ab6-a823db4e614f.png)

**Comment by allisonmuise** [comment]
@ashishchoure looks good!

**Comment by allisonmuise** [comment]
verified

**Comment by skrishn** [comment]
@allisonmuise added test case
