### ISSUE TITLE
remove titles from map details text areas

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#364]
![9-24-2018 1-24-09 pm](https://user-images.githubusercontent.com/2752195/45977019-2ef15880-bffd-11e8-876a-107f34bf0427.png)

@ashishchoure is this low enough LOE to squeeze it in for 6.4? If not, I'll make the nls strings "" and we can fix the spacing later

**Comment by ashishchoure** [comment]
@allisonmuise 

A lot of information goes into the map details area such as "owner", "description", "snippet" etc.
Here is the list : 
```    "webMapInfoDescription": true,
    "webMapInfoSnippet": true,
    "webMapInfoOwner": true,
    "webMapInfoCreated": true,
    "webMapInfoModified": true,
    "webMapInfoLicenseInfo": true,
    "webMapInfoAccessInformation": true,
    "webMapInfoTags": true,
    "webMapInfoNumViews": true,
    "webMapInfoAvgRating": true 
```
Consider a scenario where all or atleast 5-6 options are configured and we remove the section titles, then it will be difficult for user to distinguish what all information is displayed.
Here is the screenshot above metioned scenario : 
![image](https://user-images.githubusercontent.com/5525972/45998123-6e807900-c0bf-11e8-8143-651b8da3002a.png)

Even if remove the sections which has empty values, still the UI will not look good.
![image](https://user-images.githubusercontent.com/5525972/45998225-cf0fb600-c0bf-11e8-8d53-da89620171b2.png)

We think we should keep the section titles and we can remove the configured empty sections completely to avoid the spacing issues.
EG : The "description" field was configured but its value was empty. Hence it is not shown in the webmap info panel.
![image](https://user-images.githubusercontent.com/5525972/45998436-7987d900-c0c0-11e8-89b1-a7ec47a7438d.png)

The above mention approach is low LOE and we can easily do this in 6.4 release.

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
I like removing sections that aren't used, but I still have several users asking for a way to remove the headers. In many cases they are only displaying one section - Description - and they are using the space to provide instruction, context, disclaimers, etc. The title Description is a bit out of place in this case.

That being said, you make a good point about creating confusion when many/all sections are on. 

Could we (in order of priority) 
1) add a config option to hide the section titles
2) hide sections that don't contain any info (would this also hide the (i) icon when all the sections are blank?)

**Comment by ashishchoure** [comment]
@allisonmuise 

We will add two keys in the configuration panel : 
1. `hideSectionTitle` with default value as "false"
2. `hideEmptySectionContent` with default value as "false"

Appraoch : 
- If `hideSectionTitle` is "true" then section title will be hidden
- If `hideEmptySectionContent` is "true" then the section with empty values will be completely hidden
- If all the configured section's have empty values and `hideEmptySectionContent` is set to "true" then info icon will be hidden.

Please let us know if you if this looks good and we are on same page.

**Comment by allisonmuise** [comment]
@ashishchoure sounds good!

**Comment by allisonmuise** [comment]
@ashishchoure I don't see these config options in the config panel. Are these the names that were used?

**Comment by ashishchoure** [comment]
@allisonmuise 

We have updated the keys for these configurable options to `showSectionTitle` and `showEmptySectionContent`.

This change was made to keep the consistency in config panel. We always use key values starting with show or enable.
EG : `showMapFirst`, `enableFacebook` etc.

We miss to update you about the change in keys.
