### ISSUE TITLE
Help hyperlink in Sign In Options section directs users to Crowdsource Polling app

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/crowdsource-reporter#372]
@allisonmuise: The help hyperlink in the Sign In Options section, on the Access tab, in the Crowdsource Reporter application configuration, directs users to Crowdsource Polling Configure social media sign in topic.

![image](https://user-images.githubusercontent.com/2781011/46432827-2f84a000-c71d-11e8-857a-e45fbaaad732.png)

**Comment by allisonmuise** [comment]
updated config panel sent to ian
