### ISSUE TITLE
Does zooming and scaling need to be disabled?

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#385]
This is marked as a critical issue. Is there a reason this is disabled?
![11-14-2018 2-04-53 pm](https://user-images.githubusercontent.com/2752195/48515712-5226d000-e816-11e8-8743-ecf5588ac414.png)

**Comment by ashishchoure** [comment]
@allisonmuise 

The scaling is disabled to prevent the unnecessary zoom in mobile devices. 
EG : If scaling is not disabled, clicking on any of the text input controls causes app to zoom and center the text input control.

**Comment by allisonmuise** [comment]
ok - let's leave this for now, but we may need to revisit based on feedback.
