### ISSUE TITLE
Before calling toJson on infoTemplate, check for null

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-reporter#412]
Patch for cloning infoTemplate on line 2425 of main.js

cf. #409 and https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/commit/ace78b22ef8a8f3c10a6f5dcd6b7f4a827fee9f3#commitcomment-10822

**Comment by MikeTschudi** [comment]
While making this change, call should be enhanced for safety; from Praveen:

>  ...the constructor you've used during the cloning process should be the same as the one used for the object being cloned i.e. you need to use either PopupTemplate or InfoTemplate.
>
> A quick way to do that would be:
>
>  ```var newTemplate = new oldTemplate.constructor(oldTemplate.toJson());```

**Comment by ashishchoure** [comment]
@MikeTschudi @allisonmuise 

> 1. Can we guarantee that selectedOperationalLayer.infoTemplate is not null in _initializeLayer()?

Ans: Only layer with a valid popupInfo is considered as editable layer in the reporter application. So, `selectedOperationalLayer.infoTemplate` will never have a null value.

> 2. Can we guarantee that selectedOperationalLayer.infoTemplate is an InfoTemplate?

Ans : `selectedOperationalLayer` is feature layer instance from webmap. So,`selectedOperationalLayer.infoTemplate` will always be a valid infotemplate object.

Please let us know if this make sense.

**Comment by allisonmuise** [comment]
@ashishchoure Sounds good. Thanks for the explanation!
