### ISSUE TITLE
BUG-000114931 The Legend widget in the Crowdsource Reporter application does not work when the web map use a vector tile layer as a layer, not as a basemap.

### ISSUE THREAD

**Issue by shoe913** [Esri/crowdsource-reporter#415]
Followed the workflow from the CrowdSourceReporter documentation to configure the application:
(http://solutions.arcgis.com/local-government/help/crowdsource-reporter/get-started/create-template/)
Change the "showLegend" property to "true" to display the legend in the default.js file.
Created a group in ArcGIS Online and added the webmaps to the group that are displaying in the application.
When you include a webmap with a vector tile layer as a layer, the legend widget fails for the feature layer. 
"Cannot read property 'capabilities' of undefined" error message displays in the console tab of the developer tools.
When the vector tile layer is added as a basemap, the legend widget works.
Attached is an application with both a webmap that has the vector tile layer as a basemap, and a separate webmap that has the vector tile layer as a layer, which causes the legend widget to fail.
Can also access the application here:
https://jbanuelos.esri.com/CrowdSourceReporterGit/CrowdSource/index.html
The legendMap webmap has the vector tile layer as a layer with the legend widget failing.
The legendMapBasemapVTL has the vector tile layer as a basemap with the legend widget working.
Salesforce ID: BUG-000114931
Salesforce Submitter: Jose Banuelos
Salesforce Submit Date: 6/27/2018 1:56 AM
Salesforce Bug Type: Failure/Error
Salesforce Severity: Low
Repro Data: \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000114931
Work Around: Use a vector tile layer as a basemap.
Product: ArcGIS for Local Government
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: N/A
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by shoe913** [comment]
2249

**Comment by ashishchoure** [comment]
@LindsayThomas 

We are not able to reproduce the issue at our end. We tried adding vector layer in the web map and the application was working without any console errors.

However, the legend widget in crowd source reporter is not showing the vector layer. To double check the behavior we created a sample application with legend widget and we found a same behavior as reporter.

Could you please share the web map or application where the issue is reproducible. The above app link is not working.

**Comment by LindsayThomas** [comment]
@aparveen can you take a look at this?

**Comment by aparveen** [comment]
@LindsayThomas I have the same findings as @ashishchoure, I didn't get any console error in reporter, but the Legend widget is not showing vector layer and same behavior noticed when created a WAB app with Legend widget, so it is not specific to Reporter.

![image](https://user-images.githubusercontent.com/10148401/55987520-92b83780-5c56-11e9-8aa4-ebfd370761e2.png)

**Comment by LindsayThomas** [comment]
@aparveen This seems like it is an issue not specific to our apps. 
@ashishchoure We will take a look.

**Comment by aparveen** [comment]
Vector layer is not supported in 3.x Javascript api Legend Class 

![image](https://user-images.githubusercontent.com/10148401/56693881-56df9200-669a-11e9-9238-a904320cc472.png)
