### ISSUE TITLE
BUG-000119488 In the Crowdsource Reporter template, setting Application Logo with a large width causes unexpected application layout issues. 

### ISSUE THREAD

**Issue by shoe913** [Esri/crowdsource-reporter#416]
<div><div><p>Test data:</p>

<p>Crowdsource Reporter app - Crowdsource Reporter Logo Issue</p>

<p>https://ess.maps.arcgis.com/home/webmap/configureApp.html?appid=3882928fd00e48078a0110654eb65a02</p>

<p> </p>

<p>Contained in app - </p>

<p>- Group &gt; 12cb603bf1ca44078536a85157292bbb</p>

<p>- Web map &gt; 9f7bf00298e749889157de4c09a9dff0</p>

<p>- Feature Service &gt; c60af2e7b94e4d899e28c901e5654483</p>

<p>- Logo &gt; 56de8aa75b944dd9b758999e9591bc86</p>

<p>https://ess.maps.arcgis.com/sharing/rest/content/items/56de8aa75b944dd9b758999e9591bc86/data</p>

<p> </p>

<p>Issue was noticed after December update to ArcGIS Online</p>

<p> </p>

<p>1. Open the test app in Configuration mode</p>

<p> </p>

<p>2. Theme tab &gt; Application Logo &gt; enter url of test logo, which has width of 150px &gt; Save and Launch</p>

<p> </p>

<p>3. Proceed as Guest into app &gt; Layout of the app shows issues:</p>

<p>- Link in upper right corner for Sign in and Help no longer work</p>

<p>- Button in lower right to Submit a Report is hidden</p>

<p>- with some logos that have larger width, the title of the app will move to the next line, under the logo. See user&#39;s logo (attached) to replicate. </p>

<p> </p>

<p>When hovering over the setting for Application Logo, the hint says &quot;Logo displays in top left corner of application. Image should be 48px tall.&quot; If there are limiations on width, please consider updating this hint.</p></div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/sftriage?sfid=BUG-000119488">BUG-000119488</a></span><br/>
<span><b>Salesforce Submitter:</b> Cheryl Hagevik</span><br/>
<span><b>Salesforce Submit Date:</b> 1/18/2019 11:51 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000119488</span><br/>
<span><b>Work Around:</b> <p>Use a logo with a small width, such as 105px.</p></span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 6.4</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by shoe913** [comment]
2565

**Comment by aparveen** [comment]
In this kind of situation where image logo width is too long, crop the image lengthwise so that sign in and help button function properly.

**Comment by ashishchoure** [comment]
@aparveen 

We are not able to reproduce the issue at our end. Could you please share the logo image and application URL? This will help us to trace down the issue. 

Here is the screenshot : 

We tried adding logo image with width as `1280px `and `150px`. But with both the diemsions the application was working as expected.

![image](https://user-images.githubusercontent.com/5525972/52944002-71447900-3394-11e9-9e4e-494101207c8d.png)

**Comment by aparveen** [comment]
@ashishchoure I was able to repro this issue, here is the link of the app https://www.arcgis.com/apps/CrowdsourceReporter/index.html?appid=2545d6f7d817445f81431a5b12fad2a9 and the logo image I used in the app.
[esrilogo.zip](https://github.com/Esri/crowdsource-reporter/files/2881346/esrilogo.zip)

**Comment by LindsayThomas** [comment]
@ashishchoure @aparveen we are removing this issue from the 7.2 milestone.

**Comment by cchang-com** [comment]
This only happens when you have the share option enable.  If you disable the share options, it will function properly.

![image](https://user-images.githubusercontent.com/52260003/60373567-7904d180-99b5-11e9-9d7d-5eed1c652485.png)

Will ESRI fix the share option problem?

**Comment by aparveen** [comment]
Verified in devext,

**Comment by aparveen** [comment]
> This only happens when you have the share option enable. If you disable the share options, it will function properly.
> 
> ![image](https://user-images.githubusercontent.com/52260003/60373567-7904d180-99b5-11e9-9d7d-5eed1c652485.png)
> 
> Will ESRI fix the share option problem?

@cchang-com yes, the fix should resolved the share option issue as well.

**Comment by cchang-com** [comment]
Awesome! Thanks for the reply @aparveen.
