### ISSUE TITLE
Initial search radius‎

### ISSUE THREAD

**Issue by kubaszostak** [Esri/crowdsource-reporter#417]
If one leaves "Initial search radius" empty application hangs up with _TypeError: Cannot read property 'getExtent' of null_. It would be great to have ability to set  "Initial search radius" empty which will have the same behavior as denying to share their location by user. It shouldn't even check location if this value is empty.

![image](https://user-images.githubusercontent.com/4609437/51789342-2e71f580-2188-11e9-9d16-e4891d93f653.png)

**Comment by allisonmuise** [comment]
@KubaSzostak I am unable to reproduce this TypeError. Where is your application hosted? On your own web server, in your Portal, or in ArcGIS Online?

In December we added a configurable option to the Search Radius section on the Reports tab that will allow you to load the application without asking for the user's location.

**Comment by KubaSzostak** [comment]
You have to enable Geolocation in your browser. Issue raised on ArcGIS Portal 10.6.1 and AGOL. My today's sample on AGOL has still this issue:
https://umgdy.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=db35ecd36baf45298d297eedaa45d06e

Steps to reproduce:
https://youtu.be/LJjSAsJ-6Is

**Comment by allisonmuise** [comment]
@KubaSzostak I can reproduce it now. The trick is to configure the app with a value and then remove that value. 

In the meantime, I suggest configuring a value and then using the option to 'Allow users to access the application without prompting for their location‎'.
