### ISSUE TITLE
Errors thrown when initial search radius is null

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#419]
Repro steps:
1) Configure reporter app and provide an initial search radius.
2) Save the app
3) edit the configuration to remove the configured search radius
4) open the app over https and share your location with the app
5) app will throw typeerror
![2-20-2019 8-49-22 am](https://user-images.githubusercontent.com/2752195/53109674-39514900-34ee-11e9-978f-004d9944d72f.png)

6) edit the configuration to enable the option to 'Allow users to access the application without prompting for their location‎'.
7) open the app over https.
8) the first time i did this i got an error in the console saying a value couldn't be trimmed. I have not been able to reproduce on subsequent loads.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Is there a chance we can get this fixed for 7.1?

cc @aparveen @LindsayThomas 
(related to user-reported issue #417 )

**Comment by sumitzarkar** [comment]
@allisonmuise 

We will look into this and will let you know if we can fix this for 7.1

**Comment by ashishchoure** [comment]
@allisonmuise 

We are able to reproduce the issue at our end. The app fails to create the buffer when **search radius** has a null or EMPTY value.

We can overcome this issue in one of the following ways :
1. We can add a range constraint on  **search radius** parameter(in the configuration panel). This way we can restrict users from entering values less than 0.
2. As per comments the github ticket #417. If the **search radius** is EMPTY/NULL/ or less than 0 we would have to by pass the geo-filtering and load the application as if location is disabled.

Please let us know how would you like to handle this scenario.

**Comment by allisonmuise** [comment]
@ashishchoure Let's go with option 1. Let's add info to the hint text for that parameter directing users to the checkbox that disables the zoom to user's location. (these strings aren't impacted by string freeze)

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is our approach to over the issue: 
1. We have added `0.1` as a minimum search radius because the geometry engine requires minimum  `0.1` feet value to create the valid buffer.
2. To handle the backward compatibility, on application load we will check if configured search radius is EMPTY or less than `0.1`. If yes, then we will load the application without geo-filtering.

This implementation is in testing and we will keep you updated in case of any changes.

**Comment by ashishchoure** [comment]
@allisonmuise 

- While testing the application we have observed that the configuration panel is allowing user to save the value, even when a validation error message is displayed.
- This way user can store the any value which is less than 0.1. However, the application will still work as we have added check for invalid values (In this case the app will ignore the geo-location and will work without geo-filtering).
- Seems to be an issue with configuration panel. Just wanted to keep you updated about this case.

**Comment by allisonmuise** [comment]
@aparveen I believe ashish's note above is related to your observation this morning

**Comment by aparveen** [comment]
@ashishchoure @allisonmuise I reached out to ArcGIS Online team to look at this issue. I will update this issue once I hear from them.

**Comment by aparveen** [comment]
Verified in devext.
