### ISSUE TITLE
Non-Image file attachements not displaying/accessible in Reporter

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#420]
Attachments that are not images are not displaying correctly in reporter. In some cases no thumbnail is displayed at all; in other cases the paperclip thumbnail is displayed but clicking it opens the paperclip png file, not the attached document.

Noticed with PDF files on a customer app. Support bug has not yet been logged, but would like to address this for 7.1 if at all possible.

cc @aparveen @LindsayThomas

**Comment by ashishchoure** [comment]
@allisonmuise 

1. We are able to reproduce the issue where, clicking on non-image attachment causes the paperclip image to open in the new tab.
2. However, we are not able to reproduce the issue of not displaying any thumbnail for non-image attachments. Could you please retest this at your end and if possible share the application URL?

We have fixed the first case at our end and it is a minor fix. We can easily deliver this in 7.1 milestone.

**Comment by allisonmuise** [comment]
@ashishchoure Let's start with the fix for 1. At this point we only have the support analyst's word on 2 and can't reproduce it in-house. Once the support bug is logged we can follow up on it if necessary.

**Comment by allisonmuise** [comment]
cc @aparveen could you test?

**Comment by aparveen** [comment]
Verified in devext.
