### ISSUE TITLE
Search broken in old configs of Crowdsource Reporter

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#421]
Jared Schultz reported this issue to me today for Mosquito Service Request which I was able to reproduce as well as [Vision Zero](http://statelocaltryit.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=7e9142f2d6e043738578a716ecb81b1b). I have fixed it in Mosquito Service Request, but kept the issue in Vision Zero so you could reproduce:

1.	Open the Vision Zero app and login as a guest
2.	Search for an address, the progressor will just spin and no results are returned.

Looking in the browser debugger a console error is being thrown:

![image](https://user-images.githubusercontent.com/6796763/53426623-4ae69500-39b5-11e9-9112-77618fd88d99.png)

If I go to that line is see the following:

![image](https://user-images.githubusercontent.com/6796763/53426644-576aed80-39b5-11e9-86e2-1f60bf15b8ee.png)

When I look at the json of the app, it doesn't have a searchConfig property which seems to be the problem. When I compare to newer configs I see this property specified. Seems this was introduced with #265.

The way I resolved it in Mosquito Service Request was to disable and then re-enable search in the config, this wrote the new json to the app config and search worked properly again. Easy to fix, but concerned there may be users out there with old configs that don't realize their search is broken.
 
FYI @allisonmuise

**Comment by allisonmuise** [comment]
cc @aparveen @LindsayThomas 
Considering the breaking change is 2 years old and hasn't been reported until now, i don't think we need to push to fix this for 7.1. I'll leave it to you guys to decide if you'd like to fit this in to another release.

**Comment by aparveen** [comment]
Verified in devext.
