### ISSUE TITLE
When liking a Problem Report null date fields are being incorrectly set to 12/31/1899

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#423]
To reproduce:

1. In [Citizen Problem Reporter](https://www.arcgis.com/apps/CrowdsourceReporter/index.html?appid=8b7d86d2ffa642ca9a38388d3e4d7a16#) select a submitted (Red) problem report.
2. Like/Vote for that Problem Report
3. In [Citizen Problem Manager ](https://www.arcgis.com/apps/CrowdsourceManager/index.html?appid=85f76202cd134713be282179628471b7), find the problem report and edit it. The Resolution date will report 12/31/1899.

Found through the browser debugger that when you like/vote for a problem report it is passing an empty string rather than null to any date fields that are currently null. This is resulting in the date being set incorrectly. It should be passing null, this is not repro in Manager when you update the record because it is properly passing null.

{
                "geometry": {
                                "x": -9805317.262912065,
                                "y": 5131031.501087517,
                                "spatialReference": {
                                                "wkid": 102100,
                                                "latestWkid": 3857
                                }
                },
                "attributes": {
                                "OBJECTID": 8859,
                                "probid": "",
                                "category": "Animal",
                                "probtype": "Animal Abuse",
                                "details": "test",
                                "pocfullname": "",
                                "pocfirstname": "",
                                "poclastname": "",
                                "pocphone": "",
                                "pocemail": "",
                                "locdesc": "4708 River Dr, Lisle, Illinois, 60532",
                                "publicview": "Yes",
                                "userid": "",
                                "numvotes": 1,
                                "status": "Submitted",
                                "assignedto": "",
                                "resolution": "",
                                "resolutiondt": "",
                                "emailstatus": "",
                                "datesubmitted": 1552418873919
                }
}

@allisonmuise, @LindsayThomas, could we look at this for 7.2?

**Comment by allisonmuise** [comment]
@aparveen @LindsayThomas What do you think about trying to get this bug fix into a patch for 7.1? This is a bug that Omaha reported last week as well. Seems like it should be a minor fix with low impact.

**Comment by aparveen** [comment]
@allisonmuise I am good,

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Could you confirm that this is low LOE and low-risk? Could a fix be delivered by Wednesday?

**Comment by sumitzarkar** [comment]
@allisonmuise @aparveen 

We are analyzing this and will update you soon.

**Comment by aparveen** [comment]
Verified in devext
