### ISSUE TITLE
Adding report on a point layer and viewing the popup throws console error message

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#428]
@aparveen @LindsayThomas 

1. Create an app with point layer. 
2. Add a report
3.  Click on the newly added feature and notice the error message in console: "TypeError: Cannot read property 'symbol' of undefined"

Issue is noticed in older apps and newly created apps.

Sample app: http://www.arcgis.com/apps/CrowdsourceReporter/index.html

![image](https://user-images.githubusercontent.com/3836616/55841468-1e5d8700-5ae4-11e9-9301-087dafd4659b.png)

**Comment by aparveen** [comment]
Verified in devext.
