### ISSUE TITLE
BUG-000118062 Features do not appear on the map on loading in the Crowdsource Reporter app if the user allows the browser to know the user location, and the location is outside the default extent of the web map.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#431]
1. In ArcGIS Online, click Groups. Create a new group.
2. Share a web map that contains data in a different geographic area than where you currently are.
3. In ArcGIS Online, click Content.
4. Create a new web app from a template. Choose the Crowdsource Reporter template.
5. Configure the app to use the group created in step 1. Save the web app.
6. Open the web app in a browser. When the browser prompts you for location access, click Allow.
7. Notice how the application zooms to your location. Click the Home button to zoom to the default extent of the web map.
8. Note how the features in the web map do not appear.

- If you deny location access, the application zooms to the default extent of the web map and features show up as expected.
- If you allow location access and you current location is within the default extent of the map, the features will load.
- Issue occurs in Firefox 63, Chrome 70, IE 11.
- If you allow the browser to use your current location and click the "Load More…" button, the web app will center back on your current location.
- See Fiddler logs attached to case.
- LocationAllowed.saz: Allowed browser to use current location. (Chrome 70)
- LocationBlocked.saz: Blocked browser from using current location. (Chrome 70)
- I have created three web applications to showcase this issue:
- Charlotte:
- https://ess.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=f923f0eedcce4f4d9dfe85d54a383798
- Buffalo:
- https://ess.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=32328f02089b4d4e96402bf797d747be
- Redlands
- https://ess.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=36bd4932b89d490f994cbaf88791b3c3
-

**Comment by aparveen** [comment]
Same issue is seen when the user location is out of map's default extent but the data is in nearby place, [Test app](https://stategovernment.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=992767dc836a40308f1ea6579aea1626)

![image](https://user-images.githubusercontent.com/10148401/59214748-968c0b80-8b6c-11e9-8fa3-b8cc5ef0f1f8.png)

![image](https://user-images.githubusercontent.com/10148401/59214763-9b50bf80-8b6c-11e9-9e9a-91c172beec81.png)

**Comment by aparveen** [comment]
@CTLocalGovTeam Is this behavior expected?

**Comment by ashishchoure** [comment]
@aparveen 

Yes this is expected behavior.

If user location is turned on, the app will go to the user's current location instead of web map extent and will try to fetch the features within the configured buffer distance.

**Comment by aparveen** [comment]
> @aparveen
> 
> Yes this is expected behavior.
> 
> If user location is turned on, the app will go to the user's current location instead of web map extent and will try to fetch the features within the configured buffer distance.

Ok, that makes sense but the problem is it doesn't show any features at all when browse to the map extent,

**Comment by LindsayThomas** [comment]
@ashishchoure 
If the user uses current location then scrolls the map to the map extent the features are not visible. Is that aspect as designed?
(The use case would be: the customer is just outside the city limits and uses current location then pans into the city).

**Comment by ashishchoure** [comment]
@LindsayThomas @aparveen 

Yes this is expected behavior. 
- If user turn on the current location, then he will only see the feature within the configured buffer distance from the current location. He will have to click on "Load More" button for the buffer to expand and fetch other features.
- If user turn off the current location, then he will fetch all the features irrespective of extent.

**Comment by aparveen** [comment]
> @LindsayThomas @aparveen
> 
> Yes this is expected behavior.
> 
> * If user turn on the current location, then he will only see the feature within the configured buffer distance from the current location. He will have to click on "Load More" button for the buffer to expand and fetch other features.
@ashishchoure if the current location is really far apart, it does not load the features at all after clicking Load more multiple times, as for example, my current location is in California but if I have features in Naperville, Illinois, it does not load data. It seems like after a certain extert, Load More does not zoom out, is this expected behavior?

**Comment by ashishchoure** [comment]
@aparveen 

Yes this is expected behavior.

So the logic is return is such way that, If the application is fetching empty results for the 10 consecutive attempts the functionality will stop. User will have to click again on the "Load More" button to resume the functionality.

**Comment by aparveen** [comment]
> @aparveen
> 
> Yes this is expected behavior.
> 
> So the logic is return is such way that, If the application is fetching empty results for the 10 consecutive attempts the functionality will stop. User will have to click again on the "Load More" button to resume the functionality.

Thank you Ashish.

**Comment by aparveen** [comment]
Closing this since this is an expected behavior.
