### ISSUE TITLE
Crowdsource Reporter is not properly formatting search query when layer has an existing filter

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#436]
Steps to reproduce:

1. Open the sample crowdsource reporter application below:
https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=e9aeb8d3b0884b90b050e49cfa54b896#
2. Open the Animal Problems
3. From the search type 'Clinton'
4. There are many suggestions returned that are incorrect, about half way down the list with a name 'Clinton' is shown.

In the Web Map I have configured the layer search for the Full Name field with the operator 'Contains'.

The layer has a filter defined as:
(status = 'In Progress') OR (status = 'Received') OR (status = 'Completed')

When I watch in the browser debugger this is the query being sent:

UPPER(pocfullname) LIKE UPPER ('%Clinton%') AND 1563476889774=1563476889774 AND (status = 'In Progress') OR (status = 'Received') OR (status = 'Completed')

The query should be surrounding the layer filter inside parenthesis so the OR statements aren't evaluated separately, This is how the web map viewer is formatting the query and returns the correct results.

UPPER(pocfullname) LIKE UPPER ('%Clinton%') AND 1563476889774=1563476889774 AND ((status = 'In Progress') OR (status = 'Received') OR (status = 'Completed'))

Related, I am not sure why '1563476889774=1563476889774' is being added to the query, I am not seeing it defined anywhere and seems unnecessary because that will always evaluate to true.

This same issue is not reproducible in Crowdsource Manager:
https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=f858863d015c4830bcf69862e9d38e16

@aparveen, @LindsayThomas

**Comment by aparveen** [comment]
@CTLocalGovTeam could you please investigate the level of effort on this issue?

**Comment by ashishchoure** [comment]
@aparveen 

We will look into this issue at update you at the earliest.

**Comment by ashishchoure** [comment]
@aparveen 

We went through this issue and here is our findings :
> UPPER(pocfullname) LIKE UPPER ('%Clinton%') AND 1563476889774=1563476889774 AND ((status = 'In Progress') OR (status = 'Received') OR (status = 'Completed'))
- We made the suggested change by adding the brackets and found the result where more precise and accurate. 

> Related, I am not sure why '1563476889774=1563476889774' is being added to the query, I am not seeing it defined anywhere and seems unnecessary because that will always evaluate to true.
- The true condition here is nothing but the current date. This makes the query unique and ensures the accurate results. We add this to the query because we have faced issue where the result of query where getting fetched from cache.

Just to add more information,
- The search dijit in the crowdsource reporter is custom implementation and it is different from the map viewer search.

- The reporter search dijit will show all the results fetched from world geocoder and the selected layer if layer search is enabled.

This implementation is low LOE and it will be available in upcoming code drop.

**Comment by aparveen** [comment]
> > UPPER(pocfullname) LIKE UPPER ('%Clinton%') AND 1563476889774=1563476889774 AND ((status = 'In Progress') OR (status = 'Received') OR (status = 'Completed'))
> 
> * We made the suggested changes by adding the brackets and found the result where more precise and accurate.
> 
> > Related, I am not sure why '1563476889774=1563476889774' is being added to the query, I am not seeing it defined anywhere and seems unnecessary because that will always evaluate to true.
> 
> * The true condition here is nothing but the current date. This makes the query unique and ensures the accurate results. We add this to the query because we have faced issue where the result of query where getting fetched from cache when the same query was fired multiple times.
> 
> Just to add more information,
> 
> * The search dijit in the crowdsource reporter is custom implementation and it is different from the map viewer search.
> * The reporter search dijit will show all the results fetched from world geocoder and the selected layer if layer search is enabled.
> 
> This implementation is low LOE and it will be available in upcoming code drop.

@chris-fox does this solution works for you?

**Comment by chris-fox** [comment]
Sounds good to me.

**Comment by aparveen** [comment]
@ashishchoure the search is showing correct suggestions now but it is not honoring Reporter app config for search, I have an app that has ArcGIS Geocoder disabled in the config and the web map has layer search configured but it still shows the suggestion from the gecoder. Could you please take a look at this?

![image](https://user-images.githubusercontent.com/10148401/62318406-a9c2a580-b450-11e9-9a8d-fef2edf8b128.png)

**Comment by ashishchoure** [comment]
@aparveen 

- As per the current implementation, If no geocoders are configured in the configuration panel then the application picks the default geocoder from the helper services (Usually this will be the world geocoder).
- Once this is done then app looks if the layer search is enabled.

This is the reason you are seeing the world geocoder results.
However, you should also see the layer search results after the world geocoder results incase of valid search text.

**Comment by aparveen** [comment]
> @aparveen
> 
> * As per the current implementation, If no geocoders are configured in the configuration panel then the application picks the default geocoder from the helper services (Usually this will be the world geocoder).
> * Once this is done then app looks if the layer search is enabled.
> 
> This is the reason you are seeing the world geocoder results.
> However, you should also see the layer search results after the world geocoder results incase of valid search text.

@ashishchoure I could see the layer search result at the bottom, but the application Chris shared shows only layer search result and not showing any geocoder result. 

![image](https://user-images.githubusercontent.com/10148401/62395644-c381ec80-b525-11e9-9c3c-9f95f6cb9942.png)

**Comment by ashishchoure** [comment]
@aparveen 

Could you please share the application link? This will help us in understanding the scenario.

**Comment by aparveen** [comment]
https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=e9aeb8d3b0884b90b050e49cfa54b896#

**Comment by ashishchoure** [comment]
@aparveen 

Thank you for sharing the link.
- Seems like the above link doesn't have the latest code. 
- In shared application, search tool is enabled but no geocoder's are configured in the application. This is the reason you are seeing only the layer search result.
- As per the latest code delivered , if search tool is enabled and no geocoder's are configured in the application then app will use the default geocoder from organization. So, the search will show geocoder + layer search results.

**Comment by chris-fox** [comment]
@aparveen, @ashishchoure, I can say that for Omaha, they don't want to use a geocoder to search for addresses, they only want to search for features which is why they configured it that way. IMO, we shouldn't automatically use the org's geocoder if they have intentionally disabled it in the reporter app.

**Comment by aparveen** [comment]
@ashishchoure as Chris said, if the geocoder is intentionally disabled we should honor that parameter and not use the default geocoder from the org, could you please revert the code back. Thanks.

**Comment by ashishchoure** [comment]
@aparveen 

- We are always falling back to the default geocoder because it makes sure that search widget will always show the results (Even though it will be from the world geocoder).
- Consider a scenario where the geocoder is intentionally disabled and no layer inside the webmap is search enabled. So, the search widget inside the application will not have any source to fetch the address based on user input and the widget will always show a message "No result found".
![image](https://user-images.githubusercontent.com/5525972/62622005-e869cb80-b93a-11e9-95e9-6f2d784c586f.png)

Possible solution : 
- If the geocoder is disabled in the configuration and no layers in the web map are search enabled then only we will fall back to the default geocoder.

Please let us know if this makes sense or we can discuss this in detail.

**Comment by aparveen** [comment]
@chris-fox are you ok with this solution?

**Comment by chris-fox** [comment]
@aparveen, IMO I don't understand why we are changing the behavior of something we have received no complaints about. It just introduces unnecessary risk and another scenario we need to test. Everything described here would require the user take deliberate action in order to 'break' the search and could easily be resolved by them if they wanted to use a geocoder to search.

My preference would be to just fix the bug as stated in this issue and not add any additional logic to the behavior of the search widget.

**Comment by aparveen** [comment]
@ashishchoure is there any reason you for changing this behavior? We would like to keep the existing behavior in production by just fixing this bug.

**Comment by aparveen** [comment]
Search widget is working as expected and showing only feature layer search results when geocoder is disabled and layer search is enabled, Verified in devext.
