### ISSUE TITLE
Long user name causes Submit Report button to be pushed off the bottom of the browser window

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#443]
1. Create or edit your arcgis user name to be longer than 30 characters
2. Login into Crowdsource Reporter with your arcgis user

In the screenshot below you will see the application header is much larger with the app name and logo on the top line and the user on the second line. This causes the Submit Report button to be pushed off the bottom of the page.

![image](https://user-images.githubusercontent.com/6796763/63775312-104eae00-c8ad-11e9-8342-342f6d294428.png)

**Comment by ashishchoure** [comment]
@allisonmuise 

We are not able to reproduce the issue at our end.
![CSR_ISSUE_2](https://user-images.githubusercontent.com/5525972/65968650-1d992280-e481-11e9-8d5e-924af0fac193.gif)

However, for sometime the username do come down but then app adjust the header width and username gets adjusted in the UI.

Please let us know if we are missing anything at our end.

**Comment by allisonmuise** [comment]
@chris-fox can you share any more info that might help with a repro? screen size? length of name?

**Comment by chris-fox** [comment]
My screen resolution is 2560x1440, but if I shrink it down I see the same issue. In the original repro I said over 30 characters. You should be able to repro, change your user profile name for your try-it-live user and then login into the try-it-live version of Problem Reporter:

![image](https://user-images.githubusercontent.com/6796763/65973800-eb180700-e439-11e9-85cc-9cba5bb92a3c.png)

**Comment by ashishchoure** [comment]
@chris-fox

- Are you testing this functionality on the latest code?

**Comment by chris-fox** [comment]
No I am not, i am testing against production arcgis online

**Comment by chris-fox** [comment]
I attempted to repro today after the online release and can no longer reproduce:

![image](https://user-images.githubusercontent.com/6796763/66046884-ac935280-e4f4-11e9-8e64-10636bbb4eee.png)
