### ISSUE TITLE
BUG-000122326 The Location box in the Crowdsource Reporter app geocodes addresses incorrectly if the projection of the basemap is other than 4326.

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#447]
<div><div><ol><li><span style="font-size: 12pt;">Publish a map service with some data for a NAD 1983 projection. </span></li><li><span style="font-size: 12pt;">Publish a point feature service with data in the same projection as Point (1)</span></li><li><span style="font-size: 12pt;">Add the map service as a basemap to a web map and add the feature service as well. </span></li><li><span style="font-size: 12pt;">Save the web map and share this web map to a group. </span></li><li><span style="font-size: 12pt;">Create the Crowdsource Reporter App from this group. </span></li><li><span style="font-size: 12pt;">While configuring the app, in the Search column, use the ArcGIS Would Geocoding service and have the &quot;Enable search tool&quot; checked on. </span></li><li><span style="font-size: 12pt;">Save the app and launch it. </span></li><li><span style="font-size: 12pt;">Select the web map and click on Submit Report. </span></li><li><span style="font-size: 12pt;">Launch the developer tools and place a point on the map where you want to place the data </span></li><li><span style="font-size: 12pt;">Click on the reverse geocode request that passes in the developer tools. You will see that the wkid is still 4326 which would be WGS instead of the wkid for NAD.</span></li></ol>

<p><span style="font-size: 12pt;">This is reproducible with Portal for ArcGIS 10.7. Data to reproduce the issue is attached. <br>For map service published the feature class can be published from the zip file. For feature service you can export the XML in the geodatabase and publish.</span></p></div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/sftriage?sfid=BUG-000122326">BUG-000122326</a></span><br/>
<span><b>Salesforce Submitter:</b> Nerrissa Pinto</span><br/>
<span><b>Salesforce Submit Date:</b> 5/10/2019 3:50 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> Portal for ArcGIS</span><br/>
<span><b>Functional Category:</b> Portal Core</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.6.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by allisonmuise** [comment]
3146

**Comment by allisonmuise** [comment]
@ashishchoure 
I'm still seeing 4326 as the WKID. I'm wondering if this has to do with the spatial reference of the geocode service, or if this is still not working correctly?
![image](https://user-images.githubusercontent.com/2752195/68629896-4a861f80-049a-11ea-8316-463265ab6f7b.png)

**Comment by ashishchoure** [comment]
@allisonmuise 

- Yes this is correct. We try to project the geometry into geocoder's spatial reference to get the exact result. This is the reason you are seeing spatial reference of the geocode service.
- We tested this implementation and it was working as expected. Please let us know if you are seeing any unexpected behavior.

**Comment by allisonmuise** [comment]
looks good to me! Thanks for confirming.
