### ISSUE TITLE
Console error when configuring the app

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#450]
In Production and QA, configuring a reporter app throws an error. App configuration is honored and no error when the app is launched

![image](https://user-images.githubusercontent.com/3836616/65064638-b7b38380-d935-11e9-88b9-3bb0be042a72.png)

**Comment by ashishchoure** [comment]
@skrishn 

Please let us know if any further action is required from our side.

**Comment by skrishn** [comment]
cc @allisonmuise
