### ISSUE TITLE
remove social media info from details page

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#455]
Template details page still references facebook and google

**Comment by allisonmuise** [comment]
no items build for 8.1 due to build script failures. update will need to be made at 8.2

**Comment by aparveen** [comment]
Sent an email to Ian to fix this issue. https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/3772

**Comment by aparveen** [comment]
This issue is fixed https://www.arcgis.com/home/item.html?id=74b016cef7db42b28599adc5a14b010c
