### ISSUE TITLE
Send email back to user when a problem has been resolved\ completed

### ISSUE THREAD

**Issue by cchang-com** [Esri/crowdsource-reporter#461]
For the Citizen Problem Reporter on AGOL.  Is it possible to have an option to send a user a reply that their problem has been resolved?  If the user has a valid email address?

Thanks

**Comment by allisonmuise** [comment]
@cchang-com see the documentation here: https://solutions.arcgis.com/local-government/help/citizen-problem-reporter/get-started/email-notification/
