### ISSUE TITLE
BUG-000128328 A layer containing either a default value or hint in a pop-up defaults to a light gray text in the Crowdsource Reporter app, which cannot be changed.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#470]
- Configure an editable feature layer in ArcGIS Online, and add it to a web map
- Either add a hint in the web map pop-up, or add a default value
- Share web map with desired group
- In Crowdsource Reporter application, select group
- In Theme tab, configure Body background color to color other than default
- ie) dark green
- Save & Launch application
- Select Submit New Report > Note that it is difficult to read text

![image](https://user-images.githubusercontent.com/10148401/86065573-c67ea900-ba24-11ea-9f83-336b98c5b838.png)

**Comment by aparveen** [comment]
@CTLocalGovTeam please use this app https://stategovernment.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=992767dc836a40308f1ea6579aea1626, the one Support shared is not working. FYI @skrishn

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

As per our discussion, 
- We will change the hint text color same as the Field label color. So as per the above screen shot, hint text will be displayed in white color.
- Regarding the default value case, this is behavior of bootstrap classes. If the input has a valid value the field label will be displayed in green color and for the invalid values it will be displayed in red color. We will not touch the behavior.

**Comment by skrishn** [comment]
verified in dev

**Comment by skrishn** [comment]
verified in qa
