### ISSUE TITLE
BUG-000127193 In the Crowdsource Reporter app in ArcGIS Online, the location search results are not visible as the default body text color is white

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#471]
**Preparing the Data**

- Configure a feature layer with editing enabled.
- Add the feature layer to the map viewer and save the web map.
- Share the feature layer and web map with an ArcGIS Online Group.

**Creating the CrowdSource Reporter Template**

- In ArcGIS Online navigate to the Content Pane.
- Click the 'Create+' button> under App click 'Using a Template'> select CrowdSource Reporter> and click 'CREATE WEB APP'
- Add a title and tags, summary is optional, then click ok.
- The configuration page for the web app will then launch.

**Configuring the CrowdSource Reporter Template**

- When the configuration page has launched, the General tab automatically opens first.
- Click 'Select Group' and choose the group you shared the content with.
- Under the Theme tab ensure that the 'Body Text Color' is set to the default, which should be white.
- Leave all other default settings for the application.
- Click Save and then click launch.
- A new window will open in your browser

**The behavior of the Defect**
**This is reproducible whether you select 'Proceed as Guest' or sign in to your ArcGIS Online Account**

- Once you have chosen to sign in or proceed as guest, click 'Submit a Report' in the bottom right-hand corner.
- Scroll down to 'Location' and type in an address. 
- Click the "+" next to "Address: ArcGIS World Geocoding Service (2)"
- Although the box expands you cannot see the results because the text is white. Attached image for clarification of results.
- Unfortunately using white for the question headers results in this behavior, making it unusable to use white headers for questions.

![image](https://user-images.githubusercontent.com/10148401/86066556-50c80c80-ba27-11ea-8d72-533d72ebceb3.png)

**Comment by ashishchoure** [comment]
@aparveen @skrishn 

We will change the search results color to the same as its parent section l.e geocoder name div.

![image](https://user-images.githubusercontent.com/5525972/88622655-e0151e00-d0c0-11ea-8a5b-01918d998458.png)

**Comment by skrishn** [comment]
verified in devext

**Comment by skrishn** [comment]
verified in qa
