### ISSUE TITLE
Update Reporter Shield page so that the page looks good in both desktop and mobile devices

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#496]
Find way to make the shield page look better in desktop

![image](https://user-images.githubusercontent.com/10148401/106678138-eeac2880-656e-11eb-9d9f-b1366e376b15.png)

Few options to think
1) Add a high resolution image that covers the full desktop screen
2) May be use 2 different images, one for desktop, one for mobile devices

**Comment by ashishchoure** [comment]
As discussed on the call here are the options to implement this change: 

Option 1: 
- We will change the existing image to a high-resolution image.
- In addition to the above point, we have to update the CSS to allow the image to use the entire space available. (CSS property : `background-size: cover`)
- If we go with Option 1, then existing users who are using the low-resolution image will see the stretched version of a configured image on the landing page.

Option 2:
- We will change the existing image to a high-resolution image.
- To allow users to choose if they want to see the full-screen image, we can add a configurable parameter.
- The value will be set to false by default. This will make sure the existing users are not seeing any difference once they are on the landing page.
- If this flag value is set to true, then only the user will see the changes once they are on the landing page where the image will use the entire available space.


Please let us know your thoughts.

**Comment by aparveen** [comment]
@ashishchoure few questions
1) Is the current image provided by esri? Also, do you have this full image in high resolution?
2) Will this change have any impact on mobile devices, such as long loading times.
3) Could you please provide us with a few screenshots on how it will look like in desktop and mobile devices?

**Comment by aparveen** [comment]
@ashishchoure 
The way we would like to achieve this :
•	Adding a parameter to the app which will not be exposed to the users. 
•	New apps will see the high-resolution full screen image background as default 
•	but the existing users who configured their own image will not see any difference ( their image won’t be stretched out)

**Comment by ashishchoure** [comment]
@aparveen 

Thank you for the detailed information. We will consider all of the above points while implementation.

**Comment by ashishchoure** [comment]
@aparveen 
As per our discussion, 
- We will not add any configuration parameter for this functionality.
- Instead, we will replace the new image with the old one. This way new user's will always see the updated image on the landing page.
- For the existing user's we will check if the image is being updated,  
    - If yes, then we will keep the image as is and the image will not be streched
    - If no, the new image will be shown and it will occupy the entire screen

Please let us know your thoughts.

**Comment by ashishchoure** [comment]
### Dev Checklist
Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS change?​ | No | NA | ​
Required Backward compatibility​? | No | NA |  
Required 508​? | No | NA |  
Need Sanitize?​ | No | NA

### Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Sign In Page | **New Application :**  <li>The new sign image should be displayed and it should occupy the entire available space</li>**Existing Application :** <li>If the user has not updated the image, then new  image should be displayed and it should occupy the entire available space</li><li>If the user has updated the image, then the same image should be displayed and the image should not be stretched </li>

**Comment by ashishchoure** [comment]
@aparveen 

This is how the landing page looks after using the above image.

![image](https://user-images.githubusercontent.com/5525972/116707445-4e8a6200-a9ec-11eb-9651-b3fa17e99b34.png)

**Comment by aparveen** [comment]
[Reporterbg_NCY_Darker.zip](https://github.com/Esri/crowdsource-reporter/files/6435160/Reporterbg_NCY_Darker.zip)
@ashishchoure here is the png version of the image

**Comment by aparveen** [comment]
@ashishchoure in old apps I am seeing the background image is being stretched during local testing, could you please take a look at it?
![image](https://user-images.githubusercontent.com/10148401/118513265-65b59900-b6e8-11eb-8ecf-bbe3ae2faead.png)

**Comment by aparveen** [comment]
verified in qa
