### ISSUE TITLE
Handle the Reporter signout in the AGOL recommended way

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#498]
We need to implement the sign out functionality in AGOL recommended way.
![image](https://user-images.githubusercontent.com/10148401/109044636-79bca200-7687-11eb-9d58-3dd3ff64f3ce.png)

**Comment by aparveen** [comment]
![image](https://user-images.githubusercontent.com/10148401/109044749-a375c900-7687-11eb-9eb1-9daf2900e640.png)
Also here is an example
![image](https://user-images.githubusercontent.com/10148401/109045133-13844f00-7688-11eb-8809-06030998412b.png)

**Comment by ashishchoure** [comment]
@aparveen 

As discussed,
- Could you please share any of the web app templates which already use the above sing-out mechanism. 
- This will be of great help and we can make sure that we are not missing on any of the sceanrios.

**Comment by aparveen** [comment]
@ashishchoure @CTLocalGovTeam Here is some example of implementing oauth signout with client id.
1) We would like to preserve the current behavior of signout, that means if any user signs out from reporter tab, they won't be signout from all other tabs logged in to the same org.
2) Same is for redirect url, we would like to preserve the current behavior.

**Comment by ashishchoure** [comment]
@aparveen 

Thank you for sharing the details.

We followed the sign-out approach as per the shared details and here are our observations :

**1. Redirecting application to the base URL:** 
   - The sign-out `redirect_uri` parameter works only when the application is being hosted in ArcGIS online platform (Tested this by injecting the new code in the production app and after sign out the app was redirecting to the landing page).
   - If we run the locally hosted app, then the application is being not redirected to the intended URL and we see the sign-out page. (Refer screenshot)
![image](https://user-images.githubusercontent.com/5525972/113665616-61e72d80-96cb-11eb-9e63-9c7464255585.png)
   - Do we need to check if the application is being hosted on ArcGIS online once the user clicks on the sign-out button? Or are we missing anything from our side?

**2. OAuth sign out:**  
   - Once we hit the OAuth sign out URL through the application, all the sessions in other tabs also getting signed out.
   - Looks like the default behavior. Just wanted to let you know about this behavior.


**3 Application hosted on Portal** 
   - Looks like the OAuth sign-out rest end does not exist for the portal.
   - How do you want us to handle the sign-out functionality for the applications which are hosted on the portal?

**Comment by aparveen** [comment]
> * If we run the locally hosted app, then the application is being not redirected to the intended URL and we see the sign-out page. (Refer screenshot)

@ashishchoure is this the current behavior as well?

**Comment by ashishchoure** [comment]
> > * If we run the locally hosted app, then the application is being not redirected to the intended URL and we see the sign-out page. (Refer screenshot)
> 
> @ashishchoure is this the current behavior as well?

@aparveen 
As per the current implementation we never use redirect url, instead we just reload the application once user clicks on sign out.

**Comment by aparveen** [comment]
> As per the current implementation we never use redirect url, instead we just reload the application once user clicks on sign out.

oh ok, let me talk to Ryan and will update the issue.

**Comment by ashishchoure** [comment]
### Dev Checklist

Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS change?​ | No | NA | ​
Required Backward compatibility​? | No | NA |  
Required 508​? | No | NA | 
Need Sanitize?​ | No | NA | ​

### Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Sign out functionality | <li> On click of sign out, the user should be signed out from the application, and the user should be redirected to the application landing page</li>

**Comment by aparveen** [comment]
@ashishchoure the code is in devext now, but sign out is still failing with console error.
![image](https://user-images.githubusercontent.com/10148401/117501603-1f677980-af33-11eb-973f-9972ccc05c11.png)

**Comment by ashishchoure** [comment]
@aparveen 

Thank you for the update.
We will have a look at it and update you at the earliest.

**Comment by aparveen** [comment]
verified in qa
