### ISSUE TITLE
Support cascading select (Dropdown filters options in related dropdown)

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#510]
![image](https://user-images.githubusercontent.com/10148401/132562773-df87f99b-f7b7-444d-83b3-8c49db77dc9c.png)
![image](https://user-images.githubusercontent.com/10148401/132562799-c478d551-169b-4dac-9439-d826b48432bc.png)
![image](https://user-images.githubusercontent.com/10148401/132562876-6fb720f9-5300-4c95-a13c-b0414fe6ba8a.png)
![image](https://user-images.githubusercontent.com/10148401/132562947-150e1715-9c18-4edf-8380-899c848465d8.png)
![image](https://user-images.githubusercontent.com/10148401/132562994-e1ee2290-169b-4d5c-a101-1eb0965b016c.png)

**Comment by sumitzarkar** [comment]
@aparveen @skrishn @chris-fox 

 

We checked this enhancement and on analyzing this we have the following observations:
- If the layer has subtypes defined in the layer definition then this enhancement will work with the field defined for subtypes
- As mentioned above, this enhancement should be not limited to the hard-coded domain, then we need to do the following changes:
   - In the configuration, we need to provide a mapping source field with target fields and their value
      - For instance, Textbox for source field name, a textbox for source field value, a textbox for the target field name, and another textbox for its value (as shown below)
      - Also, the user has to create the above combination for all the values of the source field
   - With the template app config limitations, all the values will be static i.e. number of fields and text boxes will be limited for value and for the number of target fields

 

The below image is the example for specifying only 1 value mapping, this group will be repeated for the combinations of values i.e. if there are 3 users for the name field then a total of 3 groups have to be added
![image](https://user-images.githubusercontent.com/22743029/136927409-bd683a96-d27f-43ec-99d2-8dfd048b3ab2.png)

As discussed on the call yesterday, the forms in Reporter apps are based on GeoForm and it is dependent on the Feature Layer. So adding such enhancement in the report app will have a major impact on core code.

**Comment by aparveen** [comment]
@ashutoshverma-ct could you please change the strings to
1) Import choice list for cascading select
2) Autocomplete field information
3) autocomplete
4) First name
5) Last name
6) Email
![image](https://user-images.githubusercontent.com/10148401/139700170-78ae2e09-155e-4706-a686-9f19ccd3c440.png)

**Comment by aparveen** [comment]
@ashutoshverma-ct instead of autocomplete please use autofill as you suggested previously. Thanks

**Comment by ashutoshverma-ct** [comment]
@aparveen @skrishn @chris-fox 

We are clear with the string changes except for points 2 and 3. Just be on the same page, we understood from above as follows:

- For point 2: The new string will be "Autocomplete field information". Here we do not need to replace "autocomplete" with the "autofill" word.
- For point 3: The new string will be "Autocomplete" only

Please confirm

**Comment by aparveen** [comment]
@ashutoshverma-ct all autocomplete should be replaced by autofill.

**Comment by aparveen** [comment]
Test case? @skrishn

**Comment by aparveen** [comment]
@sumitzarkar I noticed that csv file needs to be shared publicly to be able to get url for that item, wondering for the users who wants to use the cascading select within the org, how they are going to access the csv?

**Comment by sumitzarkar** [comment]
@aparveen 

We tried different scenarios and here are the details of our alaysis:

### CSV URL will work for the following scenarios only:

- If the URL is public and accessible for all using the link

- If the CSV is secured and its domain is same as the logged in user (same AGOL org for hosting CSV and logged in user)



### Application will not able be to access the CSV data if:

- CSV is private or needs credentials to access item (Securely hosted CSV data using any custom domain. for e.g CSV shared from Sharepoint which is secured )

- CSV URL is from different AGOL organization than the logged in users organization

**Comment by skrishn** [comment]
verified in qa
