### ISSUE TITLE
Auto fill user info if logged in

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#512]
•	If a user is logged in, we can query information from the user like first name, last name, and e-mail.
•	This enhancement would allow us to configure fields in the report form and comment form to auto populate with this information from the user.
•	Note in the screenshot, Phone Number is not a property on the portal user so it can’t be autopopulated.
![image](https://user-images.githubusercontent.com/10148401/132566491-5e88b349-2ecd-4e58-8c08-c6a36f11e8b4.png)

**Comment by aparveen** [comment]
@CTLocalGovTeam could you please assess this for 9.4 release? Thanks

**Comment by ashutoshverma-ct** [comment]
@aparveen 

We understood the requirements of this enhancement but we need some more information:



> If a user is logged in, we can query information from the user like first name, last name, and e-mail.

Q1. For a logged-in user we get several values (attached as a text file), do we have to honor only first name, last name, and e-mail?

> • This enhancement would allow us to configure fields in the report form and comment form to auto populate with this information from the user.

Q2. To auto-populate, the fields with the logged-in user, do we have to match the exact field names with the portal user properties? For instance, we get "fullName" from portal user as a property so its value should be auto-populate to the field in the report with the same name and not with the field "name"

Q3. Should we match with the displayed field name (alias) of the report only or with the actual field name too?

**Comment by skrishn** [comment]
@ashutoshverma-ct 
Q1 - Yes. you're correct.
Q2 - We expose this in the config panel so that users choose how the fields are matched. 
Q3 - Do we expose alias and actual field name in the config for any other parameter in this app? Please confirm what we do.  I'd suggest we use the same pattern we did for other parameters

Let me know if you have additional questions. 

cc @aparveen

**Comment by ashutoshverma-ct** [comment]
@aparveen  @skrishn 

As discussed in the meeting, the workflow will be as follows:
- In the configuration, we will provide 3 textboxes to specify field name to auto-populate user info (i.e. first name, last name and email id) 
   - User should be able to specify only 1 field name
- If the specified field name is not found in the feature layer then the value will not be auto-populate
- Data type validation and length truncation will be handled
- All the auto-populated fields will remain editable for the users to edit the value

**Comment by aparveen** [comment]
Test case? @skrishn

**Comment by aparveen** [comment]
@CTLocalGovTeam What will be the level of effort to apply this to comment table? In our solution schema, related comment table and feature layer has the same field names for these fields.
It will help simplify editing experience for our users. 
Could you please evaluate this and see if it can be done in 9.4?

**Comment by sumitzarkar** [comment]
@aparveen 

We can add this functionality to the comment forms as well, this would need low level of efforts.
We have implemented this functionality today and currently we are testing it. We will deliver this once our testing is completed.

**Comment by aparveen** [comment]
@sumitzarkar Thanks so much for your quick action on this, appreciate it.

**Comment by skrishn** [comment]
verified in qa
