### ISSUE TITLE
Uncaught TypeError reading 'showDialog'

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#513]
I have the help option disabled and I noticed a console error on this app.

Error:
![image](https://user-images.githubusercontent.com/3836616/133532434-edd906ae-3ef4-4b62-ac73-3ed8c9ccf842.png)

https://localgovqa.mapsqa.arcgis.com/apps/CrowdsourceReporter/index.html?appid=31bdc370c3114adea7628d7c7a6f0a81

**Comment by sumitzarkar** [comment]
@skrishn 

In the configuration help is disabled but showHelpOnload is true which is causing this issue

![image](https://user-images.githubusercontent.com/9443956/133726780-53a68f28-34fe-4d74-a651-6c5bb6f9b806.png)


On Load application checks if showHelpOnload  is true it shows the help dialog but in this case help is not enabled.

**Comment by skrishn** [comment]
@sumitzarkar : Thanks for looking into this. Let's fix this for 9.4

cc @aparveen

**Comment by skrishn** [comment]
verified in qa
