### ISSUE TITLE
BUG-000140776 Reverse geocoding operation executes on the World Geocoding Service instead of a custom locator in the Crowdsource Reporter web application when selecting a location in the web map

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#523]
1) Create a Crowdsource Reporter configurable web application in ArcGIS Online (e.g. https://ess.maps.arcgis.com/home/item.html?id=90200dfb726a4a848948301cdf25ffd2).

2) Create a hosted feature layer in ArcGIS Online (e.g. https://ess.maps.arcgis.com/home/item.html?id=ca8309ad87bd4d7e8c5b424ec2b1e816).

3) Enable editing on the hosted feature layer, add one editable field to the hosted feature layer, and add the layer to a web map.

4) Save the web map (e.g. https://ess.maps.arcgis.com/home/item.html?id=0fc07f11bc3f4270babf60455bad4a81).

5) Create a group and the share Crowdsource Reporter map and feature layer with this group per https://solutions.arcgis.com/local-government/help/crowdsource-reporter/get-started/setup-map/ (e.g. https://ess.maps.arcgis.com/home/group.html?id=022a0da73c5b4d4c8b7636c18a1ab5b1#overview).

6) Change the sharing level of the web map, feature layer, and Crowdsource Reporter app to public to allow users to access the app anonymously.

7) Open the Crowdsource Reporter app in configuration mode.

8) Configure the "General" section so that the group created in step (5) is displayed in the application.

9) Configure the "Search" section so that the search tool is enabled and only a custom locator (e.g. https://sampleserver6.arcgisonline.com/arcgis/rest/services/Locators/SanDiego/GeocodeServer) is enabled to be the search source.

10) Save and launch the Crowdsource Reporter app (e.g. https://ess.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=90200dfb726a4a848948301cdf25ffd2).

11) Navigate to an area covered by the custom locator (e.g. San Diego ).

12) Click "Submit a Report".

13) Open Developer Tools > Network tab and clear the log.

14) Click on a location in the area of interest. Observe that the reverse geocode operation executes on the World Geocoding Service in the web traffic (e.g. https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/reverseGeocode?location=%7B%22x%22%3A-117.02113928157931%2C%22y%22%3A32.76728004964593%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&distance=100&f=json).

15) Type the number "'3" into the search box and click the search button. Observe that the forward geocoding is executed on the custom locator in the web traffic (e.g. https://sampleserver6.arcgisonline.com/arcgis/rest/services/Locators/SanDiego/GeocodeServer/findAddressCandidates?SingleLine=3&f=json&outSR=%7B%22wkid%22%3A102100%7D&outFields=*).

Note: Because of BUG-000139934, the search box does not populate with any attributes returned by the reverse geocode operation. However, the search box in the customer's Crowdsource Reporter app (https://gjcitygis.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=53a71834e50b438b82327af159780e62#) does get populated for an unknown reason, but still does not execute the reverse geocode operation on the custom locator configured for search when looking at the web traffic. Because it executes on the World Geocoding Service instead of the custom locator, if a POI is selected as the location, the name of the POI populates the search box instead of its street address (i.e. not what the customer wants). If the customer opens the Crowdsource Reporter app as a signed-in ArcGIS Online user, the reverse geocode operation executes on the custom locator, but the app is intended to be public.

**Comment by aparveen** [comment]
When adding a report and World geocoder is disabled I am getting this I am getting this unable to find address error in the network tab
![image](https://user-images.githubusercontent.com/10148401/144493212-a6aa551e-b3c8-4449-b759-04870c57f553.png)

**Comment by sumitzarkar** [comment]
@aparveen 

- Reverse Geocoding in Report app is designed to use the world geocoding service by default (if no service is configured in org) and if any geocoder is configured in the organization then the first geocoder from the org's geocoeder list will be used
 ![image](https://user-images.githubusercontent.com/9443956/146877149-0ed83b35-ca1c-4989-9415-1d8b39919c82.png)
- So if you want to use any custom geocoder for reverse geocoding that should be configured as the first geocoder in the orgnizations geocoder list
 ![image](https://user-images.githubusercontent.com/9443956/146877987-7f81320b-fd39-4b2b-a6ef-a77f9dd7276c.png)

Please check and let us know on how to proceed with this.

**Comment by sumitzarkar** [comment]
@aparveen 

As discussed on the call no action is required on this from our side
