### ISSUE TITLE
Crowdsource Reporter is not showing any records after the web map is saved in new map viewer

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#526]
Crowdsource Reporter has the same issue as Manager.

To Repro:

1. Deploy Citizen Problem Reporter solution
2. Add a few records using Citizen Problem Reporter app
3. Open manager and notice the records are visible in table and map.
4. Open the Citizen Problem Manager map in new map viewer (not the classic viewer)
5. Save the map and refresh manager app and notice that the records are not visible anymore, no console error either.
6. 
![image](https://user-images.githubusercontent.com/10148401/148412790-035bb56b-90db-41cb-b639-d3ea6e060140.png)

**Comment by aparveen** [comment]
We analyzed this issue and here are our findings:

- This issue is reproducible in both Reporter and Manager app.
- 
- Reporter and Manager app have a WebmapList widget and it filters the webmap and layers based on some conditions like if the layer has capabilities and if the layer is visible or not. Based on such conditions it filters the webmaps to be shown /considered for use in the application.
- 
- We found that whenever any webmap is saved using New Map Viewer it is not adding 'visibility' property and hence the app is considering no layer is visible
- 
- New Map Viewer is only adding 'visibility' property only when it is turned off
- 
- For e.g. We turned off the Birds Observation layer from the New MapViewer
![image](https://user-images.githubusercontent.com/10148401/148413036-8b64a950-26ea-4504-8fd5-962a978c40f6.png)

- However, we found that in the old map viewer we are able to get the 'visibility' property when the layer is turned on/off

**Comment by aparveen** [comment]
@sumitzarkar I couldn't assign you, so assigned it to Ganesh

**Comment by sumitzarkar** [comment]
@aparveen @skrishn 

### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | Yes  |   | ​ Need to check with older Applications if any difference is observed in showing/hiding layers that are turned off /on from the webmap
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime Impacts | Need to test following different cases:<ol><li>WebMap Create/updated with New Mapviewer</li><li>Webmap created/updated with old map viewer</li></ol>

**Comment by aparveen** [comment]
Verified in qa
