### ISSUE TITLE
Custom Vector basemap issue? 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-reporter#528]
Issues: Reporter map won't load when the application is opened. When she clicks on a category, the web map loads as expected. This is happening when using a Custom Vector basemap.

Steps to repro:
-Create a web map

Import this custom basemap into ArcGIS Online > Content > Click "New item" > Select "URL" > Insert the URLs below:
https://tiles.arcgis.com/tiles/B6yKvIZqzuOr0jBR/arcgis/rest/services/Canada_Topographic/VectorTileServer
https://tiles.arcgis.com/tiles/B6yKvIZqzuOr0jBR/arcgis/rest/services/Canada_Hillshade/MapServer
add additional data to the web mep
Create ten additional web maps using the same basemap (create 8 maps or more)
Configure reporter to use all the web maps
Launch app, log in as Guest
Let the map load and the basemap won't fully load
Select any of the maps and it will fully load
(We noticed that if you unshare some of the maps until it is less than 7 then the maps works, it seems to be beyond a certain threshold that it starts to fail.)

**Comment by LindsayThomas** [comment]
I mistakenly posted this in the manager issue list here: https://github.com/Esri/crowdsource-manager/issues/335

@sumitzarkar Are you able to take a look at this issue and see if you can repro? If you can are you able to give us a LOE on a fix?

@skrishn FYI

**Comment by sumitzarkar** [comment]
@LindsayThomas  @skrishn 

We are analyzing this issue and will share the details soon

**Comment by skrishn** [comment]
@sumitzarkar Here is the sample app https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=dae170b0fb324f14990a1775e371f01e and I showed you on the call, the issue is n. Please investigate and share your findings. Thanks!!

cc @LindsayThomas

**Comment by sumitzarkar** [comment]
@LindsayThomas @skrishn 

We tried to reproduce this with all the above steps and also tried different combinations still we are not able to reproduce this issue.

@skrishn - As we tried on the call the other day you were also able to reproduce it only once. Please let us know if you are now able to consistently reproduce the issue. If you have time we can discuss it after tomorrow's call

**Comment by skrishn** [comment]
@sumitzarkar I am not able to repro it consistently. Let me try a few more things and call you

**Comment by sumitzarkar** [comment]
@LindsayThomas @aparveen 

@skrishn  As disussed on the last call we are able to reproduce this issue with following conditions:

1. There should be at least 8 webmaps present in the application.
2. First webmap in the application should contain vector basemap.
3. Issue is reproducible only on load for the first time. Once user clicked on any of the webmap present, the issue becomes un-reproducible.

We are still working on the fix and we have not found any solution till now.

Will update you once we found the solution

**Comment by aparveen** [comment]
@sumitzarkar do you have any update on this? if we don't have any fix by 11th, can we move to next release

**Comment by sumitzarkar** [comment]
@aparveen we have not fond any feasible solution to this issue. Let's push this to next release.

**Comment by sumitzarkar** [comment]
@aparveen  @skrishn 

### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   | - | ​
Required Backward compatibility​ | No  | -  | ​
Required 508​ | No  | -  | ​
Need Sanitize?​ | No  | - | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Other Impacting tickets | 1. #363 - **reporter not displaying vector basemaps** 
Runtime impacts |  <ol> <li>Webmap List</li> <li> Webmaps with/without vector base map</li><li>Webmaps less than 7 and greater than 7 in  webmaplist </li> <li>Webmaps having refrence layers are loading correctly or not </li> <li>Issue wall is loading correctly or not</li></ol>

**Comment by aparveen** [comment]
@sumitzarkar could you please make sure that your testing team test this change on both classic map viewer map and new map viewer maps?

**Comment by skrishn** [comment]
verified in dev

**Comment by skrishn** [comment]
verified in qa
