### ISSUE TITLE
Configuration should provide list of fields instead of free text entry

### ISSUE THREAD

**Issue by karmstro77** [Esri/crowdsource-reporter#53]
When on the configuration page for the app, the user must select fields containing # Votes, user credentials, etc. These are free text fields. It would be great if it were a pick list instead. This would remove the need for the user to go back and find the field name or perhaps misspell it.

![image](https://cloud.githubusercontent.com/assets/6819070/6672368/75a5ca76-cbe2-11e4-8d54-a6d607063558.png)

**Comment by allisonmuise** [comment]
@karmstro77  we did think about this, but this is a group template - there could (and likely will be) many maps, each with many layers, and each of those having many fields. I agree that a pick list would be easier to choose from *if it was short*, but many use cases will have dozens (if not hundreds) of fields across all the maps and layers. For this reason we chose to go with free-typed field names. If you have suggestions for building a pick list that would be manageable and an improved user experience, I'm open to suggestions!

**Comment by karmstro77** [comment]
Would it be possible to just have a pick list of all the web maps in the group. Once you select a web map, it populates another pick list of the available fields?

**Comment by allisonmuise** [comment]
The current AGOL app configuration panel doesn't have a parameter type that would support map>layer>field selection. It does have a layer>field selector, but then we're back to the problem of choosing which map to pull the layers and fields from.

Would you expect to need to set each of the fields on each of the layers in each o fthe maps?
