### ISSUE TITLE
Change graphic marking selected feature in map

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#54]
Please use a plain cyan square around the selected feature, rather than the current cyan square with crosshairs.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will change the highlight graphic in sprint 1.

**Comment by allisonmuise** [comment]
@ScottOppmann : Are you ok with the plain rectangle graphic?
cc @LindsayThomas

**Comment by ScottOppmann** [comment]
Yes, please proceed

**Comment by allisonmuise** [comment]
verified
