### ISSUE TITLE
The Citizen Problem Reporter button label is displayed as “Отчет” (Report) instead of “Подтвердить” (Confirm).

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#544]
**Workflow:**

1. Login to ArcGIS Online
2. Click on Organization > Settings > General
3. Under Organization defaults from Language option change the default language for members of your organization to to Russian.
4. Deploy and run Citizen Problem Reporter (see https://solutions.arcgis.com/local-government/help/citizen-problem-reporter/get-started/deploy-solution-online/)
5. Click on any problem tab
6. Click on “Submit problem” button
7. Left bottom button must be “Подтвердить” (Submit) but it is “Отчет” (Report).

**Note:**

- In HTML element inspector we see <div tabindex="0" role="button" data-dojo-attach-point="submitButton" class="esriCTGeoFormButton esriCTGeoFormSubmitButton esriCTEllipsis esriCTBGColor btn btn-default esriCTSubmitButton esriCTButtonTextColor esriCTButtonBackgroundColor" title="Подтвердить" aria-label="Подтвердить">Отчет</div>
- It must be:<div tabindex="0" role="button" data-dojo-attach-point="submitButton" class="esriCTGeoFormButton esriCTGeoFormSubmitButton esriCTEllipsis esriCTBGColor btn btn-default esriCTSubmitButton esriCTButtonTextColor esriCTButtonBackgroundColor" title="Подтвердить" aria-label="Подтвердить">Подтвердить</div>

**This element is in following part of the document:**

- document.querySelector("#geoFormBody > div.row > div.row > div > div.form-group > div > div.esriCTGeoFormButton.esriCTGeoFormSubmitButton.esriCTEllipsis.esriCTBGColor.btn.btn-default.esriCTSubmitButton.esriCTButtonTextColor.esriCTButtonBackgroundColor"

**Comment by aparveen** [comment]
We will look into this fall release, 2023.

**Comment by LindsayThomas** [comment]
We will not address this issue. Crowdsource Reporter will be moving to Mature Support in June 2024.
