### ISSUE TITLE
Option to make Report-It the default view after selecting webmap 

### ISSUE THREAD

**Issue by TFimpel** [Esri/crowdsource-reporter#55]
It might be more user friendly if on selecting a webmap/issue-category the geoform would be open by default, instead of the list view of existing issues. I say that because in most cases the primary reason a user goes to this map is to submit a new point. Reviewing and commenting on existing points is only the secondary purpose a user would visit this application. Especially if the map is empty it is very confusing. 
 
This would also solve issue #23.

Suggestions on how I can achieve that in the .js code would be very much appreciated, too. Overall very nice job on this template, thank you!!

**Comment by allisonmuise** [comment]
@TFimpel 
I completely agree. We're working with our design team right now on changes that will make submitting reports easier and more intuitive. One of the original requirements of this app was to display the list first to help avoid duplicate submissions, but that doesn't mean we need to bury the GeoForm in a menu. Our current plan is to put a 'report it' button right on the list (and map) itself. 

We're still working out the details of the other design changes we're going to make for the first full release of the app this summer, but over the next week or so you'll see lots of issues show up in this repo for re-designs of the tablet/desktop UI (that will address #23), the map-list-geoform flow through the app, and more.

Thanks for the feedback! I'm glad we're on the right track!

**Comment by TFimpel** [comment]
@allisonmuise thanks for the reply, I am very happy to hear that! Please also keep in mind that many organizations perceive displaying user-contributed content on a public-facing app as risky and/or costly to monitor. An option to disable much of the list view and only show the title of existing points on mouse-hover or tap might be useful. Thanks again!

**Comment by allisonmuise** [comment]
@TFimpel Yup, we've definitely thought of that. The content that's visible in the list view is driven by the popup in the source web map, so fields can be hidden in the app just by turning them off in the web map popup. We are also working on a series of solutions that will lay down a pattern of including a sort of spam filter field in the layers. The web map can then be filtered to show only the features that have been approved.

**Comment by TFimpel** [comment]
@allisonmuise 
Awesome!

**Comment by allisonmuise** [comment]
I'm going to close this issue since we have a lot of ongoing work that will address these points. Over the next weeks you'll see a lot of issues in this repo assigned to our developers that will be working towards resolving these workflow issues and more. 

If you see anything else we could be doing to make these apps work for you (have you seen crowdsource manager, the companion to this app?), or if you'd like to share what you're doing with these apps (I'd love to see it!) please either post here or email me directly at amuise@esri.com.
