### ISSUE TITLE
Add in-app help

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#56]
Add an in-app help window that will open in front of the app on desktop and tablet devices, and full-screen in front of the app on smartphones. This should not open in another tab - it should be part of the app.

The content of this window will be a block of text that will be configurable though the app configuration panel.

Help will be accessed by clicking an icon in the UI - location TBD. I am working with our design team to come up with the UI and will add it to this issue as soon as I have the comp and graphics. @CTLocalGovTeam : Once we have made these decisions I will assign this issue to you for work.

**Comment by allisonmuise** [comment]
see location in screenshot here: #59

**Comment by allisonmuise** [comment]
On smartphones, 'help' will be accessible from the menu, not from an icon in the title bar.

**Comment by allisonmuise** [comment]
user experience should be similar to the Polling app:
https://arcgis.github.io/crowdsource-polling/

**Comment by allisonmuise** [comment]
This was moved to the backlog due to time constraints.

**Comment by allisonmuise** [comment]
This help should also be accessible from the splash page via a configurable text link below the social media options. This configurable text should also be used in the smartphone menu UI.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Should the help link be lower level configuration or we want to allow users to configure it?

The configuration panel will have two parameters 
* Help window title
* Help window content

Please have a look at the screenshots below and let us know if these look ok.

**Help Link on splash screen**

![image](https://cloud.githubusercontent.com/assets/2959186/8722137/061f9b0c-2bdf-11e5-8748-d9774073364a.png)

**Help window on desktop**

![image](https://cloud.githubusercontent.com/assets/2959186/8722159/3ea4c0a6-2bdf-11e5-889f-41a485474ba2.png)

**Help window on mobile**

![image](https://cloud.githubusercontent.com/assets/2959186/8722165/50fc7adc-2bdf-11e5-9cce-b12785719f37.png)

**Comment by allisonmuise** [comment]
These look good! The following should be configurable through the AGOL app config panel:
- Help title
- Help text
- Splash screen help link text (Some users have said they'd like to use this to provide terms of use)

**Comment by allisonmuise** [comment]
On Desktop, please make the '?' graphic 18px

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is a screenshot after changing to 18px on desktops
![image](https://cloud.githubusercontent.com/assets/2959186/9218276/b320a728-40ee-11e5-8dc3-7f5d586adeee.png)

On mobiles, we will retain the size at 24px

**Comment by allisonmuise** [comment]
ok. Thanks!

**Comment by allisonmuise** [comment]
verified
