### ISSUE TITLE
Add search to map view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#57]
Add a search widget to the map view. This widget should search using the map search settings (geocoders and/or layers).

The widget should display like the search in this map: http://www.gisday.com/gis-day-events-map.html

**Comment by allisonmuise** [comment]
This was moved to the backlog due to time constraints.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are planning to use the search dijit with button mode enabled.This will search layers as well as geocoding services available in the organization.
The only limitation is that suggestions are available if working with a 10.3 geocoding service that has suggest capability loaded or a 10.3 feature layer that supports pagination, i.e. supportsPagination = true.

**Comment by allisonmuise** [comment]
Some questions about this: 
Will search results be returned when an older geocoding service is used? 
How is pagination set on a feature layer? 
Is feature layer pagination on or off by default?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
For older geocoding services, suggestions are not displayed as you type for sure, but I think if you click search icon it will display the first result. Need to confirm this.

Pagination is supported on AGOL hosted feature layers by default. For on-premise feature layers it is available 10.3 onwards.

**Comment by allisonmuise** [comment]
ok. As long as it displays search results (preferably multiple choices. I think the standard is 5?) I'm ok with this approach.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We just confirmed that for older geocoding services and feature layers, the Search dijit does not display suggestions or even results at all. The behavior we see is that after you type, you have to click the search icon or press enter. This zooms to the first result on map directly without showing any list of results.

For addresses, we can display a pushpin icon for the result. However, if its a feature layer result, is it expected to select the feature on map and display its details in the right pane? If we need to do this, then we can re-use the search functionality from Submit form. This would also support older geocoding services and feature layers.

After we remove geographic filtering the app is now going to display only features (map and list view) within a buffer around user's location. The feature layer result may be outside the buffer around user's location, thus it wont be present on the map or in list. In this case, the app can only highlight the feature. Feature symbol is not displayed, only a cyan box around it will be displayed.

**Comment by allisonmuise** [comment]
1. yes, I expect that, if a feature result is selected, the feature will load in the panel and be selected on the map.

2. Can the search be restricted to only loaded features?

**Comment by allisonmuise** [comment]
Can the search widget be moved down so that it is separated from the geolocate widget by the same distance as the geolocate widget is separated from the zoom out widget?

**Comment by allisonmuise** [comment]
Please use the search hint text that is configured with the map

Please use the search (address and layer) configuration that is set in the map properties.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Ok. We will use the search hint text that is configured in web map.
The search (address and layer) configuration is already implemented.

**Comment by allisonmuise** [comment]
search hint - ok
search configuration - you are correct. this was a map configuration error on my side.

**Comment by allisonmuise** [comment]
verified
