### ISSUE TITLE
consolidate panels (desktop/tablet view)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#59]
remove the left panel that displays the map/layer list.

On app load, display the map/layer list in the right-hand panel. Display the features from the first layer in the first map in the map area. If the first map has multiple layers, it should be expanded to show the layer list and the displaying layer should be emphasized (current behavior)

On selecting a map with multiple editable layers, keep the current behavior of expanding to show the layer list

On selecting a map with a single layer, or on selecting a layer from a map with one layer, replace the map/layer list with the list of features in that layer.

**Comment by allisonmuise** [comment]
This right-side panel should be fixed, not collapsible like the current one.

**Comment by allisonmuise** [comment]
![reporter1](https://cloud.githubusercontent.com/assets/2752195/6987597/ab45e08e-d9fd-11e4-90f7-1a02d4c56c2f.jpg)

*Notes:*
The following items should be in the configured theme color:
- App title
- map titles
- sign in/sign out/username/other item text in this menu

The 'i' button beside each map has the same function as the current '...' button

**Comment by allisonmuise** [comment]
info graphic:
![info](https://cloud.githubusercontent.com/assets/2752195/6989901/8844b7b8-da16-11e4-837a-ec3349f95494.png)

**Comment by allisonmuise** [comment]
Panel background is #F0F0F0
horizontal separators are 1px #ccc

**Comment by allisonmuise** [comment]
UPDATE to theme color use:
App title should be theme color
Map titles should be #555

**Comment by allisonmuise** [comment]
When a map has multiple editable layers, clicking the map should expand a list of #555 layer names on the same #F0F0F0 background. The map tile should be #F0F0F0 unless (on desktop) the cursor is hovering there. The backgrounds of the layers should also turn white on hover.

**Comment by allisonmuise** [comment]
![maplistspec](https://cloud.githubusercontent.com/assets/2752195/7239866/fe83d938-e761-11e4-878a-35d8b85b1965.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise As suggested in your comments on Apr 7 and subsequent discussions, we decided to display 
1. App title in theme color
2. Map titles and layer title in #555
3. '>' for layer titles in #555

Also we recommend to keep the size of info icon to 24x24 instead of 16x16 so that it is easily accessible on touch devices. 

Please refer the mockup below and confirm

**Comment by allisonmuise** [comment]
Please keep the info graphic at 16 x 16. It is too dominant on the screen at 24 x 24.

Please use a thinner line for the > arrows on the layers. They are only indicators that clicking/tapping the row will do something. They shouldn't draw you attention from the layer name on the other side of the screen.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise  Info graphic is re-sized to 16x16 px. Also we have decreased the thickness of > arrow.

Please find below the revised mockup.  

![image](https://cloud.githubusercontent.com/assets/2959186/7296799/774d9112-e9e0-11e4-9ea5-6af90c585d94.png)

**Comment by allisonmuise** [comment]
Looks good! Please proceed with this design

**Comment by allisonmuise** [comment]
verified
