### ISSUE TITLE
remove menu (smartphones) and report/sign in/my issues icons (desktop/tablet)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#60]
In smartphone view remove the current menu icon and the side panel that appears when it is clicked.  In tablet/desktop view remove the sign in, report it, and my issues buttons. 

In both cases these should be replaced with a small popover window like what is found in the Manager app.

Anonymous access: Display 'Sign In' in the top right corner

Authenticated user: display the name of account holder with a small down arrow in the top right corner. On clicking/tapping the name or the arrow display a popover windo with the followign items:
- My Reports (opens same as current My Issues options)
- Sign Out (behaves the same as the current sign out option)

All other removed elements will be incorporated into other areas of the app.

**Comment by allisonmuise** [comment]
UPDATE:
leave the menu icon in smartphone view, but style the menu like the Manager app.
For anonymous users the menu should contain:
- Sign In
- Help

For known users the menu should contain:
Name
- My Reports
- Sign Out
- Help

**Comment by CTLocalGovTeam** [comment]
@allisonmuise Based on the discussion last Friday, below are the two options for displaying menu items in smartphone. Please confirm.

Option 1 - Grey color font for menu items
![image](https://cloud.githubusercontent.com/assets/2959186/7370183/d7e0df18-edd5-11e4-98bc-1e99eff5b573.png)

Option 2 - Theme color font for menu items
![image](https://cloud.githubusercontent.com/assets/2959186/7370215/116e2574-edd6-11e4-9b09-2ad8dd1f33a3.png)

**Comment by allisonmuise** [comment]
Let's go with Option 1

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will incorporate this in sprint 3, after changing the grey background to white for username. The revised mockup is as displayed below.

![image](https://cloud.githubusercontent.com/assets/2959186/7808042/bffdc346-03ad-11e5-8f0a-5fbdd6f4a5b5.png)

**Comment by allisonmuise** [comment]
verified
