### ISSUE TITLE
add back button to list view header

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#63]
add a back button to the left side of the list view title bar. This button will return to the map/layer list.

@CTLocalGovTeam : I will provide a comp of this UI and a back button graphic, then assign this issue to you for work.

**Comment by allisonmuise** [comment]
![backbutton](https://cloud.githubusercontent.com/assets/2752195/6988553/5d466dae-da07-11e4-8089-55794441bbaf.png)

In list view this button should return to the map/layer list

**Comment by allisonmuise** [comment]
back arrow: 
![back-arrow](https://cloud.githubusercontent.com/assets/2752195/6989244/2da1d74e-da0e-11e4-9d12-6342715a3788.png)

**Comment by allisonmuise** [comment]
see #67  for spec

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will include back button (as per specs in #67) in sprint 1.

**Comment by allisonmuise** [comment]
verified
