### ISSUE TITLE
Add 'Report It' button to list and map view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#64]
Add a button below the list view panel for opening the geoform.
Add the same button to the bottom of the map view in smartphone mode

@CTLocalGovTeam : I will provide a comp for this UI, then assign this issue to you for work.

**Comment by allisonmuise** [comment]
![smartphonemapam](https://cloud.githubusercontent.com/assets/2752195/6988698/c85d0c1e-da08-11e4-87cd-763acc2d140e.png)
![smartphonelistam](https://cloud.githubusercontent.com/assets/2752195/6988700/cb52a0d2-da08-11e4-952d-dfae2cc56880.png)
![reporter2](https://cloud.githubusercontent.com/assets/2752195/6988702/cec7b928-da08-11e4-9f50-6e9dacc55d6f.jpg)
(note: we are still working on a toggle button between list and map view, but it will appear on the right side of the layer title bar)

**Comment by allisonmuise** [comment]
see #67  for spec

**Comment by allisonmuise** [comment]
Add button graphic:
![add](https://cloud.githubusercontent.com/assets/2752195/7239842/c799b76c-e761-11e4-903d-e836ee2da1a5.png)

**Comment by allisonmuise** [comment]
Map view spec:
![mapspec](https://cloud.githubusercontent.com/assets/2752195/7239997/c7b36350-e762-11e4-8373-973bcc66814c.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise In sprint 1, we will provide the 'Submit Report' button in list view; For map view, we will include it in sprint 3.

**Comment by allisonmuise** [comment]
verified on the list view.

**Comment by allisonmuise** [comment]
verified
