### ISSUE TITLE
use popup config for comment entry

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#65]
All editable fields in the related table should be presented for submitting comments, and the popup configuration should also be used for displaying comments in the comments list. 

Fields that are editable (regardless of their 'display' status) should be available for entry.

Comment entry parameters should match what is configured in the popup (multi-line/single-line text, date, etc)

Comments should display as configured in the popup configuration, including custom popup content.

As part of this, remove the Comment Field parameter from the app configuration.

**Comment by allisonmuise** [comment]
This was moved to the backlog due to time constraints

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Just wanted to update our approach for displaying/adding comments based on popup config.

* User can add comments from the issue details view.   
* When user is looking at issue details view, the comments that are already posted, are visible by default (screen 1). This is based on popup config.
* When user clicks 'Comment' button to add a new comment, then a form based on popup config is displayed at the top of Comments panel (screen 2). 
* When a feature does not have any comments, then the message "No comments available" is displayed as its done currently (screen 3).

![image](https://cloud.githubusercontent.com/assets/2959186/9174155/dda41574-3f9b-11e5-9ff6-8300c64b9b97.png)

**Comment by allisonmuise** [comment]
Looks good!

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Don't recall discussing this. Do we need to include support for attachments in the comments entry form?

Even if we do need that, we should'nt be displaying a "Gallery" button that opens and closes the attachments gallery for each comment. This will lead to many gallery buttons on the page.

We could display the grid of thumbnails just below the comment. But loading those gallery images could take a long time for all the comments. ArcGIS Server does not return only thumbnails of image attachments. The app fetches the complete image and then displays it as a thumbnail.

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam No, do not allow/display attachments for comments at this time.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : What will the impact of this change be on previously-configured apps? 
Will they:
a) continue to display the configured comments field
b) switch to showing all editable fields in the table
c) something else?

Ideally, I'd like the behavior to be (a) to avoid exposing additional info, and to allow users the opportunity to choose what info they'd like exposed...

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The impact of this change for existing users is that
* Users will directly see a comments entry form instead of a single text area
* The list of comments will use the popup configuration setting of the related table
* If popup is not configured for related table, then Comment button and list of comments will not be displayed

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I am concerned that this could expose information that users did not intend to reveal when they originally configured the app because by default all fields are visible and editable in the popup configuration. 

Please suggest an approach for exposing only the configured field in existing apps and allowing users to opt in to using the popup configuration for the comments form.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Agree. We will propose an approach to expose only configured field in existing apps and allow users to enable using popup configuration from configuration panel.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here's our approach to support popup config for comments.
* Add the configure comment field option back to configuration panel. Ensure it is exactly the same as earlier.
* Add a checkbox option to "Use popup configuration for comments". By default, this will be turned off.
* For existing apps, use geoform to display comments form 
    * Use the configured comments field for entry. 
    * Popup configuration of table is not considered.
    * Only one textarea is displayed in the form although additional fields may be editable. 
    * Currently, number of remaining characters is shown for entering comments in the released version. With the new codebase, this indication will not be available. This is because geoform validates by not allowing to type any further, after field limit is reached. It does not show remaining chars.
* The placeholder available in released version ("Type a comment") also will not be available. 

Please see screenshot below that compares old vs new using this approach and let us know if this is acceptable.

![image](https://cloud.githubusercontent.com/assets/2959186/10043401/693948d4-6210-11e5-9894-02e546b4ed6d.png)

**Comment by allisonmuise** [comment]
In the new version, please remove the double heading 'Comment'. I assume the bold header is the same as the Released Version, but where is the un-bold 'Comments' header coming from? 

Is there a way not to display 'Comments' before each comment?

Is there a way to preserve the horizontal lines between comments?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
>In the new version, please remove the double heading 'Comment'. I assume the bold header is the same as the Released Version, but where is the un-bold 'Comments' header coming from?  

The first heading is of the panel. The second heading is the alias of field for storing comments. This cannot be removed and it is referred to in the error messages, if any.

>Is there a way not to display 'Comments' before each comment? 

Yes we can display just the comment.  

> Is there a way to preserve the horizontal lines between comments?  

Yes, we can preserve the horizontal lines between comments.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : 

> The first heading is of the panel. The second heading is the alias of field for storing comments. This cannot be removed and it is referred to in the error messages, if any.

Let's remove the 'Comment' header over the form and just display the field aliases (The one over the displayed comments below should stay)

> Yes we can display just the comment.

If this is the field alias that is displaying per the popup configuration, please leave it.

> Yes, we can preserve the horizontal lines between comments.

ok

**Comment by allisonmuise** [comment]
verified
