### ISSUE TITLE
zoom to selected feature

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#66]
On selection of a feature from the list, zoom to the configured zoom level over that feature.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise Map and issue list will be in sync. Zooming to feature will refresh the issue list too. Hence we will existing behavior of highlighting the feature without zooming. Please confirm.

**Comment by allisonmuise** [comment]
yes, that is correct. I will move this issue to next release

**Comment by allisonmuise** [comment]
This was moved to the backlog pending removing geographic filtering from the app.

**Comment by allisonmuise** [comment]
verified
