### ISSUE TITLE
Update list view UI

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#67]
I am working with our design team to build a list view that will align with another crowdsourcing app we are working on. These changes will include removing the current comment, like, and map buttones from each item and displaying only the number of likes.

@CTLocalGovTeam : Please do not begin work on this until I assign this issue to you, complete with a comp and detailed description of each change. Much of this CSS will likely be able to be pulled from our other app. This issue is just a placeholder so that you are aware that this change is coming.

**Comment by allisonmuise** [comment]
![smartphonelistam](https://cloud.githubusercontent.com/assets/2752195/6988754/53fdf36e-da09-11e4-8af4-0e7ebf42fd6c.png)
![reporter2](https://cloud.githubusercontent.com/assets/2752195/6988756/59a9ab64-da09-11e4-9966-999a9f5e5723.jpg)

**Comment by allisonmuise** [comment]
Layer title and highlighting along left side of the mouse-over row are the theme color

**Comment by allisonmuise** [comment]
To minimize space requirements, the votes count on right side of each item should display numbers 1-999, then abbreviate using standard letters for thousands (k) 1k-999k

**Comment by allisonmuise** [comment]
Vote count font: Arial Bold, 20px, color #000 with 35% opacity
Item title font: Arial bold, 16 px, #000
all 1px border horizontal separators are #ccc
back arrow container is 30px wide by 50px high with an opacity of 30%
submit report button is Arial Bold, 22px, #fff

**Comment by allisonmuise** [comment]
'likes' graphic:
![like](https://cloud.githubusercontent.com/assets/2752195/6989909/a22530f4-da16-11e4-8aab-35c84b903f62.png)

**Comment by allisonmuise** [comment]
'back' graphic:
![back-arrow](https://cloud.githubusercontent.com/assets/2752195/6989919/d0170938-da16-11e4-9184-b1cc202f31b2.png)

**Comment by allisonmuise** [comment]
Issue titles are popup titles and they should be shown on one line. If they don't fit on one line, show an ellipsis. 

Submit Report button should be green, but this should be available in the configuration file (not the configuration UI)

**Comment by allisonmuise** [comment]
list -> map toggle
![map-pin](https://cloud.githubusercontent.com/assets/2752195/7008053/f93b699c-dc43-11e4-9aab-b0dfa3ffadf4.png)

**Comment by allisonmuise** [comment]
In desktop view only:
When returning to the list view from the details view, indicate the selected feature in the list by using the theme color in place of the #F0F0F0 background color of the selected list item.

**Comment by allisonmuise** [comment]
![issuesspec](https://cloud.githubusercontent.com/assets/2752195/7240008/d25db774-e762-11e4-9a44-561f802d2574.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
1. The votes count on right side of each item will be abbreviated using standard letters for thousands (k) 1k-999k based on the implementation in polling app
2. As per above mockup, the color for selection and on hover is same i.e white background with theme color line on left. We will maintain this instead of showing theme color for selected row. Please confirm.

**Comment by allisonmuise** [comment]
1. good
2.  This is a good point. This could be confusing in desktop view, so instead of having exactly the same indicator for selection and hover, can we do white background only on hover, and white background with theme-colored vertical bar on the left when selected?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise The hovered row will be displayed with white background. Selected row will be displayed with white background and theme-colored vertical bar on the left.

**Comment by allisonmuise** [comment]
Please make the + bolder. Like this:
![add](https://cloud.githubusercontent.com/assets/2752195/7403692/3b930556-ee8d-11e4-87e2-54e7778c2593.png)

Please also increase the space between the + and the words

**Comment by CTLocalGovTeam** [comment]
@allisonmuise  Sure. We will make  the + icon bolder and also increase the space between + icon and the words. We will include these changes in Sprint 2.

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann, @LindsayThomas As mentioned above, we will incorporate the above changes in sprint 2.

**Comment by allisonmuise** [comment]
This UI is complete so I am closing this issue. Any future bugs/enhancements will be tracked in new issues
