### ISSUE TITLE
Update details view UI

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#68]
I am working with our design team to build a details view that will align with another crowdsourcing app we are working on. These changes will include moving the current comment, like, and map buttons, and adding the comments to this frame.

@CTLocalGovTeam : Please do not begin work on this until I assign this issue to you, complete with a comp and detailed description of each change. Much of this CSS will likely be able to be pulled from our other app. This issue is just a placeholder so that you are aware that this change is coming.

**Comment by allisonmuise** [comment]
![advanced-detailed-comments](https://cloud.githubusercontent.com/assets/2752195/6988773/7cd04da0-da09-11e4-8f6a-2069af3ff10f.jpg)

![newcommentam](https://cloud.githubusercontent.com/assets/2752195/6988793/b1dd0772-da09-11e4-927c-6f53fcb4d8da.png)

Notes:
- Clicking the like button should increment the number shown in the title bar and invert the colors of the like button.
- Clicking the comment button should invert the colors of the comment button and open the comment form (form uses comment table popup config) in the space between the details and the previously-submitted comments. 
- Clicking the Comment button when the form is open should be the equivalent of clicking the Cancel button on the form - close the form without saving.
- Clicking the Gallery button should open a small pane immediately under the detail with the thumbnails for the attachments. Clicking the attachments should open them.
Item title bar should use theme color. Form buttons should stay blue/white.

**Comment by allisonmuise** [comment]
Gallery open:
![galleryam](https://cloud.githubusercontent.com/assets/2752195/6989236/0b3c6c00-da0e-11e4-9e57-3226e765b8bd.png)

**Comment by allisonmuise** [comment]
Spec:
![detailsspec](https://cloud.githubusercontent.com/assets/2752195/6989895/5ba25c9c-da16-11e4-891d-097ba2b2d3f3.png)

**Comment by allisonmuise** [comment]
'likes' graphic:
![like](https://cloud.githubusercontent.com/assets/2752195/6989913/ae667760-da16-11e4-9cc6-83b2aa755dfd.png)

**Comment by allisonmuise** [comment]
'back' graphic:
![back-arrow](https://cloud.githubusercontent.com/assets/2752195/6989923/e68050a8-da16-11e4-92f1-8ad68c2a323c.png)

**Comment by allisonmuise** [comment]
Comment button graphics:
![commentblue](https://cloud.githubusercontent.com/assets/2752195/6989931/fc792768-da16-11e4-9262-cebdb034cbb7.png)
![commentwhite](https://cloud.githubusercontent.com/assets/2752195/6989932/fe3cd784-da16-11e4-9d93-117f20015e8f.png)

**Comment by allisonmuise** [comment]
Gallery button graphics:
![galleryblue](https://cloud.githubusercontent.com/assets/2752195/6989933/06132a12-da17-11e4-841a-924217c55716.png)
![gallerywhite](https://cloud.githubusercontent.com/assets/2752195/6989934/077f702c-da17-11e4-9862-0429d83a0520.png)

**Comment by allisonmuise** [comment]
Likes button graphics:
![likewhite](https://cloud.githubusercontent.com/assets/2752195/6989942/174d2ea4-da17-11e4-8d45-fd540c90b25b.png)
![likeblue](https://cloud.githubusercontent.com/assets/2752195/6989941/174bbc36-da17-11e4-9b35-13db2d4dc998.png)

**Comment by allisonmuise** [comment]
Formatting of details and comments is driven by popups and should be handled as it is in the current app.

**Comment by allisonmuise** [comment]
'Liking' should remain as it is in the current app with the ability for a single user to 'like' an issue multiple times.

**Comment by allisonmuise** [comment]
Instead of the 50/50 split, the boundary between the details and the comments should adjust to fit the content. There will be a single scroll bar for this panel that will scroll everything from the title to the bottom of the panel.

If possible, the 'like', 'comment', and 'gallery' buttons should not scroll off the panel. If the details are longer than one screen, these buttons should 'stick' to the bottom of the panel. When scrolling down the content, they should be 'picked up' after the details. When scrolling up, if there are more comments than can display on a single screen, the buttons should 'stick' below the theme-colored title bar.

When open, the gallery should appear below the details.

When open, the comment submission form should appear above the previously submitted comments.

When both the gallery and comment form are open the order should be details, gallery, comment form, comments.

**Comment by allisonmuise** [comment]
![detailscommentspec](https://cloud.githubusercontent.com/assets/2752195/7239875/0a0de492-e762-11e4-9bfb-b62534d40a50.png)

**Comment by allisonmuise** [comment]
Note that the comments 'Submit' button is on the left and the 'Cancel' button is on the right

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will implement these changes for issues details in sprint 2. 

As mentioned above, we need to invert the color of the buttons when they are clicked. However, Map it and Like buttons can be clicked multiple times.  In this case, do we still need to invert the colors for these two buttons? Please suggest.

**Comment by allisonmuise** [comment]
Map It: This button does not need to invert when selected because it will take users to another page
Like: On the first click this button should turn blue, and it should stay blue on subsequent clicks.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We will not invert color for 'Map it'. 
We will retain inverted colors for 'Like' after first click. Each click on 'Like' will increment the Votes/Likes count.

**Comment by allisonmuise** [comment]
These UI changes have been implemented so I will close this issue. Future bugs/enhancements to this UI will be tracked in new issues.
