### ISSUE TITLE
add 'map' button to list view header (smartphone only)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#69]
In smartphone mode only, add a button to the right side of the list view header for toggling to the map view of the issues.

The map is always visible in desktop/table view so this button should not be visible in these modes.

@CTLocalGovTeam : I will provide a comp for this change and the graphic for this button, then assign this issue to you for work.

**Comment by allisonmuise** [comment]
![smartphonelistam](https://cloud.githubusercontent.com/assets/2752195/6988933/da7e29f8-da0a-11e4-8dd2-51e509c7dac7.png)

I do not have this graphic yet, but the toggle will go where the black square is shown above. I will add the graphic as soon as I get it

**Comment by allisonmuise** [comment]
list - > map view button:
![map-pin](https://cloud.githubusercontent.com/assets/2752195/7008097/48e6b794-dc44-11e4-8d79-afb3bad09783.png)
(graphic is white on transparent)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise In sprint 1, we will provide map view button in list view as user will not be able to navigate to map view while using smartphones. Below is the updated mockup.

**Comment by allisonmuise** [comment]
looks good!

**Comment by allisonmuise** [comment]
verified
