### ISSUE TITLE
Add 'list view' header to 'map view' (smartphone only)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#70]
Keep the list view header visible, even in map view. This header should include the back button for returning to the map/layer list ( #63 ). Instead of a 'map view' button on the right side ( #69 ) there should be a 'list view' button.

@CTLocalGovTeam : I will provide a comp for this UI change and the graphic for this button, then assign this issue to you for work.

**Comment by allisonmuise** [comment]
![smartphonemapam](https://cloud.githubusercontent.com/assets/2752195/6988944/f6c32fc8-da0a-11e4-8973-8cc1d25b113d.png)
I do not have this graphic yet, but the toggle will go where the black square is shown above. I will add the graphic as soon as I get it

**Comment by allisonmuise** [comment]
back arrow
![back-arrow](https://cloud.githubusercontent.com/assets/2752195/6989185/7ad6205c-da0d-11e4-9ca1-19ea1eb97355.png)

**Comment by allisonmuise** [comment]
Navigation icons are grey (not theme color)
Pleas swap the placement of the search and geolocation widgets from how theyare shown above. The order from top to bottom should be:
- zoom in
- zoom out
- geolocate
- search

**Comment by allisonmuise** [comment]
map view -> list view icon
![list](https://cloud.githubusercontent.com/assets/2752195/7008074/27168b4e-dc44-11e4-8eb5-27617b75b545.png)
(graphic is white on transparent)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will include following in sprint 3. 
1. Navigation icons in grey color
2. As discussed during one of the sprint reviews, 'Search' icon will be removed from map; So the order of the icons from top will be
* zoom in
* zoom out
* geolocate

Below is the revised mockup
![image](https://cloud.githubusercontent.com/assets/2959186/7742892/67835e46-ffb2-11e4-9fcf-1a0d1b5363ff.png)

**Comment by allisonmuise** [comment]
verified
