### ISSUE TITLE
load geoform map with current map extents

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#71]
The map in the geoform should load with the same extents as the current map view.

If implementing this change will put resolving other issues at risk, please let me know. This is not a priority.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will load the map with current map extent while displaying the geoform. We will implement this in sprint 2.

**Comment by allisonmuise** [comment]
The geoform map loads with the main map extents, but after submitting a report the geoform map returns to the full extent of the web map. The geoform map should re-load at the current extents of the main map. If the main map extents have changed, the geoform map should reflect the new extents.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will include the fix in sprint 3.

**Comment by allisonmuise** [comment]
verified
