### ISSUE TITLE
Submit report UI

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#74]
![reporter5](https://cloud.githubusercontent.com/assets/2752195/7008135/9d383c96-dc44-11e4-8f52-78c63e8f4ab8.jpg)

**Comment by allisonmuise** [comment]
![geoformspec](https://cloud.githubusercontent.com/assets/2752195/7239851/e55de458-e761-11e4-8f27-b3569c419f7f.png)

**Comment by allisonmuise** [comment]
Note that the 'Submit' button is now on the left and 'cancel' is on the right

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
In sprint 1, 
1. We will place the geolocation icon next to search button and will remove it from map
2. Apply new styles to the buttons in geoform
Remaining changes will be implemented in sprint 2

**Comment by allisonmuise** [comment]
Are the following planned as part of sprint 2, or should I create separate issues for them?
1. Make search and geolocate buttons the same height as the search box
2. Report It button should be theme color with white text
3. There should be a Cancel button to the right of the Submit button

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will include the above mentioned changes in Sprint 2 and should be able to track them using this issue only. 
We will implement these changes as mentioned below
1. Search and geolocate buttons will have same heights as that of the text box                          
2. When GeoForm is loaded, 'Report it' button will be shown in theme color background with white text; These colors will be inverted when user clicks the 'Report it' button  
3. Cancel button will be shown to right of the submit button.

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann, @LindsayThomas As mentioned above, we have planned to include the changes for search & geolocate button, 'Report it' button and cancel button in sprint 2.

**Comment by allisonmuise** [comment]
This main dev work is completed so I am closing this issue. Any bugs or enhancements for this UI will be tracked in new issues.
