### ISSUE TITLE
Update UI for My Issues

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/crowdsource-reporter#75]
1. Authenticated smart phone users can access ‘My Issues’  from menu icon
2. Authenticated tablet and desktop users can tap ‘Caret’ icon or user name; then tap ‘My Issues’ 
3. List of My issues will be displayed with 
  * App Title bar followed by Layer Title bar
  * Layer Title bar will show ‘My Issues’; configurable from NLS
  * Webmap name and Layer name will be displayed with ellipses (if required) on first line 
  * Popup title will be displayed with ellipses (if requried) on second line
6. Tapping ‘Back’ will navigate users to List of webmaps
5. Users can tap on a row to view issue details
7. Tapping 'Back' on issue details will navigate user back to My Issues
8. Tapping 'Map it' on issue details will navigate user to Map View
9. Tapping 'List view' on map view will navigate user back to My issues

UI for My Issues

![image](https://cloud.githubusercontent.com/assets/2959186/7231793/4c35e18e-e795-11e4-8e95-34deb01381f7.png)

Tapping an issue will open issue details
![image](https://cloud.githubusercontent.com/assets/2959186/7231829/7f74f15c-e795-11e4-9375-a67485eb6602.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam  Looks good! Please proceed.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise Based on discussions during sprint 2 review meeting, there are following minor changes to the workflow when user is viewing the map.
1. Clicking 'Back' will navigate user to issue details
2. Clicking 'List' icon will navigate user to Webmap list
This behavior will replace bullet number 8 from above comment.

Below is the mockup for Map view for your ready reference 
![image](https://cloud.githubusercontent.com/assets/2959186/7676724/f8f76f9e-fd63-11e4-955f-2dcf16d6f8af.png)

**Comment by allisonmuise** [comment]
verified
