### ISSUE TITLE
Cannot sign into app using Google+

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#77]
The Google+ UI has changed slightly, but I am still able to follow the steps. After I updated my application to use the resulting Client ID, I clicked the Google+ icon on the Reporter splash screen and accepted the disclaimer, but the app did not take me to the map list – it stayed on the splash screen.

cc @MikeTschudi

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
After updating the application to use the resulting Client ID, we also need to ensure that the "Google+ API" and "Google+ Domain API " both are enabled for the configured client ID from Google's developer console.  Could you please confirm if both of them are enabled? Please refer the below screenshot to check the enabled APIs. 

 
![image](https://cloud.githubusercontent.com/assets/2959186/7450359/9950d3a8-f261-11e4-9714-06efe93d6d5c.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise As suggested by Mike, we have verified that "Google+ Domain API " is not required. We will update the documentation to include this.

**Comment by allisonmuise** [comment]
verified that I can sign into the app once the googleplusScope variable in default.js was set to https://www.googleapis.com/auth/userinfo.email
