### ISSUE TITLE
unexpectedly prompted for credentials

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#81]
When working with non-public apps I am asked for my credentials, even though I'm access these apps from inside an organization.

For example:
1. Create an app from a group
2. Don't share the app
3. Open the configuration experience for the app
4. I am prompted for credentials, even though I am still signed in to my org and the browser should be using those credentials.

If possible, please fix for sprint 2.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
When you click 'Configure App', do you see the sign-in page? You should see the sign-in page with options to login as Guest and AGOL. If you click on AGOL sign in, you will be auto signed in, since you are logged into the Org in another tab. Can you please confirm this.
If you are still seeing a sign in dialog after signing in with AGOL, then it may be due to an item (webmap or a layer) to which you do not have access.

**Comment by allisonmuise** [comment]
I am being prompted for credentials by the identity manager even before the app loads the splash screen. I own the app , the group, and all content in the group (maps and associated data)

**Comment by allisonmuise** [comment]
This same workflow does not cause me to be prompted for credentials with Basic Viewer or Public Gallery.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, 
Do you see the sign in page of the Organization or do you see the identity manager dialog asking for credentials?
Can you pls provide a screenshot of the identity manager being displayed that includes the browser address bar. 
Is it possible to share a link to the app so we can try to repro it on our end.

**Comment by allisonmuise** [comment]
I will demonstrate the workflow and behavior in our meeting Monday.

**Comment by allisonmuise** [comment]
I can't reproduce this anymore - even with the same I I saw it in earlier. I must have been signed into multiple organizations or something.

**Comment by allisonmuise** [comment]
a repro case has been recorded as part of #87 so I am re-opening this issue.

**Comment by allisonmuise** [comment]
I am also seeing this behavior in Manager

**Comment by allisonmuise** [comment]
cc @previnWong  - I know you are working on this for Polling as well.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @previnWong 

Can you please confirm if removing the trailing slash in `"sharinghost": location.protocol + "//" + "arcgis.com/",` in default.js fixes this issue?

**Comment by previnWong** [comment]
@CTLocalGovTeam removing the trailing slash does not resolve the issue.

![image](https://cloud.githubusercontent.com/assets/11183838/7838754/79c50736-0443-11e5-9de6-81b2e42f9df0.png)

![image](https://cloud.githubusercontent.com/assets/11183838/7838763/83359d1c-0443-11e5-8503-6b4fad0bf054.png)

It is not getting pass the ```_checkSignIn``` function.  The deferred that is returned states an error that user is not signed in.  Take a look at the screen shots.  You can see that I am signed into the org in the first tab, and my app is on the second tab.

![image](https://cloud.githubusercontent.com/assets/11183838/7838736/5dd6ccbc-0443-11e5-9e2d-d16a045c19cb.png)

![image](https://cloud.githubusercontent.com/assets/11183838/7838745/6b79c838-0443-11e5-8ae6-e930bb2df327.png)

**Comment by previnWong** [comment]
Both the polling app and the boilerplate template throws this sign in.  Seems like it's not looking for the oauth that is already stored.
![image](https://cloud.githubusercontent.com/assets/11183838/7840224/2e8f9d8c-044b-11e5-9a70-85ef969ade3a.png)

will check the basic viewer (which works) files with the polling to see where the differences are.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : To clarify - the issue @previnWong is seeing with Polling is the inappropriate sign in whereas, per the call this morning, the trailing slash is the cause of the double sign-in issue.

**Comment by previnWong** [comment]
@CTLocalGovTeam @allisonmuise My guess on what is happening is that the application template and map resources are running on different domains.  So the application template does not have access to the esri_auth cookie in the AGOL domain, thus prompting the sign in.  We tested by making a basic viewer with the same configuration setup as the crowdsource polling app and the credential pop up appeared.  Next test would be to place the polling template in the same domain.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam @previnWong 
I have confirmed that this issue is non-repro in devext, where both the app code and the app content are hosted on the same domain.

closing!
