### ISSUE TITLE
Add configuration parameter for enabling/disabling AGOL sign ins

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#82]
Please expose a configuration panel parameter for enabling/disabling the AGOL sign in button on the sign-in page. 

This option will need to be enabled by default to avoid breaking existing apps

If no sign-in options are selected please hide the 'or' bar and 'sign in with' text on the splash page

Please let me know ASAP if this will impact the delivery of this sprint.

**Comment by CTLocalGovTeam** [comment]
We can accommodate this change in Sprint3.
After implementing this change if all the sign-in types are disabled 'sign-in' menu in app-header/mobile menu-list will not be available and  splash page will look as follows :
![home screen](https://cloud.githubusercontent.com/assets/2959186/7627775/7e498a80-fa38-11e4-8fbf-79c7ebf5bd8a.PNG)

**Comment by allisonmuise** [comment]
Thanks!

**Comment by allisonmuise** [comment]
verified
