### ISSUE TITLE
Consider allowing display/editing of multiple layers within a single view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#84]
Suggested by Damian:
Multiple feature types.  It would be nice if I could have just said – report an error – and the user choose by picking the tool to use pt, line, or poly to report it and I didn’t make them know about them upfront.

Visibility – when switching which layer to report the other layers are no longer visible.  But in my case people may want to see other reports as someone may have put in a pt for an error and another put in a polygon for the same error.  I’d like the layers to stay visible on map in in list on right. And if a use clicks one – show its popup.

**Comment by nfeuerstein** [comment]
@phil7277 and I identified the same need when creating a "crowd source" reporting app for multiple types of intelligence reports.

**Comment by allisonmuise** [comment]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/887

**Comment by allisonmuise** [comment]
cc: @dcesri

**Comment by allisonmuise** [comment]
Displaying multiple layers is going to be considered for 4.2 and can be tracked in issue #147 .

**Comment by allisonmuise** [comment]
display of supporting layers is included in AGOL 4.2
