### ISSUE TITLE
Consider allowing editing in either map in desktop view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#85]
Allow users to draw features in either the main map or the report form map. Features should be visible as they are drawn in both maps.

**Comment by TonyGT** [comment]
I agree. It would be better if users could draw features in the main map. How can we switch maps via the code?

**Comment by DShokes** [comment]
+1 It would also be useful if authors could toggle visibility of existing features on the layer on the big map. If visibility were enabled, users would be less likely to duplicate an existing feature. Disabling visibility might be prefered if reporter should not see other user entries.

**Comment by allisonmuise** [comment]
@DShokes : You can toggle the visibility of features using a filter in the web map. Any features that don't meet the filter requirements will not be visible in the app. This way you can moderate posts - for example only show features where APPROVED='Yes', or SENSITIVE='No'. You can use default values (defined on the fc before publishing) to determine the initial value of those fields, which can then be updated through Crowdsource Manager.

**Comment by allisonmuise** [comment]
@TonyGT : There isn't a way to make this change through the configuration process, but allowing editing in both maps is under consideration for a future release. While you are welcome to customize the code, changing the editing behavior of the app would be a significant customization project that goes beyond the current scope of the app.

**Comment by TonyGT** [comment]
Thanks, Alison. I think it would be a great addition. It seems more intuitive to draw on the large screen. Thanks for your quick response.

Tony

**Comment by DShokes** [comment]
@allisonmuise thanks for the info.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : In summary, when the Geoform panel is open (desktop/tablet modes only), allow feature creation in both the main map and the geoform map.

**Comment by TonyGT** [comment]
Thanks, Allison. We appreciate the help.

Tony


________________________________

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

If user draws graphic in main map it will automatically be drawn on the geo form map and vice-versa in real-time. Also any graphic drawn on main map will be cleared if user cancels or backs out of geoform. Please see the actual implementation here and let us know your comments.

![cr_editing](https://cloud.githubusercontent.com/assets/2959186/12321275/319ac77e-bad3-11e5-90af-479392e69967.gif)

**Comment by allisonmuise** [comment]
perfect!

**Comment by TonyGT** [comment]
I tried implementing and it doesn't seem to work. I am still unable to draw in the main map. Any advice?  I downloaded the code from github and deployed it here
http://www.prism.gatech.edu/~ag124/Ocean/

Also, app link on arcgis.com is http://gcmp.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=0f6352f75e384edea359569b47d7e854

**Comment by allisonmuise** [comment]
@TonyGT : This change has not been implemented publicly yet. This functionality will be coming in the summer release of ArcGIS Online.

**Comment by TonyGT** [comment]
Thank you. Looking forward to it.

**Comment by allisonmuise** [comment]
verified - @TonyGT : This change is in the develop branch of this repo and will be included with the next release of AGOL
