### ISSUE TITLE
does not display fetures with symbol by color or symbol by size symbology

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#89]
when features are symbolized using the smartmapping options 'Counts and Amounts (color)' or 'Counts and Amounts (Size)' this is not reflected in the application. In the app all features are displayed with the same symbol.

The unique value and location only renderers work as expected.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We able to display these renderers. Please look at the screenshots below.
However we did find that clicking on any feature with these renderers does not highlight the features.
Can you please share a sample web map that we can use and try to reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/2959186/7798320/1edec84e-0316-11e5-825e-43df3cd50bbc.png)

![image](https://cloud.githubusercontent.com/assets/2959186/7798327/2694eb7c-0316-11e5-8b39-19d7b4601950.png)

**Comment by allisonmuise** [comment]
I can't repro on any other datasets, so I'm closing this issue.
