### ISSUE TITLE
state plane map won't load

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#90]
when both the basemap and datasets are in state plane, nothing loads in the feature list or the map view - not even the basemap.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to reproduce this issue.
We have shared some state plane (basemap + dataset) web maps in the [demo link for sprint 2](http://csslesxi9-vm3.cybertech.com/CSReporter/V0.7/index.html).
Can you please share a web map that doesn't work for you ?

**Comment by allisonmuise** [comment]
non-repro
