### ISSUE TITLE
Add sign in page 'Or' to NLS

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#91]
The 'Or' on the sign in page between the guest sign in and the social media sign in options is not in the NLS file. Please make this string localizable.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
The 'Or' is actually an image. The enveloping circle and horizontal line you see is also part of that image. Changing this to text will need some work. 
Need to handle text of different lengths e.g., 'Or' in Spanish is 'Oregon'.

**Comment by allisonmuise** [comment]
This string must be made localizable and the circle should expand horizontally into an oval to accommodate longer translations in other languages.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here is an example of what it would look like with text sourced from NLS.

![image](https://cloud.githubusercontent.com/assets/2959186/7880445/0c9534da-0617-11e5-864e-cb082dd6420e.png)

**Comment by allisonmuise** [comment]
Thanks, this looks good

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We've incorporated and tested this issue. Considering the upcoming code-freeze for June release, would you like us to provide an early code drop?

**Comment by allisonmuise** [comment]
Yes. Please submit a pull request as soon as possible with this fix.

**Comment by allisonmuise** [comment]
verified
