### ISSUE TITLE
Range domains are not enforced

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#93]
Fields with a range domain do not require you to enter a value in that range before you submit a report.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

If the range field is not mandatory the application will allow user to submit a form with blank value in range field.

**Comment by allisonmuise** [comment]
Yes, that's ok, but if a value is supplied to a field with a range domain, the app should verify that the values falls within the range of values specified by the domain.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise @ScottOppmann  @LindsayThomas 

We are unable to reproduce this. Can you please provide us steps to reproduce.

**Comment by allisonmuise** [comment]
I can't repro anymore either. closing.
