### ISSUE TITLE
IE9 - Newly added features failed to show up on map

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#99]
@CTLocalGovTeam : Please investigate this issue

1.	Open any reporter app in IE 9 and sign is (for example as Guest).
3.	Click on a map in the list and if necessary choose a layer
5.	Click ‘Submit report’
6.	Fill out the form
7.	Add a feature on the map  
8.	Click ‘Report It’. 
9.	Notice the message “Thank You! Your report is submitted” but the map doesn’t show the newly added feature. 
Features only draw after refreshing the map

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are investigating the issue and we will keep you updated.

**Comment by allisonmuise** [comment]
Thanks!
UPDATE: we are seeing this in IE10 as well.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This seems to be a known issue in IE Browser.A similar discussion can be found here in this thread on GeoNet.
https://geonet.esri.com/thread/9644

**Comment by allisonmuise** [comment]
There are several suggested work-arounds in that thread. Are any of them suitable for this app?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We investigated the issue further and found that, if layer is hosted on AGOL the newly added feature is not shown on map after refreshing the layer. But it does work well when layer is sourced from ArcGIS server.
